import type { ConfigContext, ExpoConfig } from 'expo/config';
import {
  withAppBuildGradle,
  withAppDelegate,
  withInfoPlist,
  withXcodeProject,
  type ConfigPlugin,
} from 'expo/config-plugins';

/**
 * Expo config as TypeScript so one codebase can produce three apps.
 *
 * `APP_VARIANT` selects the environment at build time. Bundle identifiers differ per variant
 * on purpose: development, preview and production installs must be able to coexist on one
 * device, or testers end up overwriting the build they were asked to verify.
 */
type Variant = 'development' | 'preview' | 'production';

const VARIANT = (process.env.APP_VARIANT as Variant | undefined) ?? 'development';

const NAME: Record<Variant, string> = {
  development: 'Pahad Pulse (Dev)',
  preview: 'Pahad Pulse (Preview)',
  production: 'Pahad Pulse',
};

const BUNDLE_SUFFIX: Record<Variant, string> = {
  development: '.dev',
  preview: '.preview',
  production: '',
};

const BASE_BUNDLE_ID = 'in.pahadpulse.app';

/** Accessible interface blue derived from the logo. Keep in step with `src/theme/tokens.ts`. */
const BRAND_BLUE = '#075E9C';

/**
 * The public endpoints each variant talks to.
 *
 * These live here, not only in `eas.json`, because the store archive is built in Xcode and
 * Xcode has no EAS environment. 1.0.0 (2) shipped to TestFlight with
 * `http://localhost:3000/api` inlined into the bundle — the JS is bundled by a build phase
 * during the archive, `EXPO_PUBLIC_API_URL` was unset there, and `src/config/env.ts` fell
 * back to its development default. The app launched and then failed every request against
 * the reader's own phone.
 *
 * Neither value is a secret: both are already committed in `eas.json` and `render.yaml`.
 * An `EXPO_PUBLIC_*` variable in the environment still wins, so EAS and `expo start` are
 * unaffected; this is the floor under a build that has no environment at all.
 *
 * This replaces an `assertProductionUrl` check that threw when the variables were missing at
 * config time. It could not have caught this bug: the Xcode archive never evaluates a
 * production EAS environment, and Expo loads the developer's local `.env` — with its
 * localhost values — inside the bundling step itself. The check that does catch it reads the
 * bundle that was actually produced, in `withBundleEnvironment` below.
 */
const PUBLIC_URLS: Record<Variant, { api: string; web: string }> = {
  development: { api: 'http://localhost:3000/api', web: 'http://localhost:3001' },
  preview: { api: 'https://pahadpulse.onrender.com/api', web: 'https://www.pahadpulse.live' },
  production: {
    api: 'https://pahadpulse.onrender.com/api',
    web: 'https://www.pahadpulse.live',
  },
};

/**
 * The Expo SDK 57 prebuild template sets `ENABLE_USER_SCRIPT_SANDBOXING = YES`, but the
 * "Bundle React Native code and images" phase declares no output paths. A sandboxed phase may
 * only write declared outputs, so a Release archive bundles the JS and is then denied writing
 * `main.jsbundle` (EPERM). Debug skips bundling, which is why only archives fail.
 *
 * `/ios` is gitignored and regenerated by prebuild, so the override has to live here rather
 * than in the Xcode project. See `IOS_ARCHIVE_FIX_HANDOFF.md`.
 */
const withScriptSandboxingDisabled: ConfigPlugin = (config) =>
  withXcodeProject(config, (modConfig) => {
    const configurations: Record<string, unknown> =
      modConfig.modResults.pbxXCBuildConfigurationSection();

    for (const entry of Object.values(configurations)) {
      // The section also holds `<id>_comment` string entries alongside the real configurations.
      if (typeof entry !== 'object' || entry === null || !('buildSettings' in entry)) continue;
      const { buildSettings } = entry as { buildSettings: Record<string, unknown> };
      buildSettings.ENABLE_USER_SCRIPT_SANDBOXING = 'NO';
    }

    return modConfig;
  });

/**
 * Give the JS bundling phase an environment, and refuse to ship one built without it.
 *
 * `expo export:embed` runs inside the "Bundle React Native code and images" phase during a
 * Release build, inheriting whatever Xcode has — which, for an archive started from the
 * Xcode UI, is nothing. The exports below only fill in what is missing, so a shell or EAS
 * build that already set them is untouched.
 *
 * The check afterwards is the part that matters: it reads the bundle that was just written
 * and fails the build if the development fallback is in it. A wrong base URL is invisible
 * until someone installs the build and every screen shows a network error, which is exactly
 * how 1.0.0 (2) reached TestFlight.
 */
const BUNDLE_PHASE_NAME = 'Bundle React Native code and images';

function bundleEnvironmentPrelude(variant: Variant): string {
  const { api, web } = PUBLIC_URLS[variant];
  return [
    `export APP_VARIANT="\${APP_VARIANT:-${variant}}"`,
    `export EXPO_PUBLIC_API_URL="\${EXPO_PUBLIC_API_URL:-${api}}"`,
    `export EXPO_PUBLIC_WEB_URL="\${EXPO_PUBLIC_WEB_URL:-${web}}"`,
    '',
  ].join('\n');
}

const BUNDLE_URL_GUARD = [
  '',
  '# What shipped in 1.0.0 (2): a bundle with no API URL inlined, falling back to localhost.',
  '# The check is for PRESENCE of the expected URL, never absence of the fallback — the',
  '# fallback is a literal in src/config/env.ts and is in every bundle either way.',
  'if [ "$CONFIGURATION" = "Release" ]; then',
  '  BUNDLE="$CONFIGURATION_BUILD_DIR/main.jsbundle"',
  '  if [ ! -f "$BUNDLE" ]; then',
  '    echo "error: no main.jsbundle was produced for a Release build." >&2',
  '    exit 1',
  '  fi',
  '  if ! grep -q "$EXPO_PUBLIC_API_URL" "$BUNDLE"; then',
  '    echo "error: $EXPO_PUBLIC_API_URL is not in the bundle, so the app would fall back to" >&2',
  '    echo "localhost — exactly what shipped in 1.0.0 (2). See PUBLIC_URLS in app.config.ts." >&2',
  '    exit 1',
  '  fi',
  'fi',
].join('\n');

const withBundleEnvironment: ConfigPlugin = (config) =>
  withXcodeProject(config, (modConfig) => {
    const phases: Record<string, unknown> =
      modConfig.modResults.hash.project.objects.PBXShellScriptBuildPhase ?? {};

    let patched = false;
    for (const phase of Object.values(phases)) {
      if (typeof phase !== 'object' || phase === null || !('shellScript' in phase)) continue;
      const entry = phase as { name?: string; shellScript: string };
      if (entry.name?.includes(BUNDLE_PHASE_NAME) !== true) continue;

      // `shellScript` is stored as a quoted, escaped string; JSON round-trips it faithfully.
      const script: string = JSON.parse(entry.shellScript);
      if (script.includes('EXPO_PUBLIC_API_URL')) return modConfig; // already patched
      entry.shellScript = JSON.stringify(
        bundleEnvironmentPrelude(VARIANT) + script + BUNDLE_URL_GUARD
      );
      patched = true;
    }

    if (!patched) {
      throw new Error(`Could not find the "${BUNDLE_PHASE_NAME}" build phase to patch.`);
    }

    return modConfig;
  });

/**
 * Copy vendored dSYMs into the archive.
 *
 * Every framework here ships as a prebuilt `.xcframework`, and Xcode copies only some of
 * their dSYMs into the archive. Uploading 1.0.0 (2) produced eight "Upload Symbols Failed"
 * warnings — yet five of those frameworks (ExpoImage and the four SDWebImage ones) carry a
 * dSYM inside the xcframework with exactly the UUID Apple asked for. This phase copies any
 * it finds next to the ones Xcode collected.
 *
 * `React`, `ReactNativeDependencies` and `hermesvm` ship with no dSYM at all: they are
 * downloaded release artifacts. Symbolicating those would mean building React Native from
 * source (`ios.buildReactNativeFromSource`), which costs far more archive time and disk than
 * readable third-party frames are worth. Those three warnings are expected and harmless —
 * they never affect review, only the readability of crash reports inside those frameworks.
 *
 * Release only: a debug build has no archive to fill, and `DWARF_DSYM_FOLDER_PATH` is then
 * the ordinary build folder.
 */
const COPY_VENDORED_DSYMS = [
  'if [ "$CONFIGURATION" != "Release" ]; then exit 0; fi',
  'if [ -z "$DWARF_DSYM_FOLDER_PATH" ] || [ ! -d "$PODS_ROOT" ]; then exit 0; fi',
  'mkdir -p "$DWARF_DSYM_FOLDER_PATH"',
  '# -L because CocoaPods symlinks vendored xcframeworks into node_modules; without it find',
  '# walks straight past SDWebImage and friends, which is likely why Xcode missed them too.',
  '# Device slice only — a simulator dSYM would collide on name and is never uploaded.',
  'find -L "$PODS_ROOT" -maxdepth 8 -type d -path "*/ios-arm64/dSYMs/*.framework.dSYM" -prune -print0 |',
  '  while IFS= read -r -d "" dsym; do',
  '    name=$(basename "$dsym")',
  '    if [ ! -d "$DWARF_DSYM_FOLDER_PATH/$name" ]; then',
  '      cp -R "$dsym" "$DWARF_DSYM_FOLDER_PATH/" && echo "copied $name"',
  '    fi',
  '  done',
].join('\n');

const DSYM_PHASE_NAME = 'Copy vendored dSYMs';

const withVendoredDsyms: ConfigPlugin = (config) =>
  withXcodeProject(config, (modConfig) => {
    const project = modConfig.modResults;
    const phases: Record<string, unknown> =
      project.hash.project.objects.PBXShellScriptBuildPhase ?? {};

    // Prebuild regenerates `/ios`, but a second run over the same directory must not stack
    // duplicate phases.
    for (const phase of Object.values(phases)) {
      if (typeof phase === 'object' && phase !== null && 'name' in phase) {
        const { name } = phase as { name?: string };
        if (name?.includes(DSYM_PHASE_NAME) === true) return modConfig;
      }
    }

    project.addBuildPhase([], 'PBXShellScriptBuildPhase', DSYM_PHASE_NAME, undefined, {
      shellPath: '/bin/sh',
      shellScript: COPY_VENDORED_DSYMS,
    });

    return modConfig;
  });

/**
 * The signing team, written into every build configuration.
 *
 * `ios.appleTeamId` alone is read by EAS but NOT applied by prebuild, so the generated
 * project came out with no `DEVELOPMENT_TEAM` and the store archive had to have the team
 * picked by hand in Xcode after every prebuild — easy to forget, and the failure appears
 * only at the signing step of a long archive. `/ios` is regenerated, so this belongs here.
 */
const APPLE_TEAM_ID = '9Q56J23Z23';

const withDevelopmentTeam: ConfigPlugin = (config) =>
  withXcodeProject(config, (modConfig) => {
    const configurations: Record<string, unknown> =
      modConfig.modResults.pbxXCBuildConfigurationSection();

    for (const entry of Object.values(configurations)) {
      // The section also holds `<id>_comment` string entries alongside the real configurations.
      if (typeof entry !== 'object' || entry === null || !('buildSettings' in entry)) continue;
      const { buildSettings } = entry as { buildSettings: Record<string, unknown> };
      // Only the app target carries a bundle identifier; the Pods targets must stay untouched.
      if (buildSettings.PRODUCT_BUNDLE_IDENTIFIER === undefined) continue;
      buildSettings.DEVELOPMENT_TEAM = APPLE_TEAM_ID;
    }

    return modConfig;
  });

/**
 * UIScene lifecycle adoption, required from iOS/iPadOS 27.
 *
 * iOS 27 terminates any UIKit app that launches without a `UIApplicationSceneManifest`
 * (`_UIApplicationEvaluateRuntimeIssueForNoSceneLifecycleAdoption`, EXC_BREAKPOINT on launch).
 * App Review rejected 1.0.0 (1) for exactly this. The Expo SDK 57 template still creates the
 * window in `didFinishLaunchingWithOptions`, so the template is rewritten here: the app delegate
 * only builds the React Native factory, and a scene delegate owns the window and starts React.
 *
 * Under scenes UIKit no longer calls the app delegate's open-URL / user-activity methods, so
 * the scene delegate forwards deep links to `RCTLinkingManager`, and a cold-start link is passed
 * in as launch options so `Linking.getInitialURL()` still sees it.
 *
 * Anchors are asserted, not replaced best-effort, so a changed template fails at prebuild.
 */
const TEMPLATE_WINDOW_START = `#if os(iOS) || os(tvOS)
    window = UIWindow(frame: UIScreen.main.bounds)
    factory.startReactNative(
      withModuleName: "main",
      in: window,
      launchOptions: launchOptions)
#endif
`;

const SCENE_DELEGATE_SWIFT = `
// Added by withSceneLifecycle in app.config.ts — iOS 27 requires UIScene lifecycle adoption.
class SceneDelegate: UIResponder, UIWindowSceneDelegate {
  var window: UIWindow?

  func scene(
    _ scene: UIScene,
    willConnectTo session: UISceneSession,
    options connectionOptions: UIScene.ConnectionOptions
  ) {
    guard
      let windowScene = scene as? UIWindowScene,
      let appDelegate = UIApplication.shared.delegate as? AppDelegate,
      let factory = appDelegate.reactNativeFactory
    else { return }

    let window = UIWindow(windowScene: windowScene)
    self.window = window
    appDelegate.window = window

    // Rebuild the launch options React Native reads for Linking.getInitialURL().
    var launchOptions: [UIApplication.LaunchOptionsKey: Any] = [:]
    if let url = connectionOptions.urlContexts.first?.url {
      launchOptions[.url] = url
    }
    if let activity = connectionOptions.userActivities.first(where: {
      $0.activityType == NSUserActivityTypeBrowsingWeb
    }) {
      launchOptions[.userActivityDictionary] = [
        UIApplication.LaunchOptionsKey.userActivityType.rawValue: activity.activityType,
        "UIApplicationLaunchOptionsUserActivityKey": activity,
      ]
    }

    factory.startReactNative(withModuleName: "main", in: window, launchOptions: launchOptions)
  }

  func scene(_ scene: UIScene, openURLContexts URLContexts: Set<UIOpenURLContext>) {
    for context in URLContexts {
      _ = RCTLinkingManager.application(UIApplication.shared, open: context.url, options: [:])
    }
  }

  func scene(_ scene: UIScene, continue userActivity: NSUserActivity) {
    _ = RCTLinkingManager.application(
      UIApplication.shared, continue: userActivity, restorationHandler: { _ in })
  }
}
`;

const withSceneLifecycle: ConfigPlugin = (config) =>
  withAppDelegate(
    withInfoPlist(config, (modConfig) => {
      modConfig.modResults.UIApplicationSceneManifest = {
        UIApplicationSupportsMultipleScenes: false,
        UISceneConfigurations: {
          UIWindowSceneSessionRoleApplication: [
            {
              UISceneConfigurationName: 'Default Configuration',
              UISceneDelegateClassName: '$(PRODUCT_MODULE_NAME).SceneDelegate',
            },
          ],
        },
      };
      return modConfig;
    }),
    (modConfig) => {
      const appDelegate = modConfig.modResults;
      if (appDelegate.language !== 'swift') {
        throw new Error(`Expected a Swift AppDelegate, found ${appDelegate.language}.`);
      }
      // Already rewritten by a previous prebuild into the same directory: nothing to do.
      if (appDelegate.contents.includes('class SceneDelegate')) return modConfig;
      if (!appDelegate.contents.includes(TEMPLATE_WINDOW_START)) {
        throw new Error('Could not find the window setup in ios/PahadPulse/AppDelegate.swift.');
      }

      appDelegate.contents =
        appDelegate.contents.replace(
          TEMPLATE_WINDOW_START,
          '    // The window and React Native start in SceneDelegate (UIScene lifecycle).\n'
        ) + SCENE_DELEGATE_SWIFT;
      return modConfig;
    }
  );

/**
 * Release signing for the locally built Android bundle.
 *
 * The Expo template signs release builds with its bundled DEBUG keystore. Play rejects a
 * debug-signed upload outright, and the mistake is invisible until the Console refuses the
 * file, so the config is rewritten here rather than trusted to a hand edit — `/android` is
 * gitignored and regenerated by every prebuild.
 *
 * The keystore and its passwords are read from Gradle properties, which live in
 * `~/.gradle/gradle.properties`, OUTSIDE this repository. Nothing secret is committed (N8):
 *
 *   PAHADPULSE_UPLOAD_STORE_FILE=/Users/you/keys/pahadpulse-upload.jks
 *   PAHADPULSE_UPLOAD_STORE_PASSWORD=…
 *   PAHADPULSE_UPLOAD_KEY_ALIAS=upload
 *   PAHADPULSE_UPLOAD_KEY_PASSWORD=…
 *
 * With those unset, the release build fails with "Keystore file … not found" naming the
 * sentinel below. That failure is deliberate: a build that cannot be signed properly must
 * stop, never quietly fall back to the debug key.
 */
const RELEASE_SIGNING_CONFIG = `
        release {
            // Sentinel path: if this appears in a build error, the PAHADPULSE_UPLOAD_*
            // properties are missing from ~/.gradle/gradle.properties.
            storeFile file(findProperty('PAHADPULSE_UPLOAD_STORE_FILE') ?: 'UPLOAD_KEYSTORE_NOT_CONFIGURED.jks')
            storePassword findProperty('PAHADPULSE_UPLOAD_STORE_PASSWORD') ?: ''
            keyAlias findProperty('PAHADPULSE_UPLOAD_KEY_ALIAS') ?: ''
            keyPassword findProperty('PAHADPULSE_UPLOAD_KEY_PASSWORD') ?: ''
        }`;

const withAndroidReleaseSigning: ConfigPlugin = (config) =>
  withAppBuildGradle(config, (modConfig) => {
    const gradle = modConfig.modResults;
    if (gradle.language !== 'groovy') {
      throw new Error(`Expected a Groovy build.gradle, found ${gradle.language}.`);
    }

    const debugSigningBlock = `            keyPassword 'android'
        }`;
    const releaseUsesDebugKey = `        release {
            // Caution! In production, you need to generate your own keystore file.
            // see https://reactnative.dev/docs/signed-apk-android.
            signingConfig signingConfigs.debug`;

    /*
     * Both anchors are asserted rather than replaced best-effort. If a future Expo template
     * rewrites this file, the build must fail here — loudly, at prebuild — instead of
     * producing an unsigned or debug-signed bundle that is only rejected at upload.
     */
    if (!gradle.contents.includes(debugSigningBlock)) {
      throw new Error('Could not find the debug signingConfig in android/app/build.gradle.');
    }
    if (!gradle.contents.includes(releaseUsesDebugKey)) {
      // Already rewritten by a previous prebuild into the same directory: nothing to do.
      if (gradle.contents.includes('PAHADPULSE_UPLOAD_STORE_FILE')) return modConfig;
      throw new Error('Could not find the release buildType in android/app/build.gradle.');
    }

    gradle.contents = gradle.contents
      .replace(debugSigningBlock, `${debugSigningBlock}${RELEASE_SIGNING_CONFIG}`)
      .replace(
        releaseUsesDebugKey,
        `        release {
            signingConfig signingConfigs.release`
      );

    return modConfig;
  });

export default ({ config }: ConfigContext): ExpoConfig =>
  withAndroidReleaseSigning(
    withBundleEnvironment(
      withVendoredDsyms(
        withDevelopmentTeam(
          withSceneLifecycle(
            withScriptSandboxingDisabled({
              ...config,
              name: NAME[VARIANT],
              slug: 'pahad-pulse',
              version: '1.0.0',
              orientation: 'default',
              icon: './assets/images/icon.png',
              scheme: 'pahadpulse',
              userInterfaceStyle: 'automatic',
              /**
               * Over-the-air updates are keyed to the runtime version. Tying it to `appVersion` means a
               * JS-only fix ships to everyone on the same store build, while any change that touches
               * native code requires a new store release rather than silently mismatching.
               */
              runtimeVersion: { policy: 'appVersion' },
              ios: {
                // iPhone only for v1: iPad would need its own QA pass and screenshot set before review.
                supportsTablet: false,
                bundleIdentifier: `${BASE_BUNDLE_ID}${BUNDLE_SUFFIX[VARIANT]}`,
                // Read by EAS, and by `withDevelopmentTeam` below for the local archive. Public: it
                // is printed in every crash report and on the App Store listing.
                appleTeamId: APPLE_TEAM_ID,
                /**
                 * Both store builds are produced locally — an Xcode archive and a Gradle bundle — so
                 * these two numbers are the real ones, not a starting point EAS would override.
                 * Increment on every upload: App Store Connect and Play each reject a repeat.
                 */
                buildNumber: '4',
                infoPlist: { ITSAppUsesNonExemptEncryption: false },
                /*
                 * Push, declared here rather than clicked into Xcode.
                 *
                 * 1.0.0 (2) failed to archive with "entitlements file was modified during the
                 * build": the App ID had Push Notifications enabled while the app shipped no
                 * push code, so automatic signing rewrote the empty entitlements mid-archive.
                 * The app now registers for alert notifications, so the entitlement is real —
                 * and it belongs in this file, because `/ios` is prebuild output and anything
                 * set in the Xcode UI is destroyed by the next prebuild.
                 *
                 * `production` is what an App Store or TestFlight build needs; a debug build
                 * run from Xcode gets `development` from the automatic signing flow.
                 */
                entitlements: { 'aps-environment': 'production' },
              },
              android: {
                package: `${BASE_BUNDLE_ID}${BUNDLE_SUFFIX[VARIANT]}`,
                /**
                 * Raise this by one for EVERY .aab uploaded to Play, including one that is only ever
                 * used for internal testing. Play rejects a reused versionCode outright — AgniVision
                 * hit exactly this and had to rebuild. `versionName` comes from `version` above.
                 */
                versionCode: 2,
                predictiveBackGestureEnabled: false,
                adaptiveIcon: {
                  backgroundColor: '#F2F7F7',
                  foregroundImage: './assets/images/android-icon-foreground.png',
                  monochromeImage: './assets/images/android-icon-monochrome.png',
                },
                /**
                 * Permissions the app does not use, removed from the merged manifest.
                 *
                 * The Expo template requests "display over other apps" and legacy storage access by
                 * default. Neither is used here, and Play review asks for a justification of each — a
                 * read-only data app declaring them invites a delayed or rejected review. INTERNET and
                 * VIBRATE (haptics) stay.
                 */
                blockedPermissions: [
                  'android.permission.ACCESS_COARSE_LOCATION',
                  'android.permission.ACCESS_FINE_LOCATION',
                  'android.permission.SYSTEM_ALERT_WINDOW',
                  'android.permission.READ_EXTERNAL_STORAGE',
                  'android.permission.WRITE_EXTERNAL_STORAGE',
                ],
              },
              web: {
                output: 'static',
                favicon: './assets/images/favicon.png',
              },
              plugins: [
                'expo-router',
                'expo-secure-store',
                'expo-localization',
                [
                  'expo-splash-screen',
                  {
                    backgroundColor: '#F2F7F7',
                    dark: { backgroundColor: '#071719' },
                    image: './assets/images/splash-icon.png',
                    imageWidth: 180,
                  },
                ],
              ],
              experiments: {
                typedRoutes: true,
                reactCompiler: true,
              },
              extra: {
                variant: VARIANT,
                brandColor: BRAND_BLUE,
                router: {},
                /**
                 * The `eas` key is OMITTED entirely until a project ID exists, rather than set to null.
                 *
                 * Expo's config serialisation turns a null here into `{}`, which is truthy — so the dev
                 * server treats it as a real project ID, tries to sign the Expo Go manifest with it, and
                 * fails with "The path argument must be of type string". An absent key takes the
                 * unconfigured branch instead, which is what a fresh clone without EAS should do.
                 *
                 * `eas init` writes the real value; once it exists this passes it through.
                 */
                ...(process.env.EAS_PROJECT_ID
                  ? { eas: { projectId: process.env.EAS_PROJECT_ID } }
                  : null),
              },
            })
          )
        )
      )
    )
  );
