import type { ConfigContext, ExpoConfig } from 'expo/config';
import { withAppBuildGradle, withXcodeProject, type ConfigPlugin } from 'expo/config-plugins';

/**
 * Expo config as TypeScript so one codebase can produce three apps.
 *
 * `APP_VARIANT` selects the environment at build time. Bundle identifiers differ per variant
 * on purpose: development, preview and production installs must be able to coexist on one
 * device, or testers end up overwriting the build they were asked to verify.
 */
type Variant = 'development' | 'preview' | 'production';

const VARIANT = (process.env.APP_VARIANT as Variant | undefined) ?? 'development';

const NAME: Record<Variant, string> = {
  development: 'Pahad Pulse (Dev)',
  preview: 'Pahad Pulse (Preview)',
  production: 'Pahad Pulse',
};

const BUNDLE_SUFFIX: Record<Variant, string> = {
  development: '.dev',
  preview: '.preview',
  production: '',
};

const BASE_BUNDLE_ID = 'in.pahadpulse.app';

/** Accessible interface blue derived from the logo. Keep in step with `src/theme/tokens.ts`. */
const BRAND_BLUE = '#075E9C';

/**
 * A production binary must never silently inherit the localhost development defaults from
 * `src/config/env.ts`. EAS evaluates this file before bundling, so failing here prevents a
 * store build whose every request would be sent to the reader's own phone.
 */
function assertProductionUrl(name: string, value: string | undefined): void {
  if (VARIANT !== 'production') return;

  if (!value) {
    throw new Error(`${name} must be set in the EAS production environment.`);
  }

  const url = new URL(value);
  if (url.protocol !== 'https:' || ['localhost', '127.0.0.1', '::1'].includes(url.hostname)) {
    throw new Error(`${name} must be a public HTTPS URL for production builds.`);
  }
}

/**
 * The Expo SDK 57 prebuild template sets `ENABLE_USER_SCRIPT_SANDBOXING = YES`, but the
 * "Bundle React Native code and images" phase declares no output paths. A sandboxed phase may
 * only write declared outputs, so a Release archive bundles the JS and is then denied writing
 * `main.jsbundle` (EPERM). Debug skips bundling, which is why only archives fail.
 *
 * `/ios` is gitignored and regenerated by prebuild, so the override has to live here rather
 * than in the Xcode project. See `IOS_ARCHIVE_FIX_HANDOFF.md`.
 */
const withScriptSandboxingDisabled: ConfigPlugin = (config) =>
  withXcodeProject(config, (modConfig) => {
    const configurations: Record<string, unknown> =
      modConfig.modResults.pbxXCBuildConfigurationSection();

    for (const entry of Object.values(configurations)) {
      // The section also holds `<id>_comment` string entries alongside the real configurations.
      if (typeof entry !== 'object' || entry === null || !('buildSettings' in entry)) continue;
      const { buildSettings } = entry as { buildSettings: Record<string, unknown> };
      buildSettings.ENABLE_USER_SCRIPT_SANDBOXING = 'NO';
    }

    return modConfig;
  });

/**
 * Release signing for the locally built Android bundle.
 *
 * The Expo template signs release builds with its bundled DEBUG keystore. Play rejects a
 * debug-signed upload outright, and the mistake is invisible until the Console refuses the
 * file, so the config is rewritten here rather than trusted to a hand edit — `/android` is
 * gitignored and regenerated by every prebuild.
 *
 * The keystore and its passwords are read from Gradle properties, which live in
 * `~/.gradle/gradle.properties`, OUTSIDE this repository. Nothing secret is committed (N8):
 *
 *   PAHADPULSE_UPLOAD_STORE_FILE=/Users/you/keys/pahadpulse-upload.jks
 *   PAHADPULSE_UPLOAD_STORE_PASSWORD=…
 *   PAHADPULSE_UPLOAD_KEY_ALIAS=upload
 *   PAHADPULSE_UPLOAD_KEY_PASSWORD=…
 *
 * With those unset, the release build fails with "Keystore file … not found" naming the
 * sentinel below. That failure is deliberate: a build that cannot be signed properly must
 * stop, never quietly fall back to the debug key.
 */
const RELEASE_SIGNING_CONFIG = `
        release {
            // Sentinel path: if this appears in a build error, the PAHADPULSE_UPLOAD_*
            // properties are missing from ~/.gradle/gradle.properties.
            storeFile file(findProperty('PAHADPULSE_UPLOAD_STORE_FILE') ?: 'UPLOAD_KEYSTORE_NOT_CONFIGURED.jks')
            storePassword findProperty('PAHADPULSE_UPLOAD_STORE_PASSWORD') ?: ''
            keyAlias findProperty('PAHADPULSE_UPLOAD_KEY_ALIAS') ?: ''
            keyPassword findProperty('PAHADPULSE_UPLOAD_KEY_PASSWORD') ?: ''
        }`;

const withAndroidReleaseSigning: ConfigPlugin = (config) =>
  withAppBuildGradle(config, (modConfig) => {
    const gradle = modConfig.modResults;
    if (gradle.language !== 'groovy') {
      throw new Error(`Expected a Groovy build.gradle, found ${gradle.language}.`);
    }

    const debugSigningBlock = `            keyPassword 'android'
        }`;
    const releaseUsesDebugKey = `        release {
            // Caution! In production, you need to generate your own keystore file.
            // see https://reactnative.dev/docs/signed-apk-android.
            signingConfig signingConfigs.debug`;

    /*
     * Both anchors are asserted rather than replaced best-effort. If a future Expo template
     * rewrites this file, the build must fail here — loudly, at prebuild — instead of
     * producing an unsigned or debug-signed bundle that is only rejected at upload.
     */
    if (!gradle.contents.includes(debugSigningBlock)) {
      throw new Error('Could not find the debug signingConfig in android/app/build.gradle.');
    }
    if (!gradle.contents.includes(releaseUsesDebugKey)) {
      // Already rewritten by a previous prebuild into the same directory: nothing to do.
      if (gradle.contents.includes('PAHADPULSE_UPLOAD_STORE_FILE')) return modConfig;
      throw new Error('Could not find the release buildType in android/app/build.gradle.');
    }

    gradle.contents = gradle.contents
      .replace(debugSigningBlock, `${debugSigningBlock}${RELEASE_SIGNING_CONFIG}`)
      .replace(
        releaseUsesDebugKey,
        `        release {
            signingConfig signingConfigs.release`
      );

    return modConfig;
  });

assertProductionUrl('EXPO_PUBLIC_API_URL', process.env.EXPO_PUBLIC_API_URL);
assertProductionUrl('EXPO_PUBLIC_WEB_URL', process.env.EXPO_PUBLIC_WEB_URL);

export default ({ config }: ConfigContext): ExpoConfig =>
  withAndroidReleaseSigning(
    withScriptSandboxingDisabled({
      ...config,
      name: NAME[VARIANT],
      slug: 'pahad-pulse',
      version: '1.0.0',
      orientation: 'default',
      icon: './assets/images/icon.png',
      scheme: 'pahadpulse',
      userInterfaceStyle: 'automatic',
      /**
       * Over-the-air updates are keyed to the runtime version. Tying it to `appVersion` means a
       * JS-only fix ships to everyone on the same store build, while any change that touches
       * native code requires a new store release rather than silently mismatching.
       */
      runtimeVersion: { policy: 'appVersion' },
      ios: {
        // iPhone only for v1: iPad would need its own QA pass and screenshot set before review.
        supportsTablet: false,
        bundleIdentifier: `${BASE_BUNDLE_ID}${BUNDLE_SUFFIX[VARIANT]}`,
        /**
         * Both store builds are produced locally — an Xcode archive and a Gradle bundle — so
         * these two numbers are the real ones, not a starting point EAS would override.
         * Increment on every upload: App Store Connect and Play each reject a repeat.
         */
        buildNumber: '1',
        infoPlist: { ITSAppUsesNonExemptEncryption: false },
      },
      android: {
        package: `${BASE_BUNDLE_ID}${BUNDLE_SUFFIX[VARIANT]}`,
        /**
         * Raise this by one for EVERY .aab uploaded to Play, including one that is only ever
         * used for internal testing. Play rejects a reused versionCode outright — AgniVision
         * hit exactly this and had to rebuild. `versionName` comes from `version` above.
         */
        versionCode: 1,
        predictiveBackGestureEnabled: false,
        adaptiveIcon: {
          backgroundColor: '#F2F7F7',
          foregroundImage: './assets/images/android-icon-foreground.png',
          monochromeImage: './assets/images/android-icon-monochrome.png',
        },
        /**
         * Permissions the app does not use, removed from the merged manifest.
         *
         * The Expo template requests "display over other apps" and legacy storage access by
         * default. Neither is used here, and Play review asks for a justification of each — a
         * read-only data app declaring them invites a delayed or rejected review. INTERNET and
         * VIBRATE (haptics) stay.
         */
        blockedPermissions: [
          'android.permission.ACCESS_COARSE_LOCATION',
          'android.permission.ACCESS_FINE_LOCATION',
          'android.permission.SYSTEM_ALERT_WINDOW',
          'android.permission.READ_EXTERNAL_STORAGE',
          'android.permission.WRITE_EXTERNAL_STORAGE',
        ],
      },
      web: {
        output: 'static',
        favicon: './assets/images/favicon.png',
      },
      plugins: [
        'expo-router',
        'expo-secure-store',
        'expo-localization',
        [
          'expo-splash-screen',
          {
            backgroundColor: '#F2F7F7',
            dark: { backgroundColor: '#071719' },
            image: './assets/images/splash-icon.png',
            imageWidth: 180,
          },
        ],
      ],
      experiments: {
        typedRoutes: true,
        reactCompiler: true,
      },
      extra: {
        variant: VARIANT,
        brandColor: BRAND_BLUE,
        router: {},
        /**
         * The `eas` key is OMITTED entirely until a project ID exists, rather than set to null.
         *
         * Expo's config serialisation turns a null here into `{}`, which is truthy — so the dev
         * server treats it as a real project ID, tries to sign the Expo Go manifest with it, and
         * fails with "The path argument must be of type string". An absent key takes the
         * unconfigured branch instead, which is what a fresh clone without EAS should do.
         *
         * `eas init` writes the real value; once it exists this passes it through.
         */
        ...(process.env.EAS_PROJECT_ID
          ? { eas: { projectId: process.env.EAS_PROJECT_ID } }
          : null),
      },
    })
  );
