-- 039 — the migration surveys, their answer options, and every district figure in both rounds.
--
-- SOURCE.
--
-- The Rural Development and Migration Commission (Palayan Ayog), Pauri Garhwal, surveyed
-- every gram panchayat in the state twice. Its reports are PDFs, so this is a `manual`
-- source in the same sense as the transcribed reservoir figures (HYD-7): a human read the
-- tables and typed them, and the row records which document and which round.
--
-- HOW THESE NUMBERS WERE CHECKED.
--
-- Every district figure below appears in TWO independently typeset reports — the 2018
-- English report, and the 2023 report which reprints the 2018 round beside its own. All four
-- headline counts reconcile across both, and the per-district columns sum to the state
-- totals the reports state for themselves (383,726 and 118,981 for 2018; 307,310 and 28,531
-- for 2022). The share dimensions each sum to 100.00 per district, and the village condition
-- counts sum to the stated state totals (734 emptied, 482 of them without a road, and so on).
--
-- ONE DISCREPANCY, RECORDED RATHER THAN RESOLVED.
--
-- The 2023 report's prose says 28,631 people migrated permanently between 2018 and 2022; its
-- own tables say 28,531, and those columns add up. The table figure is used here. The prose
-- figure is noted so that a reader who finds it in the PDF is not left thinking this is wrong.

INSERT INTO sources
  (source_key, owner_module, department_en, department_hi, url, attribution, licence,
   access_method, cadence, may_redistribute, metadata_status, metadata_note, is_enabled)
VALUES
  (
    'uk-migration-commission',
    'migration',
    'Rural Development and Migration Commission, Uttarakhand',
    'ग्राम्य विकास एवं पलायन निवारण आयोग, उत्तराखण्ड',
    'https://palayanayog.uk.gov.in',
    'Rural Development and Migration Commission (Palayan Ayog), Uttarakhand, Pauri Garhwal',
    'Government of Uttarakhand report, reproduced with attribution.',
    'manual',
    'static',
    TRUE,
    'provisional',
    'Transcribed by hand from the commission''s published PDF reports; there is no feed. Two rounds so far: an interim report of April 2018 covering 2008-2018, and a second interim report of February 2023 covering 2018 to September 2022. Figures were cross-checked against both documents and against the state totals each report states for itself. The 2023 report''s prose gives permanent migration as 28,631 where its tables give 28,531; the table figure is stored.',
    TRUE
  )
ON CONFLICT (source_key) DO UPDATE SET
  owner_module     = EXCLUDED.owner_module,
  department_en    = EXCLUDED.department_en,
  department_hi    = EXCLUDED.department_hi,
  url              = EXCLUDED.url,
  attribution      = EXCLUDED.attribution,
  licence          = EXCLUDED.licence,
  access_method    = EXCLUDED.access_method,
  cadence          = EXCLUDED.cadence,
  may_redistribute = EXCLUDED.may_redistribute,
  metadata_status  = EXCLUDED.metadata_status,
  metadata_note    = EXCLUDED.metadata_note,
  is_enabled       = EXCLUDED.is_enabled;

INSERT INTO migration_surveys
  (survey_key, label_en, label_hi, covers_from, covers_to, published_on,
   gram_panchayats_surveyed, blocks_surveyed, source_id, evidence_url)
VALUES
  ('round-2018',
   'First interim report, April 2018',
   'प्रथम अंतरिम रिपोर्ट, अप्रैल 2018',
   '2008-01-01', '2018-02-28', '2018-04-01',
   NULL, NULL,
   (SELECT id FROM sources WHERE source_key = 'uk-migration-commission'),
   'https://palayanayog.uk.gov.in'),
  ('round-2022',
   'Second interim report, February 2023',
   'द्वितीय अंतरिम रिपोर्ट, फरवरी 2023',
   '2018-03-01', '2022-09-30', '2023-02-01',
   7759, 95,
   (SELECT id FROM sources WHERE source_key = 'uk-migration-commission'),
   'https://palayanayog.uk.gov.in')
ON CONFLICT (survey_key) DO UPDATE SET
  label_en                 = EXCLUDED.label_en,
  label_hi                 = EXCLUDED.label_hi,
  covers_from              = EXCLUDED.covers_from,
  covers_to                = EXCLUDED.covers_to,
  published_on             = EXCLUDED.published_on,
  gram_panchayats_surveyed = EXCLUDED.gram_panchayats_surveyed,
  blocks_surveyed          = EXCLUDED.blocks_surveyed,
  source_id                = EXCLUDED.source_id,
  evidence_url             = EXCLUDED.evidence_url;

INSERT INTO migration_categories (category_key, dimension, label_en, label_hi, sort_order, note_en)
VALUES
  ('livelihood', 'reason', 'Livelihood or employment', 'आजीविका / रोज़गार की समस्या', 1, NULL),
  ('healthcare', 'reason', 'Lack of healthcare', 'चिकित्सा सुविधा का अभाव', 2, NULL),
  ('education', 'reason', 'Lack of education', 'शिक्षा सुविधा का अभाव', 3, NULL),
  ('infrastructure', 'reason', 'Lack of infrastructure', 'इंफ्रास्ट्रक्चर (सड़क, बिजली, पानी) का अभाव', 4, 'Roads, electricity, drinking water and similar basic services.'),
  ('farm_productivity', 'reason', 'Low farm productivity', 'कृषि भूमि में उत्पादकता / पैदावार की कमी', 5, NULL),
  ('family_influence', 'reason', 'Following family or relatives', 'परिवार / सगे-संबंधियों की देखा-देखी पलायन', 6, NULL),
  ('wildlife_damage', 'reason', 'Crop loss to wild animals', 'जंगली जानवरों द्वारा कृषि को हानि', 7, NULL),
  ('reason_other', 'reason', 'Other reasons', 'अन्य कोई विशेष कारण', 8, NULL),
  ('age_under_25', 'age', 'Under 25', '25 साल से कम आयु वर्ग', 1, NULL),
  ('age_26_to_35', 'age', '26 to 35', '26 से 35 आयु वर्ग', 2, NULL),
  ('age_over_35', 'age', 'Over 35', '35 साल से अधिक आयु वर्ग', 3, NULL),
  ('nearby_towns', 'destination', 'Nearby towns', 'नजदीकी कस्बों में', 1, NULL),
  ('district_hq', 'destination', 'District headquarters', 'जनपद मुख्यालय', 2, NULL),
  ('other_district_in_state', 'destination', 'Another district in the state', 'राज्य के अन्य जनपदों में', 3, NULL),
  ('outside_state', 'destination', 'Outside Uttarakhand', 'राज्य से बाहर', 4, NULL),
  ('outside_country', 'destination', 'Outside India', 'देश से बाहर', 5, NULL),
  ('labour', 'occupation', 'Wage labour', 'मजदूरी', 1, '2018 round only. Not comparable with the 2022 categories.'),
  ('agriculture', 'occupation', 'Agriculture', 'कृषि', 2, '2018 round only.'),
  ('horticulture', 'occupation', 'Horticulture', 'उद्यान', 3, '2018 round only.'),
  ('dairy', 'occupation', 'Dairy', 'डेरी', 4, '2018 round only.'),
  ('government_service', 'occupation', 'Government service', 'सरकारी सेवा', 5, '2018 round only.'),
  ('other_work', 'occupation', 'Other work', 'अन्य कार्य', 6, '2018 round only.'),
  ('agri_horti_livestock', 'occupation', 'Agriculture, horticulture and livestock', 'कृषि / बागवानी / पशुपालन', 11, '2022 round only. Merges three options the 2018 round asked separately.'),
  ('mgnrega', 'occupation', 'MGNREGA', 'मनरेगा', 12, '2022 round only. Was not an option in 2018.'),
  ('government_service_2022', 'occupation', 'Government job', 'सरकारी नौकरी', 13, '2022 round only.'),
  ('self_employment_other', 'occupation', 'Self-employment and other', 'स्वरोजगार एवं अन्य', 14, '2022 round only. Was not an option in 2018.'),
  ('labour_2022', 'occupation', 'Wage labour', 'मजदूरी', 15, '2022 round only.'),
  ('depopulated_after_2011', 'village_condition', 'Emptied since 2011', '2011 के बाद निर्जन हुए गाँव', 1, 'Revenue villages, toks and majras with no remaining population.'),
  ('depopulated_no_road', 'village_condition', 'Emptied, and had no road', 'निर्जन, सड़क से न जुड़े', 2, 'Subset of the emptied villages.'),
  ('depopulated_no_power', 'village_condition', 'Emptied, and had no electricity', 'निर्जन, बिजली रहित', 3, 'Subset of the emptied villages.'),
  ('depopulated_no_water', 'village_condition', 'Emptied, and had no water within 1 km', 'निर्जन, 1 किमी में पेयजल नहीं', 4, 'Subset of the emptied villages.'),
  ('depopulated_no_phc', 'village_condition', 'Emptied, and had no health centre', 'निर्जन, प्राथमिक स्वास्थ्य केंद्र नहीं', 5, 'Subset of the emptied villages.'),
  ('depopulated_near_border', 'village_condition', 'Emptied, within 5 km of the border', 'निर्जन, अंतर्राष्ट्रीय सीमा से 5 किमी के भीतर', 6, 'Subset of the emptied villages. Only border districts can have these.'),
  ('declined_over_half', 'village_condition', 'Lost over half their people', 'आधी से अधिक जनसंख्या घटी', 11, 'Still inhabited, but population fell by more than 50% between 2011 and 2018.'),
  ('declined_no_road', 'village_condition', 'Halved, and has no road', 'आधी घटी, सड़क से न जुड़े', 12, 'Subset of the halved villages.'),
  ('declined_no_power', 'village_condition', 'Halved, and has no electricity', 'आधी घटी, बिजली रहित', 13, 'Subset of the halved villages.'),
  ('declined_no_water', 'village_condition', 'Halved, and has no water within 1 km', 'आधी घटी, 1 किमी में पेयजल नहीं', 14, 'Subset of the halved villages.'),
  ('declined_no_phc', 'village_condition', 'Halved, and has no health centre', 'आधी घटी, स्वास्थ्य केंद्र नहीं', 15, 'Subset of the halved villages.'),
  ('declined_near_border', 'village_condition', 'Halved, within 5 km of the border', 'आधी घटी, सीमा से 5 किमी के भीतर', 16, 'Subset of the halved villages.'),
  ('inward_migration', 'village_condition', 'Villages people moved into', 'जहाँ लोग आकर बसे', 21, 'Villages where families from outside settled during the same period.')
ON CONFLICT (category_key) DO UPDATE SET
  dimension  = EXCLUDED.dimension,
  label_en   = EXCLUDED.label_en,
  label_hi   = EXCLUDED.label_hi,
  sort_order = EXCLUDED.sort_order,
  note_en    = EXCLUDED.note_en;


INSERT INTO migration_district_figures
  (survey_id, area_id, temporary_persons, temporary_panchayats,
   permanent_persons, permanent_panchayats, blocks_reporting)
VALUES
  ((SELECT id FROM migration_surveys WHERE survey_key = 'round-2018'), (SELECT id FROM areas WHERE type = 'district' AND slug = 'almora'), 53611, 1022, 16207, 646, NULL),
  ((SELECT id FROM migration_surveys WHERE survey_key = 'round-2018'), (SELECT id FROM areas WHERE type = 'district' AND slug = 'bageshwar'), 23388, 346, 5912, 195, NULL),
  ((SELECT id FROM migration_surveys WHERE survey_key = 'round-2018'), (SELECT id FROM areas WHERE type = 'district' AND slug = 'chamoli'), 32020, 556, 14289, 373, NULL),
  ((SELECT id FROM migration_surveys WHERE survey_key = 'round-2018'), (SELECT id FROM areas WHERE type = 'district' AND slug = 'champawat'), 20332, 304, 7886, 208, NULL),
  ((SELECT id FROM migration_surveys WHERE survey_key = 'round-2018'), (SELECT id FROM areas WHERE type = 'district' AND slug = 'dehradun'), 25781, 231, 2802, 53, NULL),
  ((SELECT id FROM migration_surveys WHERE survey_key = 'round-2018'), (SELECT id FROM areas WHERE type = 'district' AND slug = 'haridwar'), 8168, 153, 1251, 73, NULL),
  ((SELECT id FROM migration_surveys WHERE survey_key = 'round-2018'), (SELECT id FROM areas WHERE type = 'district' AND slug = 'nainital'), 20951, 339, 4823, 213, NULL),
  ((SELECT id FROM migration_surveys WHERE survey_key = 'round-2018'), (SELECT id FROM areas WHERE type = 'district' AND slug = 'pauri-garhwal'), 47488, 1025, 25584, 821, NULL),
  ((SELECT id FROM migration_surveys WHERE survey_key = 'round-2018'), (SELECT id FROM areas WHERE type = 'district' AND slug = 'pithoragarh'), 31786, 589, 9883, 384, NULL),
  ((SELECT id FROM migration_surveys WHERE survey_key = 'round-2018'), (SELECT id FROM areas WHERE type = 'district' AND slug = 'rudraprayag'), 22735, 316, 7835, 230, NULL),
  ((SELECT id FROM migration_surveys WHERE survey_key = 'round-2018'), (SELECT id FROM areas WHERE type = 'district' AND slug = 'tehri-garhwal'), 71509, 934, 18830, 585, NULL),
  ((SELECT id FROM migration_surveys WHERE survey_key = 'round-2018'), (SELECT id FROM areas WHERE type = 'district' AND slug = 'udham-singh-nagar'), 6064, 147, 952, 54, NULL),
  ((SELECT id FROM migration_surveys WHERE survey_key = 'round-2018'), (SELECT id FROM areas WHERE type = 'district' AND slug = 'uttarkashi'), 19893, 376, 2727, 111, NULL),
  ((SELECT id FROM migration_surveys WHERE survey_key = 'round-2022'), (SELECT id FROM areas WHERE type = 'district' AND slug = 'almora'), 54519, 1090, 5926, 407, 11),
  ((SELECT id FROM migration_surveys WHERE survey_key = 'round-2022'), (SELECT id FROM areas WHERE type = 'district' AND slug = 'bageshwar'), 14503, 380, 1403, 93, 3),
  ((SELECT id FROM migration_surveys WHERE survey_key = 'round-2022'), (SELECT id FROM areas WHERE type = 'district' AND slug = 'chamoli'), 16326, 478, 1722, 151, 9),
  ((SELECT id FROM migration_surveys WHERE survey_key = 'round-2022'), (SELECT id FROM areas WHERE type = 'district' AND slug = 'champawat'), 13711, 263, 1588, 90, 4),
  ((SELECT id FROM migration_surveys WHERE survey_key = 'round-2022'), (SELECT id FROM areas WHERE type = 'district' AND slug = 'dehradun'), 9309, 220, 312, 7, 6),
  ((SELECT id FROM migration_surveys WHERE survey_key = 'round-2022'), (SELECT id FROM areas WHERE type = 'district' AND slug = 'haridwar'), 28087, 179, 1029, 26, 4),
  ((SELECT id FROM migration_surveys WHERE survey_key = 'round-2022'), (SELECT id FROM areas WHERE type = 'district' AND slug = 'nainital'), 20863, 410, 2014, 152, 8),
  ((SELECT id FROM migration_surveys WHERE survey_key = 'round-2022'), (SELECT id FROM areas WHERE type = 'district' AND slug = 'pauri-garhwal'), 29093, 1057, 5474, 467, 15),
  ((SELECT id FROM migration_surveys WHERE survey_key = 'round-2022'), (SELECT id FROM areas WHERE type = 'district' AND slug = 'pithoragarh'), 25715, 585, 1713, 173, 8),
  ((SELECT id FROM migration_surveys WHERE survey_key = 'round-2022'), (SELECT id FROM areas WHERE type = 'district' AND slug = 'rudraprayag'), 14593, 300, 715, 71, 3),
  ((SELECT id FROM migration_surveys WHERE survey_key = 'round-2022'), (SELECT id FROM areas WHERE type = 'district' AND slug = 'tehri-garhwal'), 41359, 906, 5653, 350, 9),
  ((SELECT id FROM migration_surveys WHERE survey_key = 'round-2022'), (SELECT id FROM areas WHERE type = 'district' AND slug = 'udham-singh-nagar'), 19583, 191, 82, 2, 6),
  ((SELECT id FROM migration_surveys WHERE survey_key = 'round-2022'), (SELECT id FROM areas WHERE type = 'district' AND slug = 'uttarkashi'), 19649, 377, 900, 78, 6)
ON CONFLICT (survey_id, area_id) DO UPDATE SET
  temporary_persons    = EXCLUDED.temporary_persons,
  temporary_panchayats = EXCLUDED.temporary_panchayats,
  permanent_persons    = EXCLUDED.permanent_persons,
  permanent_panchayats = EXCLUDED.permanent_panchayats,
  blocks_reporting     = EXCLUDED.blocks_reporting;


INSERT INTO migration_observations (survey_id, area_id, category_key, value)
VALUES
  ((SELECT id FROM migration_surveys WHERE survey_key = 'round-2018'), (SELECT id FROM areas WHERE type = 'district' AND slug = 'almora'), 'age_26_to_35', 42.22),
  ((SELECT id FROM migration_surveys WHERE survey_key = 'round-2018'), (SELECT id FROM areas WHERE type = 'district' AND slug = 'almora'), 'agriculture', 39.35),
  ((SELECT id FROM migration_surveys WHERE survey_key = 'round-2018'), (SELECT id FROM areas WHERE type = 'district' AND slug = 'almora'), 'dairy', 3.66),
  ((SELECT id FROM migration_surveys WHERE survey_key = 'round-2018'), (SELECT id FROM areas WHERE type = 'district' AND slug = 'almora'), 'district_hq', 13.00),
  ((SELECT id FROM migration_surveys WHERE survey_key = 'round-2018'), (SELECT id FROM areas WHERE type = 'district' AND slug = 'almora'), 'education', 11.75),
  ((SELECT id FROM migration_surveys WHERE survey_key = 'round-2018'), (SELECT id FROM areas WHERE type = 'district' AND slug = 'almora'), 'family_influence', 2.68),
  ((SELECT id FROM migration_surveys WHERE survey_key = 'round-2018'), (SELECT id FROM areas WHERE type = 'district' AND slug = 'almora'), 'farm_productivity', 8.37),
  ((SELECT id FROM migration_surveys WHERE survey_key = 'round-2018'), (SELECT id FROM areas WHERE type = 'district' AND slug = 'almora'), 'government_service', 10.86),
  ((SELECT id FROM migration_surveys WHERE survey_key = 'round-2018'), (SELECT id FROM areas WHERE type = 'district' AND slug = 'almora'), 'healthcare', 8.61),
  ((SELECT id FROM migration_surveys WHERE survey_key = 'round-2018'), (SELECT id FROM areas WHERE type = 'district' AND slug = 'almora'), 'horticulture', 1.51),
  ((SELECT id FROM migration_surveys WHERE survey_key = 'round-2018'), (SELECT id FROM areas WHERE type = 'district' AND slug = 'almora'), 'infrastructure', 3.81),
  ((SELECT id FROM migration_surveys WHERE survey_key = 'round-2018'), (SELECT id FROM areas WHERE type = 'district' AND slug = 'almora'), 'labour', 34.13),
  ((SELECT id FROM migration_surveys WHERE survey_key = 'round-2018'), (SELECT id FROM areas WHERE type = 'district' AND slug = 'almora'), 'livelihood', 47.78),
  ((SELECT id FROM migration_surveys WHERE survey_key = 'round-2018'), (SELECT id FROM areas WHERE type = 'district' AND slug = 'almora'), 'nearby_towns', 7.13),
  ((SELECT id FROM migration_surveys WHERE survey_key = 'round-2018'), (SELECT id FROM areas WHERE type = 'district' AND slug = 'almora'), 'reason_other', 6.02),
  ((SELECT id FROM migration_surveys WHERE survey_key = 'round-2018'), (SELECT id FROM areas WHERE type = 'district' AND slug = 'almora'), 'other_district_in_state', 32.37),
  ((SELECT id FROM migration_surveys WHERE survey_key = 'round-2018'), (SELECT id FROM areas WHERE type = 'district' AND slug = 'almora'), 'other_work', 10.50),
  ((SELECT id FROM migration_surveys WHERE survey_key = 'round-2018'), (SELECT id FROM areas WHERE type = 'district' AND slug = 'almora'), 'outside_country', 0.43),
  ((SELECT id FROM migration_surveys WHERE survey_key = 'round-2018'), (SELECT id FROM areas WHERE type = 'district' AND slug = 'almora'), 'outside_state', 47.08),
  ((SELECT id FROM migration_surveys WHERE survey_key = 'round-2018'), (SELECT id FROM areas WHERE type = 'district' AND slug = 'almora'), 'age_over_35', 28.59),
  ((SELECT id FROM migration_surveys WHERE survey_key = 'round-2018'), (SELECT id FROM areas WHERE type = 'district' AND slug = 'almora'), 'age_under_25', 29.19),
  ((SELECT id FROM migration_surveys WHERE survey_key = 'round-2018'), (SELECT id FROM areas WHERE type = 'district' AND slug = 'almora'), 'wildlife_damage', 10.99),
  ((SELECT id FROM migration_surveys WHERE survey_key = 'round-2018'), (SELECT id FROM areas WHERE type = 'district' AND slug = 'bageshwar'), 'age_26_to_35', 42.10),
  ((SELECT id FROM migration_surveys WHERE survey_key = 'round-2018'), (SELECT id FROM areas WHERE type = 'district' AND slug = 'bageshwar'), 'agriculture', 42.55),
  ((SELECT id FROM migration_surveys WHERE survey_key = 'round-2018'), (SELECT id FROM areas WHERE type = 'district' AND slug = 'bageshwar'), 'dairy', 1.79),
  ((SELECT id FROM migration_surveys WHERE survey_key = 'round-2018'), (SELECT id FROM areas WHERE type = 'district' AND slug = 'bageshwar'), 'district_hq', 22.00),
  ((SELECT id FROM migration_surveys WHERE survey_key = 'round-2018'), (SELECT id FROM areas WHERE type = 'district' AND slug = 'bageshwar'), 'education', 14.49),
  ((SELECT id FROM migration_surveys WHERE survey_key = 'round-2018'), (SELECT id FROM areas WHERE type = 'district' AND slug = 'bageshwar'), 'family_influence', 1.45),
  ((SELECT id FROM migration_surveys WHERE survey_key = 'round-2018'), (SELECT id FROM areas WHERE type = 'district' AND slug = 'bageshwar'), 'farm_productivity', 2.18),
  ((SELECT id FROM migration_surveys WHERE survey_key = 'round-2018'), (SELECT id FROM areas WHERE type = 'district' AND slug = 'bageshwar'), 'government_service', 14.35),
  ((SELECT id FROM migration_surveys WHERE survey_key = 'round-2018'), (SELECT id FROM areas WHERE type = 'district' AND slug = 'bageshwar'), 'healthcare', 9.09),
  ((SELECT id FROM migration_surveys WHERE survey_key = 'round-2018'), (SELECT id FROM areas WHERE type = 'district' AND slug = 'bageshwar'), 'horticulture', 1.52),
  ((SELECT id FROM migration_surveys WHERE survey_key = 'round-2018'), (SELECT id FROM areas WHERE type = 'district' AND slug = 'bageshwar'), 'infrastructure', 4.32),
  ((SELECT id FROM migration_surveys WHERE survey_key = 'round-2018'), (SELECT id FROM areas WHERE type = 'district' AND slug = 'bageshwar'), 'labour', 29.70),
  ((SELECT id FROM migration_surveys WHERE survey_key = 'round-2018'), (SELECT id FROM areas WHERE type = 'district' AND slug = 'bageshwar'), 'livelihood', 41.39),
  ((SELECT id FROM migration_surveys WHERE survey_key = 'round-2018'), (SELECT id FROM areas WHERE type = 'district' AND slug = 'bageshwar'), 'nearby_towns', 15.45),
  ((SELECT id FROM migration_surveys WHERE survey_key = 'round-2018'), (SELECT id FROM areas WHERE type = 'district' AND slug = 'bageshwar'), 'reason_other', 23.65),
  ((SELECT id FROM migration_surveys WHERE survey_key = 'round-2018'), (SELECT id FROM areas WHERE type = 'district' AND slug = 'bageshwar'), 'other_district_in_state', 37.19),
  ((SELECT id FROM migration_surveys WHERE survey_key = 'round-2018'), (SELECT id FROM areas WHERE type = 'district' AND slug = 'bageshwar'), 'other_work', 10.09),
  ((SELECT id FROM migration_surveys WHERE survey_key = 'round-2018'), (SELECT id FROM areas WHERE type = 'district' AND slug = 'bageshwar'), 'outside_country', 0.19),
  ((SELECT id FROM migration_surveys WHERE survey_key = 'round-2018'), (SELECT id FROM areas WHERE type = 'district' AND slug = 'bageshwar'), 'outside_state', 25.18),
  ((SELECT id FROM migration_surveys WHERE survey_key = 'round-2018'), (SELECT id FROM areas WHERE type = 'district' AND slug = 'bageshwar'), 'age_over_35', 23.97),
  ((SELECT id FROM migration_surveys WHERE survey_key = 'round-2018'), (SELECT id FROM areas WHERE type = 'district' AND slug = 'bageshwar'), 'age_under_25', 33.92),
  ((SELECT id FROM migration_surveys WHERE survey_key = 'round-2018'), (SELECT id FROM areas WHERE type = 'district' AND slug = 'bageshwar'), 'wildlife_damage', 3.42),
  ((SELECT id FROM migration_surveys WHERE survey_key = 'round-2018'), (SELECT id FROM areas WHERE type = 'district' AND slug = 'chamoli'), 'age_26_to_35', 43.49),
  ((SELECT id FROM migration_surveys WHERE survey_key = 'round-2018'), (SELECT id FROM areas WHERE type = 'district' AND slug = 'chamoli'), 'agriculture', 47.24),
  ((SELECT id FROM migration_surveys WHERE survey_key = 'round-2018'), (SELECT id FROM areas WHERE type = 'district' AND slug = 'chamoli'), 'dairy', 1.40),
  ((SELECT id FROM migration_surveys WHERE survey_key = 'round-2018'), (SELECT id FROM areas WHERE type = 'district' AND slug = 'chamoli'), 'district_hq', 13.34),
  ((SELECT id FROM migration_surveys WHERE survey_key = 'round-2018'), (SELECT id FROM areas WHERE type = 'district' AND slug = 'chamoli'), 'education', 19.73),
  ((SELECT id FROM migration_surveys WHERE survey_key = 'round-2018'), (SELECT id FROM areas WHERE type = 'district' AND slug = 'chamoli'), 'family_influence', 2.51),
  ((SELECT id FROM migration_surveys WHERE survey_key = 'round-2018'), (SELECT id FROM areas WHERE type = 'district' AND slug = 'chamoli'), 'farm_productivity', 4.73),
  ((SELECT id FROM migration_surveys WHERE survey_key = 'round-2018'), (SELECT id FROM areas WHERE type = 'district' AND slug = 'chamoli'), 'government_service', 16.22),
  ((SELECT id FROM migration_surveys WHERE survey_key = 'round-2018'), (SELECT id FROM areas WHERE type = 'district' AND slug = 'chamoli'), 'healthcare', 10.83),
  ((SELECT id FROM migration_surveys WHERE survey_key = 'round-2018'), (SELECT id FROM areas WHERE type = 'district' AND slug = 'chamoli'), 'horticulture', 0.62),
  ((SELECT id FROM migration_surveys WHERE survey_key = 'round-2018'), (SELECT id FROM areas WHERE type = 'district' AND slug = 'chamoli'), 'infrastructure', 4.93),
  ((SELECT id FROM migration_surveys WHERE survey_key = 'round-2018'), (SELECT id FROM areas WHERE type = 'district' AND slug = 'chamoli'), 'labour', 28.85),
  ((SELECT id FROM migration_surveys WHERE survey_key = 'round-2018'), (SELECT id FROM areas WHERE type = 'district' AND slug = 'chamoli'), 'livelihood', 49.30),
  ((SELECT id FROM migration_surveys WHERE survey_key = 'round-2018'), (SELECT id FROM areas WHERE type = 'district' AND slug = 'chamoli'), 'nearby_towns', 19.79),
  ((SELECT id FROM migration_surveys WHERE survey_key = 'round-2018'), (SELECT id FROM areas WHERE type = 'district' AND slug = 'chamoli'), 'reason_other', 4.87),
  ((SELECT id FROM migration_surveys WHERE survey_key = 'round-2018'), (SELECT id FROM areas WHERE type = 'district' AND slug = 'chamoli'), 'other_district_in_state', 50.48),
  ((SELECT id FROM migration_surveys WHERE survey_key = 'round-2018'), (SELECT id FROM areas WHERE type = 'district' AND slug = 'chamoli'), 'other_work', 5.68),
  ((SELECT id FROM migration_surveys WHERE survey_key = 'round-2018'), (SELECT id FROM areas WHERE type = 'district' AND slug = 'chamoli'), 'outside_country', 0.51),
  ((SELECT id FROM migration_surveys WHERE survey_key = 'round-2018'), (SELECT id FROM areas WHERE type = 'district' AND slug = 'chamoli'), 'outside_state', 15.88),
  ((SELECT id FROM migration_surveys WHERE survey_key = 'round-2018'), (SELECT id FROM areas WHERE type = 'district' AND slug = 'chamoli'), 'age_over_35', 29.79),
  ((SELECT id FROM migration_surveys WHERE survey_key = 'round-2018'), (SELECT id FROM areas WHERE type = 'district' AND slug = 'chamoli'), 'age_under_25', 26.71),
  ((SELECT id FROM migration_surveys WHERE survey_key = 'round-2018'), (SELECT id FROM areas WHERE type = 'district' AND slug = 'chamoli'), 'wildlife_damage', 3.09),
  ((SELECT id FROM migration_surveys WHERE survey_key = 'round-2018'), (SELECT id FROM areas WHERE type = 'district' AND slug = 'champawat'), 'age_26_to_35', 45.49),
  ((SELECT id FROM migration_surveys WHERE survey_key = 'round-2018'), (SELECT id FROM areas WHERE type = 'district' AND slug = 'champawat'), 'agriculture', 42.41),
  ((SELECT id FROM migration_surveys WHERE survey_key = 'round-2018'), (SELECT id FROM areas WHERE type = 'district' AND slug = 'champawat'), 'dairy', 7.22),
  ((SELECT id FROM migration_surveys WHERE survey_key = 'round-2018'), (SELECT id FROM areas WHERE type = 'district' AND slug = 'champawat'), 'district_hq', 16.86),
  ((SELECT id FROM migration_surveys WHERE survey_key = 'round-2018'), (SELECT id FROM areas WHERE type = 'district' AND slug = 'champawat'), 'education', 10.24),
  ((SELECT id FROM migration_surveys WHERE survey_key = 'round-2018'), (SELECT id FROM areas WHERE type = 'district' AND slug = 'champawat'), 'family_influence', 4.30),
  ((SELECT id FROM migration_surveys WHERE survey_key = 'round-2018'), (SELECT id FROM areas WHERE type = 'district' AND slug = 'champawat'), 'farm_productivity', 6.31),
  ((SELECT id FROM migration_surveys WHERE survey_key = 'round-2018'), (SELECT id FROM areas WHERE type = 'district' AND slug = 'champawat'), 'government_service', 6.48),
  ((SELECT id FROM migration_surveys WHERE survey_key = 'round-2018'), (SELECT id FROM areas WHERE type = 'district' AND slug = 'champawat'), 'healthcare', 6.67),
  ((SELECT id FROM migration_surveys WHERE survey_key = 'round-2018'), (SELECT id FROM areas WHERE type = 'district' AND slug = 'champawat'), 'horticulture', 2.29),
  ((SELECT id FROM migration_surveys WHERE survey_key = 'round-2018'), (SELECT id FROM areas WHERE type = 'district' AND slug = 'champawat'), 'infrastructure', 5.46),
  ((SELECT id FROM migration_surveys WHERE survey_key = 'round-2018'), (SELECT id FROM areas WHERE type = 'district' AND slug = 'champawat'), 'labour', 34.23),
  ((SELECT id FROM migration_surveys WHERE survey_key = 'round-2018'), (SELECT id FROM areas WHERE type = 'district' AND slug = 'champawat'), 'livelihood', 54.90),
  ((SELECT id FROM migration_surveys WHERE survey_key = 'round-2018'), (SELECT id FROM areas WHERE type = 'district' AND slug = 'champawat'), 'nearby_towns', 14.00),
  ((SELECT id FROM migration_surveys WHERE survey_key = 'round-2018'), (SELECT id FROM areas WHERE type = 'district' AND slug = 'champawat'), 'reason_other', 5.46),
  ((SELECT id FROM migration_surveys WHERE survey_key = 'round-2018'), (SELECT id FROM areas WHERE type = 'district' AND slug = 'champawat'), 'other_district_in_state', 36.24),
  ((SELECT id FROM migration_surveys WHERE survey_key = 'round-2018'), (SELECT id FROM areas WHERE type = 'district' AND slug = 'champawat'), 'other_work', 7.37),
  ((SELECT id FROM migration_surveys WHERE survey_key = 'round-2018'), (SELECT id FROM areas WHERE type = 'district' AND slug = 'champawat'), 'outside_country', 0.30),
  ((SELECT id FROM migration_surveys WHERE survey_key = 'round-2018'), (SELECT id FROM areas WHERE type = 'district' AND slug = 'champawat'), 'outside_state', 32.59),
  ((SELECT id FROM migration_surveys WHERE survey_key = 'round-2018'), (SELECT id FROM areas WHERE type = 'district' AND slug = 'champawat'), 'age_over_35', 29.29),
  ((SELECT id FROM migration_surveys WHERE survey_key = 'round-2018'), (SELECT id FROM areas WHERE type = 'district' AND slug = 'champawat'), 'age_under_25', 25.23),
  ((SELECT id FROM migration_surveys WHERE survey_key = 'round-2018'), (SELECT id FROM areas WHERE type = 'district' AND slug = 'champawat'), 'wildlife_damage', 6.65),
  ((SELECT id FROM migration_surveys WHERE survey_key = 'round-2018'), (SELECT id FROM areas WHERE type = 'district' AND slug = 'dehradun'), 'age_26_to_35', 34.47),
  ((SELECT id FROM migration_surveys WHERE survey_key = 'round-2018'), (SELECT id FROM areas WHERE type = 'district' AND slug = 'dehradun'), 'agriculture', 45.48),
  ((SELECT id FROM migration_surveys WHERE survey_key = 'round-2018'), (SELECT id FROM areas WHERE type = 'district' AND slug = 'dehradun'), 'dairy', 2.22),
  ((SELECT id FROM migration_surveys WHERE survey_key = 'round-2018'), (SELECT id FROM areas WHERE type = 'district' AND slug = 'dehradun'), 'district_hq', 23.67),
  ((SELECT id FROM migration_surveys WHERE survey_key = 'round-2018'), (SELECT id FROM areas WHERE type = 'district' AND slug = 'dehradun'), 'education', 12.50),
  ((SELECT id FROM migration_surveys WHERE survey_key = 'round-2018'), (SELECT id FROM areas WHERE type = 'district' AND slug = 'dehradun'), 'family_influence', 1.40),
  ((SELECT id FROM migration_surveys WHERE survey_key = 'round-2018'), (SELECT id FROM areas WHERE type = 'district' AND slug = 'dehradun'), 'farm_productivity', 2.08),
  ((SELECT id FROM migration_surveys WHERE survey_key = 'round-2018'), (SELECT id FROM areas WHERE type = 'district' AND slug = 'dehradun'), 'government_service', 9.56),
  ((SELECT id FROM migration_surveys WHERE survey_key = 'round-2018'), (SELECT id FROM areas WHERE type = 'district' AND slug = 'dehradun'), 'healthcare', 6.33),
  ((SELECT id FROM migration_surveys WHERE survey_key = 'round-2018'), (SELECT id FROM areas WHERE type = 'district' AND slug = 'dehradun'), 'horticulture', 2.93),
  ((SELECT id FROM migration_surveys WHERE survey_key = 'round-2018'), (SELECT id FROM areas WHERE type = 'district' AND slug = 'dehradun'), 'infrastructure', 1.20),
  ((SELECT id FROM migration_surveys WHERE survey_key = 'round-2018'), (SELECT id FROM areas WHERE type = 'district' AND slug = 'dehradun'), 'labour', 28.14),
  ((SELECT id FROM migration_surveys WHERE survey_key = 'round-2018'), (SELECT id FROM areas WHERE type = 'district' AND slug = 'dehradun'), 'livelihood', 56.13),
  ((SELECT id FROM migration_surveys WHERE survey_key = 'round-2018'), (SELECT id FROM areas WHERE type = 'district' AND slug = 'dehradun'), 'nearby_towns', 57.12),
  ((SELECT id FROM migration_surveys WHERE survey_key = 'round-2018'), (SELECT id FROM areas WHERE type = 'district' AND slug = 'dehradun'), 'reason_other', 18.70),
  ((SELECT id FROM migration_surveys WHERE survey_key = 'round-2018'), (SELECT id FROM areas WHERE type = 'district' AND slug = 'dehradun'), 'other_district_in_state', 8.08),
  ((SELECT id FROM migration_surveys WHERE survey_key = 'round-2018'), (SELECT id FROM areas WHERE type = 'district' AND slug = 'dehradun'), 'other_work', 11.68),
  ((SELECT id FROM migration_surveys WHERE survey_key = 'round-2018'), (SELECT id FROM areas WHERE type = 'district' AND slug = 'dehradun'), 'outside_country', 0.67),
  ((SELECT id FROM migration_surveys WHERE survey_key = 'round-2018'), (SELECT id FROM areas WHERE type = 'district' AND slug = 'dehradun'), 'outside_state', 10.46),
  ((SELECT id FROM migration_surveys WHERE survey_key = 'round-2018'), (SELECT id FROM areas WHERE type = 'district' AND slug = 'dehradun'), 'age_over_35', 27.12),
  ((SELECT id FROM migration_surveys WHERE survey_key = 'round-2018'), (SELECT id FROM areas WHERE type = 'district' AND slug = 'dehradun'), 'age_under_25', 38.41),
  ((SELECT id FROM migration_surveys WHERE survey_key = 'round-2018'), (SELECT id FROM areas WHERE type = 'district' AND slug = 'dehradun'), 'wildlife_damage', 1.65),
  ((SELECT id FROM migration_surveys WHERE survey_key = 'round-2018'), (SELECT id FROM areas WHERE type = 'district' AND slug = 'haridwar'), 'age_26_to_35', 52.79),
  ((SELECT id FROM migration_surveys WHERE survey_key = 'round-2018'), (SELECT id FROM areas WHERE type = 'district' AND slug = 'haridwar'), 'agriculture', 42.98),
  ((SELECT id FROM migration_surveys WHERE survey_key = 'round-2018'), (SELECT id FROM areas WHERE type = 'district' AND slug = 'haridwar'), 'dairy', 2.65),
  ((SELECT id FROM migration_surveys WHERE survey_key = 'round-2018'), (SELECT id FROM areas WHERE type = 'district' AND slug = 'haridwar'), 'district_hq', 18.29),
  ((SELECT id FROM migration_surveys WHERE survey_key = 'round-2018'), (SELECT id FROM areas WHERE type = 'district' AND slug = 'haridwar'), 'education', 2.73),
  ((SELECT id FROM migration_surveys WHERE survey_key = 'round-2018'), (SELECT id FROM areas WHERE type = 'district' AND slug = 'haridwar'), 'family_influence', 1.69),
  ((SELECT id FROM migration_surveys WHERE survey_key = 'round-2018'), (SELECT id FROM areas WHERE type = 'district' AND slug = 'haridwar'), 'farm_productivity', 0.64),
  ((SELECT id FROM migration_surveys WHERE survey_key = 'round-2018'), (SELECT id FROM areas WHERE type = 'district' AND slug = 'haridwar'), 'government_service', 3.28),
  ((SELECT id FROM migration_surveys WHERE survey_key = 'round-2018'), (SELECT id FROM areas WHERE type = 'district' AND slug = 'haridwar'), 'healthcare', 1.62),
  ((SELECT id FROM migration_surveys WHERE survey_key = 'round-2018'), (SELECT id FROM areas WHERE type = 'district' AND slug = 'haridwar'), 'horticulture', 1.26),
  ((SELECT id FROM migration_surveys WHERE survey_key = 'round-2018'), (SELECT id FROM areas WHERE type = 'district' AND slug = 'haridwar'), 'infrastructure', 0.05),
  ((SELECT id FROM migration_surveys WHERE survey_key = 'round-2018'), (SELECT id FROM areas WHERE type = 'district' AND slug = 'haridwar'), 'labour', 42.01),
  ((SELECT id FROM migration_surveys WHERE survey_key = 'round-2018'), (SELECT id FROM areas WHERE type = 'district' AND slug = 'haridwar'), 'livelihood', 76.60),
  ((SELECT id FROM migration_surveys WHERE survey_key = 'round-2018'), (SELECT id FROM areas WHERE type = 'district' AND slug = 'haridwar'), 'nearby_towns', 44.27),
  ((SELECT id FROM migration_surveys WHERE survey_key = 'round-2018'), (SELECT id FROM areas WHERE type = 'district' AND slug = 'haridwar'), 'reason_other', 15.85),
  ((SELECT id FROM migration_surveys WHERE survey_key = 'round-2018'), (SELECT id FROM areas WHERE type = 'district' AND slug = 'haridwar'), 'other_district_in_state', 16.10),
  ((SELECT id FROM migration_surveys WHERE survey_key = 'round-2018'), (SELECT id FROM areas WHERE type = 'district' AND slug = 'haridwar'), 'other_work', 7.81),
  ((SELECT id FROM migration_surveys WHERE survey_key = 'round-2018'), (SELECT id FROM areas WHERE type = 'district' AND slug = 'haridwar'), 'outside_country', 0.49),
  ((SELECT id FROM migration_surveys WHERE survey_key = 'round-2018'), (SELECT id FROM areas WHERE type = 'district' AND slug = 'haridwar'), 'outside_state', 20.85),
  ((SELECT id FROM migration_surveys WHERE survey_key = 'round-2018'), (SELECT id FROM areas WHERE type = 'district' AND slug = 'haridwar'), 'age_over_35', 33.22),
  ((SELECT id FROM migration_surveys WHERE survey_key = 'round-2018'), (SELECT id FROM areas WHERE type = 'district' AND slug = 'haridwar'), 'age_under_25', 13.99),
  ((SELECT id FROM migration_surveys WHERE survey_key = 'round-2018'), (SELECT id FROM areas WHERE type = 'district' AND slug = 'haridwar'), 'wildlife_damage', 0.82),
  ((SELECT id FROM migration_surveys WHERE survey_key = 'round-2018'), (SELECT id FROM areas WHERE type = 'district' AND slug = 'nainital'), 'age_26_to_35', 44.57),
  ((SELECT id FROM migration_surveys WHERE survey_key = 'round-2018'), (SELECT id FROM areas WHERE type = 'district' AND slug = 'nainital'), 'agriculture', 44.41),
  ((SELECT id FROM migration_surveys WHERE survey_key = 'round-2018'), (SELECT id FROM areas WHERE type = 'district' AND slug = 'nainital'), 'dairy', 6.44),
  ((SELECT id FROM migration_surveys WHERE survey_key = 'round-2018'), (SELECT id FROM areas WHERE type = 'district' AND slug = 'nainital'), 'district_hq', 17.93),
  ((SELECT id FROM migration_surveys WHERE survey_key = 'round-2018'), (SELECT id FROM areas WHERE type = 'district' AND slug = 'nainital'), 'education', 10.37),
  ((SELECT id FROM migration_surveys WHERE survey_key = 'round-2018'), (SELECT id FROM areas WHERE type = 'district' AND slug = 'nainital'), 'family_influence', 2.10),
  ((SELECT id FROM migration_surveys WHERE survey_key = 'round-2018'), (SELECT id FROM areas WHERE type = 'district' AND slug = 'nainital'), 'farm_productivity', 4.94),
  ((SELECT id FROM migration_surveys WHERE survey_key = 'round-2018'), (SELECT id FROM areas WHERE type = 'district' AND slug = 'nainital'), 'government_service', 8.70),
  ((SELECT id FROM migration_surveys WHERE survey_key = 'round-2018'), (SELECT id FROM areas WHERE type = 'district' AND slug = 'nainital'), 'healthcare', 7.79),
  ((SELECT id FROM migration_surveys WHERE survey_key = 'round-2018'), (SELECT id FROM areas WHERE type = 'district' AND slug = 'nainital'), 'horticulture', 8.41),
  ((SELECT id FROM migration_surveys WHERE survey_key = 'round-2018'), (SELECT id FROM areas WHERE type = 'district' AND slug = 'nainital'), 'infrastructure', 4.96),
  ((SELECT id FROM migration_surveys WHERE survey_key = 'round-2018'), (SELECT id FROM areas WHERE type = 'district' AND slug = 'nainital'), 'labour', 26.27),
  ((SELECT id FROM migration_surveys WHERE survey_key = 'round-2018'), (SELECT id FROM areas WHERE type = 'district' AND slug = 'nainital'), 'livelihood', 53.70),
  ((SELECT id FROM migration_surveys WHERE survey_key = 'round-2018'), (SELECT id FROM areas WHERE type = 'district' AND slug = 'nainital'), 'nearby_towns', 35.49),
  ((SELECT id FROM migration_surveys WHERE survey_key = 'round-2018'), (SELECT id FROM areas WHERE type = 'district' AND slug = 'nainital'), 'reason_other', 9.76),
  ((SELECT id FROM migration_surveys WHERE survey_key = 'round-2018'), (SELECT id FROM areas WHERE type = 'district' AND slug = 'nainital'), 'other_district_in_state', 21.47),
  ((SELECT id FROM migration_surveys WHERE survey_key = 'round-2018'), (SELECT id FROM areas WHERE type = 'district' AND slug = 'nainital'), 'other_work', 5.76),
  ((SELECT id FROM migration_surveys WHERE survey_key = 'round-2018'), (SELECT id FROM areas WHERE type = 'district' AND slug = 'nainital'), 'outside_country', 0.47),
  ((SELECT id FROM migration_surveys WHERE survey_key = 'round-2018'), (SELECT id FROM areas WHERE type = 'district' AND slug = 'nainital'), 'outside_state', 24.64),
  ((SELECT id FROM migration_surveys WHERE survey_key = 'round-2018'), (SELECT id FROM areas WHERE type = 'district' AND slug = 'nainital'), 'age_over_35', 25.96),
  ((SELECT id FROM migration_surveys WHERE survey_key = 'round-2018'), (SELECT id FROM areas WHERE type = 'district' AND slug = 'nainital'), 'age_under_25', 29.48),
  ((SELECT id FROM migration_surveys WHERE survey_key = 'round-2018'), (SELECT id FROM areas WHERE type = 'district' AND slug = 'nainital'), 'wildlife_damage', 6.38),
  ((SELECT id FROM migration_surveys WHERE survey_key = 'round-2018'), (SELECT id FROM areas WHERE type = 'district' AND slug = 'pauri-garhwal'), 'age_26_to_35', 41.67),
  ((SELECT id FROM migration_surveys WHERE survey_key = 'round-2018'), (SELECT id FROM areas WHERE type = 'district' AND slug = 'pauri-garhwal'), 'agriculture', 38.81),
  ((SELECT id FROM migration_surveys WHERE survey_key = 'round-2018'), (SELECT id FROM areas WHERE type = 'district' AND slug = 'pauri-garhwal'), 'dairy', 1.06),
  ((SELECT id FROM migration_surveys WHERE survey_key = 'round-2018'), (SELECT id FROM areas WHERE type = 'district' AND slug = 'pauri-garhwal'), 'district_hq', 9.55),
  ((SELECT id FROM migration_surveys WHERE survey_key = 'round-2018'), (SELECT id FROM areas WHERE type = 'district' AND slug = 'pauri-garhwal'), 'education', 15.78),
  ((SELECT id FROM migration_surveys WHERE survey_key = 'round-2018'), (SELECT id FROM areas WHERE type = 'district' AND slug = 'pauri-garhwal'), 'family_influence', 2.53),
  ((SELECT id FROM migration_surveys WHERE survey_key = 'round-2018'), (SELECT id FROM areas WHERE type = 'district' AND slug = 'pauri-garhwal'), 'farm_productivity', 5.35),
  ((SELECT id FROM migration_surveys WHERE survey_key = 'round-2018'), (SELECT id FROM areas WHERE type = 'district' AND slug = 'pauri-garhwal'), 'government_service', 12.75),
  ((SELECT id FROM migration_surveys WHERE survey_key = 'round-2018'), (SELECT id FROM areas WHERE type = 'district' AND slug = 'pauri-garhwal'), 'healthcare', 11.26),
  ((SELECT id FROM migration_surveys WHERE survey_key = 'round-2018'), (SELECT id FROM areas WHERE type = 'district' AND slug = 'pauri-garhwal'), 'horticulture', 0.92),
  ((SELECT id FROM migration_surveys WHERE survey_key = 'round-2018'), (SELECT id FROM areas WHERE type = 'district' AND slug = 'pauri-garhwal'), 'infrastructure', 3.03),
  ((SELECT id FROM migration_surveys WHERE survey_key = 'round-2018'), (SELECT id FROM areas WHERE type = 'district' AND slug = 'pauri-garhwal'), 'labour', 38.67),
  ((SELECT id FROM migration_surveys WHERE survey_key = 'round-2018'), (SELECT id FROM areas WHERE type = 'district' AND slug = 'pauri-garhwal'), 'livelihood', 52.58),
  ((SELECT id FROM migration_surveys WHERE survey_key = 'round-2018'), (SELECT id FROM areas WHERE type = 'district' AND slug = 'pauri-garhwal'), 'nearby_towns', 19.61),
  ((SELECT id FROM migration_surveys WHERE survey_key = 'round-2018'), (SELECT id FROM areas WHERE type = 'district' AND slug = 'pauri-garhwal'), 'reason_other', 3.21),
  ((SELECT id FROM migration_surveys WHERE survey_key = 'round-2018'), (SELECT id FROM areas WHERE type = 'district' AND slug = 'pauri-garhwal'), 'other_district_in_state', 36.15),
  ((SELECT id FROM migration_surveys WHERE survey_key = 'round-2018'), (SELECT id FROM areas WHERE type = 'district' AND slug = 'pauri-garhwal'), 'other_work', 7.78),
  ((SELECT id FROM migration_surveys WHERE survey_key = 'round-2018'), (SELECT id FROM areas WHERE type = 'district' AND slug = 'pauri-garhwal'), 'outside_country', 0.54),
  ((SELECT id FROM migration_surveys WHERE survey_key = 'round-2018'), (SELECT id FROM areas WHERE type = 'district' AND slug = 'pauri-garhwal'), 'outside_state', 34.15),
  ((SELECT id FROM migration_surveys WHERE survey_key = 'round-2018'), (SELECT id FROM areas WHERE type = 'district' AND slug = 'pauri-garhwal'), 'age_over_35', 29.10),
  ((SELECT id FROM migration_surveys WHERE survey_key = 'round-2018'), (SELECT id FROM areas WHERE type = 'district' AND slug = 'pauri-garhwal'), 'age_under_25', 29.23),
  ((SELECT id FROM migration_surveys WHERE survey_key = 'round-2018'), (SELECT id FROM areas WHERE type = 'district' AND slug = 'pauri-garhwal'), 'wildlife_damage', 6.27),
  ((SELECT id FROM migration_surveys WHERE survey_key = 'round-2018'), (SELECT id FROM areas WHERE type = 'district' AND slug = 'pithoragarh'), 'age_26_to_35', 42.58),
  ((SELECT id FROM migration_surveys WHERE survey_key = 'round-2018'), (SELECT id FROM areas WHERE type = 'district' AND slug = 'pithoragarh'), 'agriculture', 40.78),
  ((SELECT id FROM migration_surveys WHERE survey_key = 'round-2018'), (SELECT id FROM areas WHERE type = 'district' AND slug = 'pithoragarh'), 'dairy', 4.44),
  ((SELECT id FROM migration_surveys WHERE survey_key = 'round-2018'), (SELECT id FROM areas WHERE type = 'district' AND slug = 'pithoragarh'), 'district_hq', 33.07),
  ((SELECT id FROM migration_surveys WHERE survey_key = 'round-2018'), (SELECT id FROM areas WHERE type = 'district' AND slug = 'pithoragarh'), 'education', 19.52),
  ((SELECT id FROM migration_surveys WHERE survey_key = 'round-2018'), (SELECT id FROM areas WHERE type = 'district' AND slug = 'pithoragarh'), 'family_influence', 2.36),
  ((SELECT id FROM migration_surveys WHERE survey_key = 'round-2018'), (SELECT id FROM areas WHERE type = 'district' AND slug = 'pithoragarh'), 'farm_productivity', 4.66),
  ((SELECT id FROM migration_surveys WHERE survey_key = 'round-2018'), (SELECT id FROM areas WHERE type = 'district' AND slug = 'pithoragarh'), 'government_service', 15.13),
  ((SELECT id FROM migration_surveys WHERE survey_key = 'round-2018'), (SELECT id FROM areas WHERE type = 'district' AND slug = 'pithoragarh'), 'healthcare', 10.13),
  ((SELECT id FROM migration_surveys WHERE survey_key = 'round-2018'), (SELECT id FROM areas WHERE type = 'district' AND slug = 'pithoragarh'), 'horticulture', 2.16),
  ((SELECT id FROM migration_surveys WHERE survey_key = 'round-2018'), (SELECT id FROM areas WHERE type = 'district' AND slug = 'pithoragarh'), 'infrastructure', 4.97),
  ((SELECT id FROM migration_surveys WHERE survey_key = 'round-2018'), (SELECT id FROM areas WHERE type = 'district' AND slug = 'pithoragarh'), 'labour', 27.17),
  ((SELECT id FROM migration_surveys WHERE survey_key = 'round-2018'), (SELECT id FROM areas WHERE type = 'district' AND slug = 'pithoragarh'), 'livelihood', 42.81),
  ((SELECT id FROM migration_surveys WHERE survey_key = 'round-2018'), (SELECT id FROM areas WHERE type = 'district' AND slug = 'pithoragarh'), 'nearby_towns', 15.70),
  ((SELECT id FROM migration_surveys WHERE survey_key = 'round-2018'), (SELECT id FROM areas WHERE type = 'district' AND slug = 'pithoragarh'), 'reason_other', 11.48),
  ((SELECT id FROM migration_surveys WHERE survey_key = 'round-2018'), (SELECT id FROM areas WHERE type = 'district' AND slug = 'pithoragarh'), 'other_district_in_state', 34.33),
  ((SELECT id FROM migration_surveys WHERE survey_key = 'round-2018'), (SELECT id FROM areas WHERE type = 'district' AND slug = 'pithoragarh'), 'other_work', 10.31),
  ((SELECT id FROM migration_surveys WHERE survey_key = 'round-2018'), (SELECT id FROM areas WHERE type = 'district' AND slug = 'pithoragarh'), 'outside_country', 0.23),
  ((SELECT id FROM migration_surveys WHERE survey_key = 'round-2018'), (SELECT id FROM areas WHERE type = 'district' AND slug = 'pithoragarh'), 'outside_state', 16.67),
  ((SELECT id FROM migration_surveys WHERE survey_key = 'round-2018'), (SELECT id FROM areas WHERE type = 'district' AND slug = 'pithoragarh'), 'age_over_35', 29.10),
  ((SELECT id FROM migration_surveys WHERE survey_key = 'round-2018'), (SELECT id FROM areas WHERE type = 'district' AND slug = 'pithoragarh'), 'age_under_25', 28.32),
  ((SELECT id FROM migration_surveys WHERE survey_key = 'round-2018'), (SELECT id FROM areas WHERE type = 'district' AND slug = 'pithoragarh'), 'wildlife_damage', 4.08),
  ((SELECT id FROM migration_surveys WHERE survey_key = 'round-2018'), (SELECT id FROM areas WHERE type = 'district' AND slug = 'rudraprayag'), 'age_26_to_35', 41.83),
  ((SELECT id FROM migration_surveys WHERE survey_key = 'round-2018'), (SELECT id FROM areas WHERE type = 'district' AND slug = 'rudraprayag'), 'agriculture', 43.26),
  ((SELECT id FROM migration_surveys WHERE survey_key = 'round-2018'), (SELECT id FROM areas WHERE type = 'district' AND slug = 'rudraprayag'), 'dairy', 0.57),
  ((SELECT id FROM migration_surveys WHERE survey_key = 'round-2018'), (SELECT id FROM areas WHERE type = 'district' AND slug = 'rudraprayag'), 'district_hq', 12.66),
  ((SELECT id FROM migration_surveys WHERE survey_key = 'round-2018'), (SELECT id FROM areas WHERE type = 'district' AND slug = 'rudraprayag'), 'education', 15.67),
  ((SELECT id FROM migration_surveys WHERE survey_key = 'round-2018'), (SELECT id FROM areas WHERE type = 'district' AND slug = 'rudraprayag'), 'family_influence', 3.26),
  ((SELECT id FROM migration_surveys WHERE survey_key = 'round-2018'), (SELECT id FROM areas WHERE type = 'district' AND slug = 'rudraprayag'), 'farm_productivity', 4.27),
  ((SELECT id FROM migration_surveys WHERE survey_key = 'round-2018'), (SELECT id FROM areas WHERE type = 'district' AND slug = 'rudraprayag'), 'government_service', 15.19),
  ((SELECT id FROM migration_surveys WHERE survey_key = 'round-2018'), (SELECT id FROM areas WHERE type = 'district' AND slug = 'rudraprayag'), 'healthcare', 8.64),
  ((SELECT id FROM migration_surveys WHERE survey_key = 'round-2018'), (SELECT id FROM areas WHERE type = 'district' AND slug = 'rudraprayag'), 'horticulture', 0.73),
  ((SELECT id FROM migration_surveys WHERE survey_key = 'round-2018'), (SELECT id FROM areas WHERE type = 'district' AND slug = 'rudraprayag'), 'infrastructure', 4.43),
  ((SELECT id FROM migration_surveys WHERE survey_key = 'round-2018'), (SELECT id FROM areas WHERE type = 'district' AND slug = 'rudraprayag'), 'labour', 31.43),
  ((SELECT id FROM migration_surveys WHERE survey_key = 'round-2018'), (SELECT id FROM areas WHERE type = 'district' AND slug = 'rudraprayag'), 'livelihood', 52.90),
  ((SELECT id FROM migration_surveys WHERE survey_key = 'round-2018'), (SELECT id FROM areas WHERE type = 'district' AND slug = 'rudraprayag'), 'nearby_towns', 19.34),
  ((SELECT id FROM migration_surveys WHERE survey_key = 'round-2018'), (SELECT id FROM areas WHERE type = 'district' AND slug = 'rudraprayag'), 'reason_other', 5.72),
  ((SELECT id FROM migration_surveys WHERE survey_key = 'round-2018'), (SELECT id FROM areas WHERE type = 'district' AND slug = 'rudraprayag'), 'other_district_in_state', 40.51),
  ((SELECT id FROM migration_surveys WHERE survey_key = 'round-2018'), (SELECT id FROM areas WHERE type = 'district' AND slug = 'rudraprayag'), 'other_work', 8.81),
  ((SELECT id FROM migration_surveys WHERE survey_key = 'round-2018'), (SELECT id FROM areas WHERE type = 'district' AND slug = 'rudraprayag'), 'outside_country', 1.80),
  ((SELECT id FROM migration_surveys WHERE survey_key = 'round-2018'), (SELECT id FROM areas WHERE type = 'district' AND slug = 'rudraprayag'), 'outside_state', 25.69),
  ((SELECT id FROM migration_surveys WHERE survey_key = 'round-2018'), (SELECT id FROM areas WHERE type = 'district' AND slug = 'rudraprayag'), 'age_over_35', 29.20),
  ((SELECT id FROM migration_surveys WHERE survey_key = 'round-2018'), (SELECT id FROM areas WHERE type = 'district' AND slug = 'rudraprayag'), 'age_under_25', 28.97),
  ((SELECT id FROM migration_surveys WHERE survey_key = 'round-2018'), (SELECT id FROM areas WHERE type = 'district' AND slug = 'rudraprayag'), 'wildlife_damage', 5.11),
  ((SELECT id FROM migration_surveys WHERE survey_key = 'round-2018'), (SELECT id FROM areas WHERE type = 'district' AND slug = 'tehri-garhwal'), 'age_26_to_35', 40.92),
  ((SELECT id FROM migration_surveys WHERE survey_key = 'round-2018'), (SELECT id FROM areas WHERE type = 'district' AND slug = 'tehri-garhwal'), 'agriculture', 50.04),
  ((SELECT id FROM migration_surveys WHERE survey_key = 'round-2018'), (SELECT id FROM areas WHERE type = 'district' AND slug = 'tehri-garhwal'), 'dairy', 1.47),
  ((SELECT id FROM migration_surveys WHERE survey_key = 'round-2018'), (SELECT id FROM areas WHERE type = 'district' AND slug = 'tehri-garhwal'), 'district_hq', 9.42),
  ((SELECT id FROM migration_surveys WHERE survey_key = 'round-2018'), (SELECT id FROM areas WHERE type = 'district' AND slug = 'tehri-garhwal'), 'education', 18.24),
  ((SELECT id FROM migration_surveys WHERE survey_key = 'round-2018'), (SELECT id FROM areas WHERE type = 'district' AND slug = 'tehri-garhwal'), 'family_influence', 2.47),
  ((SELECT id FROM migration_surveys WHERE survey_key = 'round-2018'), (SELECT id FROM areas WHERE type = 'district' AND slug = 'tehri-garhwal'), 'farm_productivity', 6.17),
  ((SELECT id FROM migration_surveys WHERE survey_key = 'round-2018'), (SELECT id FROM areas WHERE type = 'district' AND slug = 'tehri-garhwal'), 'government_service', 7.83),
  ((SELECT id FROM migration_surveys WHERE survey_key = 'round-2018'), (SELECT id FROM areas WHERE type = 'district' AND slug = 'tehri-garhwal'), 'healthcare', 7.84),
  ((SELECT id FROM migration_surveys WHERE survey_key = 'round-2018'), (SELECT id FROM areas WHERE type = 'district' AND slug = 'tehri-garhwal'), 'horticulture', 0.82),
  ((SELECT id FROM migration_surveys WHERE survey_key = 'round-2018'), (SELECT id FROM areas WHERE type = 'district' AND slug = 'tehri-garhwal'), 'infrastructure', 3.07),
  ((SELECT id FROM migration_surveys WHERE survey_key = 'round-2018'), (SELECT id FROM areas WHERE type = 'district' AND slug = 'tehri-garhwal'), 'labour', 30.32),
  ((SELECT id FROM migration_surveys WHERE survey_key = 'round-2018'), (SELECT id FROM areas WHERE type = 'district' AND slug = 'tehri-garhwal'), 'livelihood', 52.43),
  ((SELECT id FROM migration_surveys WHERE survey_key = 'round-2018'), (SELECT id FROM areas WHERE type = 'district' AND slug = 'tehri-garhwal'), 'nearby_towns', 17.73),
  ((SELECT id FROM migration_surveys WHERE survey_key = 'round-2018'), (SELECT id FROM areas WHERE type = 'district' AND slug = 'tehri-garhwal'), 'reason_other', 5.52),
  ((SELECT id FROM migration_surveys WHERE survey_key = 'round-2018'), (SELECT id FROM areas WHERE type = 'district' AND slug = 'tehri-garhwal'), 'other_district_in_state', 40.78),
  ((SELECT id FROM migration_surveys WHERE survey_key = 'round-2018'), (SELECT id FROM areas WHERE type = 'district' AND slug = 'tehri-garhwal'), 'other_work', 9.52),
  ((SELECT id FROM migration_surveys WHERE survey_key = 'round-2018'), (SELECT id FROM areas WHERE type = 'district' AND slug = 'tehri-garhwal'), 'outside_country', 3.09),
  ((SELECT id FROM migration_surveys WHERE survey_key = 'round-2018'), (SELECT id FROM areas WHERE type = 'district' AND slug = 'tehri-garhwal'), 'outside_state', 28.98),
  ((SELECT id FROM migration_surveys WHERE survey_key = 'round-2018'), (SELECT id FROM areas WHERE type = 'district' AND slug = 'tehri-garhwal'), 'age_over_35', 29.82),
  ((SELECT id FROM migration_surveys WHERE survey_key = 'round-2018'), (SELECT id FROM areas WHERE type = 'district' AND slug = 'tehri-garhwal'), 'age_under_25', 29.26),
  ((SELECT id FROM migration_surveys WHERE survey_key = 'round-2018'), (SELECT id FROM areas WHERE type = 'district' AND slug = 'tehri-garhwal'), 'wildlife_damage', 4.26),
  ((SELECT id FROM migration_surveys WHERE survey_key = 'round-2018'), (SELECT id FROM areas WHERE type = 'district' AND slug = 'udham-singh-nagar'), 'age_26_to_35', 43.34),
  ((SELECT id FROM migration_surveys WHERE survey_key = 'round-2018'), (SELECT id FROM areas WHERE type = 'district' AND slug = 'udham-singh-nagar'), 'agriculture', 37.64),
  ((SELECT id FROM migration_surveys WHERE survey_key = 'round-2018'), (SELECT id FROM areas WHERE type = 'district' AND slug = 'udham-singh-nagar'), 'dairy', 2.95),
  ((SELECT id FROM migration_surveys WHERE survey_key = 'round-2018'), (SELECT id FROM areas WHERE type = 'district' AND slug = 'udham-singh-nagar'), 'district_hq', 8.48),
  ((SELECT id FROM migration_surveys WHERE survey_key = 'round-2018'), (SELECT id FROM areas WHERE type = 'district' AND slug = 'udham-singh-nagar'), 'education', 3.52),
  ((SELECT id FROM migration_surveys WHERE survey_key = 'round-2018'), (SELECT id FROM areas WHERE type = 'district' AND slug = 'udham-singh-nagar'), 'family_influence', 5.40),
  ((SELECT id FROM migration_surveys WHERE survey_key = 'round-2018'), (SELECT id FROM areas WHERE type = 'district' AND slug = 'udham-singh-nagar'), 'farm_productivity', 0.38),
  ((SELECT id FROM migration_surveys WHERE survey_key = 'round-2018'), (SELECT id FROM areas WHERE type = 'district' AND slug = 'udham-singh-nagar'), 'government_service', 3.67),
  ((SELECT id FROM migration_surveys WHERE survey_key = 'round-2018'), (SELECT id FROM areas WHERE type = 'district' AND slug = 'udham-singh-nagar'), 'healthcare', 4.27),
  ((SELECT id FROM migration_surveys WHERE survey_key = 'round-2018'), (SELECT id FROM areas WHERE type = 'district' AND slug = 'udham-singh-nagar'), 'horticulture', 1.23),
  ((SELECT id FROM migration_surveys WHERE survey_key = 'round-2018'), (SELECT id FROM areas WHERE type = 'district' AND slug = 'udham-singh-nagar'), 'infrastructure', 0.60),
  ((SELECT id FROM migration_surveys WHERE survey_key = 'round-2018'), (SELECT id FROM areas WHERE type = 'district' AND slug = 'udham-singh-nagar'), 'labour', 45.61),
  ((SELECT id FROM migration_surveys WHERE survey_key = 'round-2018'), (SELECT id FROM areas WHERE type = 'district' AND slug = 'udham-singh-nagar'), 'livelihood', 65.63),
  ((SELECT id FROM migration_surveys WHERE survey_key = 'round-2018'), (SELECT id FROM areas WHERE type = 'district' AND slug = 'udham-singh-nagar'), 'nearby_towns', 27.48),
  ((SELECT id FROM migration_surveys WHERE survey_key = 'round-2018'), (SELECT id FROM areas WHERE type = 'district' AND slug = 'udham-singh-nagar'), 'reason_other', 17.60),
  ((SELECT id FROM migration_surveys WHERE survey_key = 'round-2018'), (SELECT id FROM areas WHERE type = 'district' AND slug = 'udham-singh-nagar'), 'other_district_in_state', 28.04),
  ((SELECT id FROM migration_surveys WHERE survey_key = 'round-2018'), (SELECT id FROM areas WHERE type = 'district' AND slug = 'udham-singh-nagar'), 'other_work', 8.89),
  ((SELECT id FROM migration_surveys WHERE survey_key = 'round-2018'), (SELECT id FROM areas WHERE type = 'district' AND slug = 'udham-singh-nagar'), 'outside_country', 4.89),
  ((SELECT id FROM migration_surveys WHERE survey_key = 'round-2018'), (SELECT id FROM areas WHERE type = 'district' AND slug = 'udham-singh-nagar'), 'outside_state', 31.11),
  ((SELECT id FROM migration_surveys WHERE survey_key = 'round-2018'), (SELECT id FROM areas WHERE type = 'district' AND slug = 'udham-singh-nagar'), 'age_over_35', 40.00),
  ((SELECT id FROM migration_surveys WHERE survey_key = 'round-2018'), (SELECT id FROM areas WHERE type = 'district' AND slug = 'udham-singh-nagar'), 'age_under_25', 16.66),
  ((SELECT id FROM migration_surveys WHERE survey_key = 'round-2018'), (SELECT id FROM areas WHERE type = 'district' AND slug = 'udham-singh-nagar'), 'wildlife_damage', 2.60),
  ((SELECT id FROM migration_surveys WHERE survey_key = 'round-2018'), (SELECT id FROM areas WHERE type = 'district' AND slug = 'uttarkashi'), 'age_26_to_35', 36.56),
  ((SELECT id FROM migration_surveys WHERE survey_key = 'round-2018'), (SELECT id FROM areas WHERE type = 'district' AND slug = 'uttarkashi'), 'agriculture', 55.32),
  ((SELECT id FROM migration_surveys WHERE survey_key = 'round-2018'), (SELECT id FROM areas WHERE type = 'district' AND slug = 'uttarkashi'), 'dairy', 0.99),
  ((SELECT id FROM migration_surveys WHERE survey_key = 'round-2018'), (SELECT id FROM areas WHERE type = 'district' AND slug = 'uttarkashi'), 'district_hq', 20.27),
  ((SELECT id FROM migration_surveys WHERE survey_key = 'round-2018'), (SELECT id FROM areas WHERE type = 'district' AND slug = 'uttarkashi'), 'education', 17.44),
  ((SELECT id FROM migration_surveys WHERE survey_key = 'round-2018'), (SELECT id FROM areas WHERE type = 'district' AND slug = 'uttarkashi'), 'family_influence', 2.10),
  ((SELECT id FROM migration_surveys WHERE survey_key = 'round-2018'), (SELECT id FROM areas WHERE type = 'district' AND slug = 'uttarkashi'), 'farm_productivity', 7.14),
  ((SELECT id FROM migration_surveys WHERE survey_key = 'round-2018'), (SELECT id FROM areas WHERE type = 'district' AND slug = 'uttarkashi'), 'government_service', 9.40),
  ((SELECT id FROM migration_surveys WHERE survey_key = 'round-2018'), (SELECT id FROM areas WHERE type = 'district' AND slug = 'uttarkashi'), 'healthcare', 6.04),
  ((SELECT id FROM migration_surveys WHERE survey_key = 'round-2018'), (SELECT id FROM areas WHERE type = 'district' AND slug = 'uttarkashi'), 'horticulture', 6.23),
  ((SELECT id FROM migration_surveys WHERE survey_key = 'round-2018'), (SELECT id FROM areas WHERE type = 'district' AND slug = 'uttarkashi'), 'infrastructure', 2.29),
  ((SELECT id FROM migration_surveys WHERE survey_key = 'round-2018'), (SELECT id FROM areas WHERE type = 'district' AND slug = 'uttarkashi'), 'labour', 22.56),
  ((SELECT id FROM migration_surveys WHERE survey_key = 'round-2018'), (SELECT id FROM areas WHERE type = 'district' AND slug = 'uttarkashi'), 'livelihood', 41.77),
  ((SELECT id FROM migration_surveys WHERE survey_key = 'round-2018'), (SELECT id FROM areas WHERE type = 'district' AND slug = 'uttarkashi'), 'nearby_towns', 39.14),
  ((SELECT id FROM migration_surveys WHERE survey_key = 'round-2018'), (SELECT id FROM areas WHERE type = 'district' AND slug = 'uttarkashi'), 'reason_other', 19.17),
  ((SELECT id FROM migration_surveys WHERE survey_key = 'round-2018'), (SELECT id FROM areas WHERE type = 'district' AND slug = 'uttarkashi'), 'other_district_in_state', 22.37),
  ((SELECT id FROM migration_surveys WHERE survey_key = 'round-2018'), (SELECT id FROM areas WHERE type = 'district' AND slug = 'uttarkashi'), 'other_work', 5.50),
  ((SELECT id FROM migration_surveys WHERE survey_key = 'round-2018'), (SELECT id FROM areas WHERE type = 'district' AND slug = 'uttarkashi'), 'outside_country', 0.89),
  ((SELECT id FROM migration_surveys WHERE survey_key = 'round-2018'), (SELECT id FROM areas WHERE type = 'district' AND slug = 'uttarkashi'), 'outside_state', 17.34),
  ((SELECT id FROM migration_surveys WHERE survey_key = 'round-2018'), (SELECT id FROM areas WHERE type = 'district' AND slug = 'uttarkashi'), 'age_over_35', 32.77),
  ((SELECT id FROM migration_surveys WHERE survey_key = 'round-2018'), (SELECT id FROM areas WHERE type = 'district' AND slug = 'uttarkashi'), 'age_under_25', 30.68),
  ((SELECT id FROM migration_surveys WHERE survey_key = 'round-2018'), (SELECT id FROM areas WHERE type = 'district' AND slug = 'uttarkashi'), 'wildlife_damage', 4.04),
  ((SELECT id FROM migration_surveys WHERE survey_key = 'round-2022'), (SELECT id FROM areas WHERE type = 'district' AND slug = 'almora'), 'agri_horti_livestock', 46.23),
  ((SELECT id FROM migration_surveys WHERE survey_key = 'round-2022'), (SELECT id FROM areas WHERE type = 'district' AND slug = 'almora'), 'government_service_2022', 6.78),
  ((SELECT id FROM migration_surveys WHERE survey_key = 'round-2022'), (SELECT id FROM areas WHERE type = 'district' AND slug = 'almora'), 'labour_2022', 18.11),
  ((SELECT id FROM migration_surveys WHERE survey_key = 'round-2022'), (SELECT id FROM areas WHERE type = 'district' AND slug = 'almora'), 'mgnrega', 21.24),
  ((SELECT id FROM migration_surveys WHERE survey_key = 'round-2022'), (SELECT id FROM areas WHERE type = 'district' AND slug = 'almora'), 'self_employment_other', 7.64),
  ((SELECT id FROM migration_surveys WHERE survey_key = 'round-2022'), (SELECT id FROM areas WHERE type = 'district' AND slug = 'bageshwar'), 'agri_horti_livestock', 41.59),
  ((SELECT id FROM migration_surveys WHERE survey_key = 'round-2022'), (SELECT id FROM areas WHERE type = 'district' AND slug = 'bageshwar'), 'government_service_2022', 10.21),
  ((SELECT id FROM migration_surveys WHERE survey_key = 'round-2022'), (SELECT id FROM areas WHERE type = 'district' AND slug = 'bageshwar'), 'labour_2022', 19.54),
  ((SELECT id FROM migration_surveys WHERE survey_key = 'round-2022'), (SELECT id FROM areas WHERE type = 'district' AND slug = 'bageshwar'), 'mgnrega', 19.94),
  ((SELECT id FROM migration_surveys WHERE survey_key = 'round-2022'), (SELECT id FROM areas WHERE type = 'district' AND slug = 'bageshwar'), 'self_employment_other', 8.71),
  ((SELECT id FROM migration_surveys WHERE survey_key = 'round-2022'), (SELECT id FROM areas WHERE type = 'district' AND slug = 'chamoli'), 'agri_horti_livestock', 41.44),
  ((SELECT id FROM migration_surveys WHERE survey_key = 'round-2022'), (SELECT id FROM areas WHERE type = 'district' AND slug = 'chamoli'), 'government_service_2022', 13.10),
  ((SELECT id FROM migration_surveys WHERE survey_key = 'round-2022'), (SELECT id FROM areas WHERE type = 'district' AND slug = 'chamoli'), 'labour_2022', 10.88),
  ((SELECT id FROM migration_surveys WHERE survey_key = 'round-2022'), (SELECT id FROM areas WHERE type = 'district' AND slug = 'chamoli'), 'mgnrega', 27.18),
  ((SELECT id FROM migration_surveys WHERE survey_key = 'round-2022'), (SELECT id FROM areas WHERE type = 'district' AND slug = 'chamoli'), 'self_employment_other', 7.40),
  ((SELECT id FROM migration_surveys WHERE survey_key = 'round-2022'), (SELECT id FROM areas WHERE type = 'district' AND slug = 'champawat'), 'agri_horti_livestock', 50.78),
  ((SELECT id FROM migration_surveys WHERE survey_key = 'round-2022'), (SELECT id FROM areas WHERE type = 'district' AND slug = 'champawat'), 'government_service_2022', 4.86),
  ((SELECT id FROM migration_surveys WHERE survey_key = 'round-2022'), (SELECT id FROM areas WHERE type = 'district' AND slug = 'champawat'), 'labour_2022', 15.55),
  ((SELECT id FROM migration_surveys WHERE survey_key = 'round-2022'), (SELECT id FROM areas WHERE type = 'district' AND slug = 'champawat'), 'mgnrega', 22.81),
  ((SELECT id FROM migration_surveys WHERE survey_key = 'round-2022'), (SELECT id FROM areas WHERE type = 'district' AND slug = 'champawat'), 'self_employment_other', 6.01),
  ((SELECT id FROM migration_surveys WHERE survey_key = 'round-2022'), (SELECT id FROM areas WHERE type = 'district' AND slug = 'dehradun'), 'agri_horti_livestock', 47.03),
  ((SELECT id FROM migration_surveys WHERE survey_key = 'round-2022'), (SELECT id FROM areas WHERE type = 'district' AND slug = 'dehradun'), 'government_service_2022', 8.05),
  ((SELECT id FROM migration_surveys WHERE survey_key = 'round-2022'), (SELECT id FROM areas WHERE type = 'district' AND slug = 'dehradun'), 'labour_2022', 17.71),
  ((SELECT id FROM migration_surveys WHERE survey_key = 'round-2022'), (SELECT id FROM areas WHERE type = 'district' AND slug = 'dehradun'), 'mgnrega', 17.12),
  ((SELECT id FROM migration_surveys WHERE survey_key = 'round-2022'), (SELECT id FROM areas WHERE type = 'district' AND slug = 'dehradun'), 'self_employment_other', 10.08),
  ((SELECT id FROM migration_surveys WHERE survey_key = 'round-2022'), (SELECT id FROM areas WHERE type = 'district' AND slug = 'haridwar'), 'agri_horti_livestock', 58.74),
  ((SELECT id FROM migration_surveys WHERE survey_key = 'round-2022'), (SELECT id FROM areas WHERE type = 'district' AND slug = 'haridwar'), 'government_service_2022', 2.82),
  ((SELECT id FROM migration_surveys WHERE survey_key = 'round-2022'), (SELECT id FROM areas WHERE type = 'district' AND slug = 'haridwar'), 'labour_2022', 20.70),
  ((SELECT id FROM migration_surveys WHERE survey_key = 'round-2022'), (SELECT id FROM areas WHERE type = 'district' AND slug = 'haridwar'), 'mgnrega', 9.05),
  ((SELECT id FROM migration_surveys WHERE survey_key = 'round-2022'), (SELECT id FROM areas WHERE type = 'district' AND slug = 'haridwar'), 'self_employment_other', 8.69),
  ((SELECT id FROM migration_surveys WHERE survey_key = 'round-2022'), (SELECT id FROM areas WHERE type = 'district' AND slug = 'nainital'), 'agri_horti_livestock', 51.94),
  ((SELECT id FROM migration_surveys WHERE survey_key = 'round-2022'), (SELECT id FROM areas WHERE type = 'district' AND slug = 'nainital'), 'government_service_2022', 8.29),
  ((SELECT id FROM migration_surveys WHERE survey_key = 'round-2022'), (SELECT id FROM areas WHERE type = 'district' AND slug = 'nainital'), 'labour_2022', 15.64),
  ((SELECT id FROM migration_surveys WHERE survey_key = 'round-2022'), (SELECT id FROM areas WHERE type = 'district' AND slug = 'nainital'), 'mgnrega', 16.26),
  ((SELECT id FROM migration_surveys WHERE survey_key = 'round-2022'), (SELECT id FROM areas WHERE type = 'district' AND slug = 'nainital'), 'self_employment_other', 7.87),
  ((SELECT id FROM migration_surveys WHERE survey_key = 'round-2022'), (SELECT id FROM areas WHERE type = 'district' AND slug = 'pauri-garhwal'), 'agri_horti_livestock', 30.16),
  ((SELECT id FROM migration_surveys WHERE survey_key = 'round-2022'), (SELECT id FROM areas WHERE type = 'district' AND slug = 'pauri-garhwal'), 'government_service_2022', 9.09),
  ((SELECT id FROM migration_surveys WHERE survey_key = 'round-2022'), (SELECT id FROM areas WHERE type = 'district' AND slug = 'pauri-garhwal'), 'labour_2022', 13.93),
  ((SELECT id FROM migration_surveys WHERE survey_key = 'round-2022'), (SELECT id FROM areas WHERE type = 'district' AND slug = 'pauri-garhwal'), 'mgnrega', 39.01),
  ((SELECT id FROM migration_surveys WHERE survey_key = 'round-2022'), (SELECT id FROM areas WHERE type = 'district' AND slug = 'pauri-garhwal'), 'self_employment_other', 7.82),
  ((SELECT id FROM migration_surveys WHERE survey_key = 'round-2022'), (SELECT id FROM areas WHERE type = 'district' AND slug = 'pithoragarh'), 'agri_horti_livestock', 36.00),
  ((SELECT id FROM migration_surveys WHERE survey_key = 'round-2022'), (SELECT id FROM areas WHERE type = 'district' AND slug = 'pithoragarh'), 'government_service_2022', 12.56),
  ((SELECT id FROM migration_surveys WHERE survey_key = 'round-2022'), (SELECT id FROM areas WHERE type = 'district' AND slug = 'pithoragarh'), 'labour_2022', 16.70),
  ((SELECT id FROM migration_surveys WHERE survey_key = 'round-2022'), (SELECT id FROM areas WHERE type = 'district' AND slug = 'pithoragarh'), 'mgnrega', 25.39),
  ((SELECT id FROM migration_surveys WHERE survey_key = 'round-2022'), (SELECT id FROM areas WHERE type = 'district' AND slug = 'pithoragarh'), 'self_employment_other', 9.35),
  ((SELECT id FROM migration_surveys WHERE survey_key = 'round-2022'), (SELECT id FROM areas WHERE type = 'district' AND slug = 'rudraprayag'), 'agri_horti_livestock', 35.25),
  ((SELECT id FROM migration_surveys WHERE survey_key = 'round-2022'), (SELECT id FROM areas WHERE type = 'district' AND slug = 'rudraprayag'), 'government_service_2022', 11.01),
  ((SELECT id FROM migration_surveys WHERE survey_key = 'round-2022'), (SELECT id FROM areas WHERE type = 'district' AND slug = 'rudraprayag'), 'labour_2022', 15.27),
  ((SELECT id FROM migration_surveys WHERE survey_key = 'round-2022'), (SELECT id FROM areas WHERE type = 'district' AND slug = 'rudraprayag'), 'mgnrega', 26.12),
  ((SELECT id FROM migration_surveys WHERE survey_key = 'round-2022'), (SELECT id FROM areas WHERE type = 'district' AND slug = 'rudraprayag'), 'self_employment_other', 12.35),
  ((SELECT id FROM migration_surveys WHERE survey_key = 'round-2022'), (SELECT id FROM areas WHERE type = 'district' AND slug = 'tehri-garhwal'), 'agri_horti_livestock', 37.93),
  ((SELECT id FROM migration_surveys WHERE survey_key = 'round-2022'), (SELECT id FROM areas WHERE type = 'district' AND slug = 'tehri-garhwal'), 'government_service_2022', 6.79),
  ((SELECT id FROM migration_surveys WHERE survey_key = 'round-2022'), (SELECT id FROM areas WHERE type = 'district' AND slug = 'tehri-garhwal'), 'labour_2022', 12.68),
  ((SELECT id FROM migration_surveys WHERE survey_key = 'round-2022'), (SELECT id FROM areas WHERE type = 'district' AND slug = 'tehri-garhwal'), 'mgnrega', 33.97),
  ((SELECT id FROM migration_surveys WHERE survey_key = 'round-2022'), (SELECT id FROM areas WHERE type = 'district' AND slug = 'tehri-garhwal'), 'self_employment_other', 8.63),
  ((SELECT id FROM migration_surveys WHERE survey_key = 'round-2022'), (SELECT id FROM areas WHERE type = 'district' AND slug = 'udham-singh-nagar'), 'agri_horti_livestock', 51.34),
  ((SELECT id FROM migration_surveys WHERE survey_key = 'round-2022'), (SELECT id FROM areas WHERE type = 'district' AND slug = 'udham-singh-nagar'), 'government_service_2022', 4.60),
  ((SELECT id FROM migration_surveys WHERE survey_key = 'round-2022'), (SELECT id FROM areas WHERE type = 'district' AND slug = 'udham-singh-nagar'), 'labour_2022', 21.38),
  ((SELECT id FROM migration_surveys WHERE survey_key = 'round-2022'), (SELECT id FROM areas WHERE type = 'district' AND slug = 'udham-singh-nagar'), 'mgnrega', 11.84),
  ((SELECT id FROM migration_surveys WHERE survey_key = 'round-2022'), (SELECT id FROM areas WHERE type = 'district' AND slug = 'udham-singh-nagar'), 'self_employment_other', 10.83),
  ((SELECT id FROM migration_surveys WHERE survey_key = 'round-2022'), (SELECT id FROM areas WHERE type = 'district' AND slug = 'uttarkashi'), 'agri_horti_livestock', 57.50),
  ((SELECT id FROM migration_surveys WHERE survey_key = 'round-2022'), (SELECT id FROM areas WHERE type = 'district' AND slug = 'uttarkashi'), 'government_service_2022', 7.20),
  ((SELECT id FROM migration_surveys WHERE survey_key = 'round-2022'), (SELECT id FROM areas WHERE type = 'district' AND slug = 'uttarkashi'), 'labour_2022', 9.08),
  ((SELECT id FROM migration_surveys WHERE survey_key = 'round-2022'), (SELECT id FROM areas WHERE type = 'district' AND slug = 'uttarkashi'), 'mgnrega', 19.94),
  ((SELECT id FROM migration_surveys WHERE survey_key = 'round-2022'), (SELECT id FROM areas WHERE type = 'district' AND slug = 'uttarkashi'), 'self_employment_other', 6.28),
  ((SELECT id FROM migration_surveys WHERE survey_key = 'round-2018'), (SELECT id FROM areas WHERE type = 'district' AND slug = 'almora'), 'declined_no_phc', 71),
  ((SELECT id FROM migration_surveys WHERE survey_key = 'round-2018'), (SELECT id FROM areas WHERE type = 'district' AND slug = 'almora'), 'declined_no_power', 11),
  ((SELECT id FROM migration_surveys WHERE survey_key = 'round-2018'), (SELECT id FROM areas WHERE type = 'district' AND slug = 'almora'), 'declined_no_road', 63),
  ((SELECT id FROM migration_surveys WHERE survey_key = 'round-2018'), (SELECT id FROM areas WHERE type = 'district' AND slug = 'almora'), 'declined_no_water', 34),
  ((SELECT id FROM migration_surveys WHERE survey_key = 'round-2018'), (SELECT id FROM areas WHERE type = 'district' AND slug = 'almora'), 'declined_over_half', 80),
  ((SELECT id FROM migration_surveys WHERE survey_key = 'round-2018'), (SELECT id FROM areas WHERE type = 'district' AND slug = 'almora'), 'depopulated_after_2011', 57),
  ((SELECT id FROM migration_surveys WHERE survey_key = 'round-2018'), (SELECT id FROM areas WHERE type = 'district' AND slug = 'almora'), 'depopulated_no_phc', 53),
  ((SELECT id FROM migration_surveys WHERE survey_key = 'round-2018'), (SELECT id FROM areas WHERE type = 'district' AND slug = 'almora'), 'depopulated_no_power', 21),
  ((SELECT id FROM migration_surveys WHERE survey_key = 'round-2018'), (SELECT id FROM areas WHERE type = 'district' AND slug = 'almora'), 'depopulated_no_road', 42),
  ((SELECT id FROM migration_surveys WHERE survey_key = 'round-2018'), (SELECT id FROM areas WHERE type = 'district' AND slug = 'almora'), 'depopulated_no_water', 30),
  ((SELECT id FROM migration_surveys WHERE survey_key = 'round-2018'), (SELECT id FROM areas WHERE type = 'district' AND slug = 'almora'), 'inward_migration', 39),
  ((SELECT id FROM migration_surveys WHERE survey_key = 'round-2018'), (SELECT id FROM areas WHERE type = 'district' AND slug = 'bageshwar'), 'declined_no_phc', 35),
  ((SELECT id FROM migration_surveys WHERE survey_key = 'round-2018'), (SELECT id FROM areas WHERE type = 'district' AND slug = 'bageshwar'), 'declined_no_power', 3),
  ((SELECT id FROM migration_surveys WHERE survey_key = 'round-2018'), (SELECT id FROM areas WHERE type = 'district' AND slug = 'bageshwar'), 'declined_no_road', 19),
  ((SELECT id FROM migration_surveys WHERE survey_key = 'round-2018'), (SELECT id FROM areas WHERE type = 'district' AND slug = 'bageshwar'), 'declined_no_water', 15),
  ((SELECT id FROM migration_surveys WHERE survey_key = 'round-2018'), (SELECT id FROM areas WHERE type = 'district' AND slug = 'bageshwar'), 'declined_over_half', 37),
  ((SELECT id FROM migration_surveys WHERE survey_key = 'round-2018'), (SELECT id FROM areas WHERE type = 'district' AND slug = 'bageshwar'), 'depopulated_after_2011', 77),
  ((SELECT id FROM migration_surveys WHERE survey_key = 'round-2018'), (SELECT id FROM areas WHERE type = 'district' AND slug = 'bageshwar'), 'depopulated_no_phc', 62),
  ((SELECT id FROM migration_surveys WHERE survey_key = 'round-2018'), (SELECT id FROM areas WHERE type = 'district' AND slug = 'bageshwar'), 'depopulated_no_power', 27),
  ((SELECT id FROM migration_surveys WHERE survey_key = 'round-2018'), (SELECT id FROM areas WHERE type = 'district' AND slug = 'bageshwar'), 'depopulated_no_road', 39),
  ((SELECT id FROM migration_surveys WHERE survey_key = 'round-2018'), (SELECT id FROM areas WHERE type = 'district' AND slug = 'bageshwar'), 'depopulated_no_water', 49),
  ((SELECT id FROM migration_surveys WHERE survey_key = 'round-2018'), (SELECT id FROM areas WHERE type = 'district' AND slug = 'bageshwar'), 'inward_migration', 24),
  ((SELECT id FROM migration_surveys WHERE survey_key = 'round-2018'), (SELECT id FROM areas WHERE type = 'district' AND slug = 'chamoli'), 'declined_no_phc', 14),
  ((SELECT id FROM migration_surveys WHERE survey_key = 'round-2018'), (SELECT id FROM areas WHERE type = 'district' AND slug = 'chamoli'), 'declined_no_power', 4),
  ((SELECT id FROM migration_surveys WHERE survey_key = 'round-2018'), (SELECT id FROM areas WHERE type = 'district' AND slug = 'chamoli'), 'declined_no_road', 18),
  ((SELECT id FROM migration_surveys WHERE survey_key = 'round-2018'), (SELECT id FROM areas WHERE type = 'district' AND slug = 'chamoli'), 'declined_no_water', 7),
  ((SELECT id FROM migration_surveys WHERE survey_key = 'round-2018'), (SELECT id FROM areas WHERE type = 'district' AND slug = 'chamoli'), 'declined_over_half', 18),
  ((SELECT id FROM migration_surveys WHERE survey_key = 'round-2018'), (SELECT id FROM areas WHERE type = 'district' AND slug = 'chamoli'), 'depopulated_after_2011', 41),
  ((SELECT id FROM migration_surveys WHERE survey_key = 'round-2018'), (SELECT id FROM areas WHERE type = 'district' AND slug = 'chamoli'), 'depopulated_near_border', 1),
  ((SELECT id FROM migration_surveys WHERE survey_key = 'round-2018'), (SELECT id FROM areas WHERE type = 'district' AND slug = 'chamoli'), 'depopulated_no_phc', 41),
  ((SELECT id FROM migration_surveys WHERE survey_key = 'round-2018'), (SELECT id FROM areas WHERE type = 'district' AND slug = 'chamoli'), 'depopulated_no_power', 35),
  ((SELECT id FROM migration_surveys WHERE survey_key = 'round-2018'), (SELECT id FROM areas WHERE type = 'district' AND slug = 'chamoli'), 'depopulated_no_road', 33),
  ((SELECT id FROM migration_surveys WHERE survey_key = 'round-2018'), (SELECT id FROM areas WHERE type = 'district' AND slug = 'chamoli'), 'depopulated_no_water', 26),
  ((SELECT id FROM migration_surveys WHERE survey_key = 'round-2018'), (SELECT id FROM areas WHERE type = 'district' AND slug = 'chamoli'), 'inward_migration', 26),
  ((SELECT id FROM migration_surveys WHERE survey_key = 'round-2018'), (SELECT id FROM areas WHERE type = 'district' AND slug = 'champawat'), 'declined_near_border', 4),
  ((SELECT id FROM migration_surveys WHERE survey_key = 'round-2018'), (SELECT id FROM areas WHERE type = 'district' AND slug = 'champawat'), 'declined_no_phc', 37),
  ((SELECT id FROM migration_surveys WHERE survey_key = 'round-2018'), (SELECT id FROM areas WHERE type = 'district' AND slug = 'champawat'), 'declined_no_power', 16),
  ((SELECT id FROM migration_surveys WHERE survey_key = 'round-2018'), (SELECT id FROM areas WHERE type = 'district' AND slug = 'champawat'), 'declined_no_road', 38),
  ((SELECT id FROM migration_surveys WHERE survey_key = 'round-2018'), (SELECT id FROM areas WHERE type = 'district' AND slug = 'champawat'), 'declined_no_water', 11),
  ((SELECT id FROM migration_surveys WHERE survey_key = 'round-2018'), (SELECT id FROM areas WHERE type = 'district' AND slug = 'champawat'), 'declined_over_half', 44),
  ((SELECT id FROM migration_surveys WHERE survey_key = 'round-2018'), (SELECT id FROM areas WHERE type = 'district' AND slug = 'champawat'), 'depopulated_after_2011', 64),
  ((SELECT id FROM migration_surveys WHERE survey_key = 'round-2018'), (SELECT id FROM areas WHERE type = 'district' AND slug = 'champawat'), 'depopulated_near_border', 5),
  ((SELECT id FROM migration_surveys WHERE survey_key = 'round-2018'), (SELECT id FROM areas WHERE type = 'district' AND slug = 'champawat'), 'depopulated_no_phc', 61),
  ((SELECT id FROM migration_surveys WHERE survey_key = 'round-2018'), (SELECT id FROM areas WHERE type = 'district' AND slug = 'champawat'), 'depopulated_no_power', 43),
  ((SELECT id FROM migration_surveys WHERE survey_key = 'round-2018'), (SELECT id FROM areas WHERE type = 'district' AND slug = 'champawat'), 'depopulated_no_road', 56),
  ((SELECT id FROM migration_surveys WHERE survey_key = 'round-2018'), (SELECT id FROM areas WHERE type = 'district' AND slug = 'champawat'), 'depopulated_no_water', 32),
  ((SELECT id FROM migration_surveys WHERE survey_key = 'round-2018'), (SELECT id FROM areas WHERE type = 'district' AND slug = 'champawat'), 'inward_migration', 60),
  ((SELECT id FROM migration_surveys WHERE survey_key = 'round-2018'), (SELECT id FROM areas WHERE type = 'district' AND slug = 'dehradun'), 'declined_no_phc', 40),
  ((SELECT id FROM migration_surveys WHERE survey_key = 'round-2018'), (SELECT id FROM areas WHERE type = 'district' AND slug = 'dehradun'), 'declined_no_power', 3),
  ((SELECT id FROM migration_surveys WHERE survey_key = 'round-2018'), (SELECT id FROM areas WHERE type = 'district' AND slug = 'dehradun'), 'declined_no_road', 32),
  ((SELECT id FROM migration_surveys WHERE survey_key = 'round-2018'), (SELECT id FROM areas WHERE type = 'district' AND slug = 'dehradun'), 'declined_no_water', 4),
  ((SELECT id FROM migration_surveys WHERE survey_key = 'round-2018'), (SELECT id FROM areas WHERE type = 'district' AND slug = 'dehradun'), 'declined_over_half', 42),
  ((SELECT id FROM migration_surveys WHERE survey_key = 'round-2018'), (SELECT id FROM areas WHERE type = 'district' AND slug = 'dehradun'), 'depopulated_after_2011', 7),
  ((SELECT id FROM migration_surveys WHERE survey_key = 'round-2018'), (SELECT id FROM areas WHERE type = 'district' AND slug = 'dehradun'), 'depopulated_no_phc', 7),
  ((SELECT id FROM migration_surveys WHERE survey_key = 'round-2018'), (SELECT id FROM areas WHERE type = 'district' AND slug = 'dehradun'), 'depopulated_no_power', 5),
  ((SELECT id FROM migration_surveys WHERE survey_key = 'round-2018'), (SELECT id FROM areas WHERE type = 'district' AND slug = 'dehradun'), 'depopulated_no_road', 3),
  ((SELECT id FROM migration_surveys WHERE survey_key = 'round-2018'), (SELECT id FROM areas WHERE type = 'district' AND slug = 'dehradun'), 'depopulated_no_water', 5),
  ((SELECT id FROM migration_surveys WHERE survey_key = 'round-2018'), (SELECT id FROM areas WHERE type = 'district' AND slug = 'dehradun'), 'inward_migration', 114),
  ((SELECT id FROM migration_surveys WHERE survey_key = 'round-2018'), (SELECT id FROM areas WHERE type = 'district' AND slug = 'haridwar'), 'declined_no_phc', 5),
  ((SELECT id FROM migration_surveys WHERE survey_key = 'round-2018'), (SELECT id FROM areas WHERE type = 'district' AND slug = 'haridwar'), 'declined_no_power', 4),
  ((SELECT id FROM migration_surveys WHERE survey_key = 'round-2018'), (SELECT id FROM areas WHERE type = 'district' AND slug = 'haridwar'), 'declined_no_road', 2),
  ((SELECT id FROM migration_surveys WHERE survey_key = 'round-2018'), (SELECT id FROM areas WHERE type = 'district' AND slug = 'haridwar'), 'declined_no_water', 4),
  ((SELECT id FROM migration_surveys WHERE survey_key = 'round-2018'), (SELECT id FROM areas WHERE type = 'district' AND slug = 'haridwar'), 'declined_over_half', 7),
  ((SELECT id FROM migration_surveys WHERE survey_key = 'round-2018'), (SELECT id FROM areas WHERE type = 'district' AND slug = 'haridwar'), 'depopulated_after_2011', 38),
  ((SELECT id FROM migration_surveys WHERE survey_key = 'round-2018'), (SELECT id FROM areas WHERE type = 'district' AND slug = 'haridwar'), 'depopulated_no_phc', 28),
  ((SELECT id FROM migration_surveys WHERE survey_key = 'round-2018'), (SELECT id FROM areas WHERE type = 'district' AND slug = 'haridwar'), 'depopulated_no_power', 20),
  ((SELECT id FROM migration_surveys WHERE survey_key = 'round-2018'), (SELECT id FROM areas WHERE type = 'district' AND slug = 'haridwar'), 'depopulated_no_road', 15),
  ((SELECT id FROM migration_surveys WHERE survey_key = 'round-2018'), (SELECT id FROM areas WHERE type = 'district' AND slug = 'haridwar'), 'depopulated_no_water', 20),
  ((SELECT id FROM migration_surveys WHERE survey_key = 'round-2018'), (SELECT id FROM areas WHERE type = 'district' AND slug = 'haridwar'), 'inward_migration', 121),
  ((SELECT id FROM migration_surveys WHERE survey_key = 'round-2018'), (SELECT id FROM areas WHERE type = 'district' AND slug = 'nainital'), 'declined_no_phc', 12),
  ((SELECT id FROM migration_surveys WHERE survey_key = 'round-2018'), (SELECT id FROM areas WHERE type = 'district' AND slug = 'nainital'), 'declined_no_power', 2),
  ((SELECT id FROM migration_surveys WHERE survey_key = 'round-2018'), (SELECT id FROM areas WHERE type = 'district' AND slug = 'nainital'), 'declined_no_road', 7),
  ((SELECT id FROM migration_surveys WHERE survey_key = 'round-2018'), (SELECT id FROM areas WHERE type = 'district' AND slug = 'nainital'), 'declined_no_water', 3),
  ((SELECT id FROM migration_surveys WHERE survey_key = 'round-2018'), (SELECT id FROM areas WHERE type = 'district' AND slug = 'nainital'), 'declined_over_half', 14),
  ((SELECT id FROM migration_surveys WHERE survey_key = 'round-2018'), (SELECT id FROM areas WHERE type = 'district' AND slug = 'nainital'), 'depopulated_after_2011', 22),
  ((SELECT id FROM migration_surveys WHERE survey_key = 'round-2018'), (SELECT id FROM areas WHERE type = 'district' AND slug = 'nainital'), 'depopulated_no_phc', 20),
  ((SELECT id FROM migration_surveys WHERE survey_key = 'round-2018'), (SELECT id FROM areas WHERE type = 'district' AND slug = 'nainital'), 'depopulated_no_power', 10),
  ((SELECT id FROM migration_surveys WHERE survey_key = 'round-2018'), (SELECT id FROM areas WHERE type = 'district' AND slug = 'nainital'), 'depopulated_no_road', 15),
  ((SELECT id FROM migration_surveys WHERE survey_key = 'round-2018'), (SELECT id FROM areas WHERE type = 'district' AND slug = 'nainital'), 'depopulated_no_water', 10),
  ((SELECT id FROM migration_surveys WHERE survey_key = 'round-2018'), (SELECT id FROM areas WHERE type = 'district' AND slug = 'nainital'), 'inward_migration', 139),
  ((SELECT id FROM migration_surveys WHERE survey_key = 'round-2018'), (SELECT id FROM areas WHERE type = 'district' AND slug = 'pauri-garhwal'), 'declined_no_phc', 106),
  ((SELECT id FROM migration_surveys WHERE survey_key = 'round-2018'), (SELECT id FROM areas WHERE type = 'district' AND slug = 'pauri-garhwal'), 'declined_no_power', 17),
  ((SELECT id FROM migration_surveys WHERE survey_key = 'round-2018'), (SELECT id FROM areas WHERE type = 'district' AND slug = 'pauri-garhwal'), 'declined_no_road', 75),
  ((SELECT id FROM migration_surveys WHERE survey_key = 'round-2018'), (SELECT id FROM areas WHERE type = 'district' AND slug = 'pauri-garhwal'), 'declined_no_water', 39),
  ((SELECT id FROM migration_surveys WHERE survey_key = 'round-2018'), (SELECT id FROM areas WHERE type = 'district' AND slug = 'pauri-garhwal'), 'declined_over_half', 112),
  ((SELECT id FROM migration_surveys WHERE survey_key = 'round-2018'), (SELECT id FROM areas WHERE type = 'district' AND slug = 'pauri-garhwal'), 'depopulated_after_2011', 186),
  ((SELECT id FROM migration_surveys WHERE survey_key = 'round-2018'), (SELECT id FROM areas WHERE type = 'district' AND slug = 'pauri-garhwal'), 'depopulated_no_phc', 164),
  ((SELECT id FROM migration_surveys WHERE survey_key = 'round-2018'), (SELECT id FROM areas WHERE type = 'district' AND slug = 'pauri-garhwal'), 'depopulated_no_power', 84),
  ((SELECT id FROM migration_surveys WHERE survey_key = 'round-2018'), (SELECT id FROM areas WHERE type = 'district' AND slug = 'pauri-garhwal'), 'depopulated_no_road', 126),
  ((SELECT id FROM migration_surveys WHERE survey_key = 'round-2018'), (SELECT id FROM areas WHERE type = 'district' AND slug = 'pauri-garhwal'), 'depopulated_no_water', 97),
  ((SELECT id FROM migration_surveys WHERE survey_key = 'round-2018'), (SELECT id FROM areas WHERE type = 'district' AND slug = 'pauri-garhwal'), 'inward_migration', 46),
  ((SELECT id FROM migration_surveys WHERE survey_key = 'round-2018'), (SELECT id FROM areas WHERE type = 'district' AND slug = 'pithoragarh'), 'declined_near_border', 2),
  ((SELECT id FROM migration_surveys WHERE survey_key = 'round-2018'), (SELECT id FROM areas WHERE type = 'district' AND slug = 'pithoragarh'), 'declined_no_phc', 43),
  ((SELECT id FROM migration_surveys WHERE survey_key = 'round-2018'), (SELECT id FROM areas WHERE type = 'district' AND slug = 'pithoragarh'), 'declined_no_power', 26),
  ((SELECT id FROM migration_surveys WHERE survey_key = 'round-2018'), (SELECT id FROM areas WHERE type = 'district' AND slug = 'pithoragarh'), 'declined_no_road', 23),
  ((SELECT id FROM migration_surveys WHERE survey_key = 'round-2018'), (SELECT id FROM areas WHERE type = 'district' AND slug = 'pithoragarh'), 'declined_no_water', 25),
  ((SELECT id FROM migration_surveys WHERE survey_key = 'round-2018'), (SELECT id FROM areas WHERE type = 'district' AND slug = 'pithoragarh'), 'declined_over_half', 45),
  ((SELECT id FROM migration_surveys WHERE survey_key = 'round-2018'), (SELECT id FROM areas WHERE type = 'district' AND slug = 'pithoragarh'), 'depopulated_after_2011', 75),
  ((SELECT id FROM migration_surveys WHERE survey_key = 'round-2018'), (SELECT id FROM areas WHERE type = 'district' AND slug = 'pithoragarh'), 'depopulated_near_border', 8),
  ((SELECT id FROM migration_surveys WHERE survey_key = 'round-2018'), (SELECT id FROM areas WHERE type = 'district' AND slug = 'pithoragarh'), 'depopulated_no_phc', 74),
  ((SELECT id FROM migration_surveys WHERE survey_key = 'round-2018'), (SELECT id FROM areas WHERE type = 'district' AND slug = 'pithoragarh'), 'depopulated_no_power', 53),
  ((SELECT id FROM migration_surveys WHERE survey_key = 'round-2018'), (SELECT id FROM areas WHERE type = 'district' AND slug = 'pithoragarh'), 'depopulated_no_road', 44),
  ((SELECT id FROM migration_surveys WHERE survey_key = 'round-2018'), (SELECT id FROM areas WHERE type = 'district' AND slug = 'pithoragarh'), 'depopulated_no_water', 45),
  ((SELECT id FROM migration_surveys WHERE survey_key = 'round-2018'), (SELECT id FROM areas WHERE type = 'district' AND slug = 'pithoragarh'), 'inward_migration', 69),
  ((SELECT id FROM migration_surveys WHERE survey_key = 'round-2018'), (SELECT id FROM areas WHERE type = 'district' AND slug = 'rudraprayag'), 'declined_no_phc', 19),
  ((SELECT id FROM migration_surveys WHERE survey_key = 'round-2018'), (SELECT id FROM areas WHERE type = 'district' AND slug = 'rudraprayag'), 'declined_no_power', 5),
  ((SELECT id FROM migration_surveys WHERE survey_key = 'round-2018'), (SELECT id FROM areas WHERE type = 'district' AND slug = 'rudraprayag'), 'declined_no_road', 18),
  ((SELECT id FROM migration_surveys WHERE survey_key = 'round-2018'), (SELECT id FROM areas WHERE type = 'district' AND slug = 'rudraprayag'), 'declined_no_water', 6),
  ((SELECT id FROM migration_surveys WHERE survey_key = 'round-2018'), (SELECT id FROM areas WHERE type = 'district' AND slug = 'rudraprayag'), 'declined_over_half', 23),
  ((SELECT id FROM migration_surveys WHERE survey_key = 'round-2018'), (SELECT id FROM areas WHERE type = 'district' AND slug = 'rudraprayag'), 'depopulated_after_2011', 20),
  ((SELECT id FROM migration_surveys WHERE survey_key = 'round-2018'), (SELECT id FROM areas WHERE type = 'district' AND slug = 'rudraprayag'), 'depopulated_no_phc', 17),
  ((SELECT id FROM migration_surveys WHERE survey_key = 'round-2018'), (SELECT id FROM areas WHERE type = 'district' AND slug = 'rudraprayag'), 'depopulated_no_power', 5),
  ((SELECT id FROM migration_surveys WHERE survey_key = 'round-2018'), (SELECT id FROM areas WHERE type = 'district' AND slug = 'rudraprayag'), 'depopulated_no_road', 14),
  ((SELECT id FROM migration_surveys WHERE survey_key = 'round-2018'), (SELECT id FROM areas WHERE type = 'district' AND slug = 'rudraprayag'), 'depopulated_no_water', 7),
  ((SELECT id FROM migration_surveys WHERE survey_key = 'round-2018'), (SELECT id FROM areas WHERE type = 'district' AND slug = 'rudraprayag'), 'inward_migration', 28),
  ((SELECT id FROM migration_surveys WHERE survey_key = 'round-2018'), (SELECT id FROM areas WHERE type = 'district' AND slug = 'tehri-garhwal'), 'declined_no_phc', 70),
  ((SELECT id FROM migration_surveys WHERE survey_key = 'round-2018'), (SELECT id FROM areas WHERE type = 'district' AND slug = 'tehri-garhwal'), 'declined_no_power', 10),
  ((SELECT id FROM migration_surveys WHERE survey_key = 'round-2018'), (SELECT id FROM areas WHERE type = 'district' AND slug = 'tehri-garhwal'), 'declined_no_road', 36),
  ((SELECT id FROM migration_surveys WHERE survey_key = 'round-2018'), (SELECT id FROM areas WHERE type = 'district' AND slug = 'tehri-garhwal'), 'declined_no_water', 17),
  ((SELECT id FROM migration_surveys WHERE survey_key = 'round-2018'), (SELECT id FROM areas WHERE type = 'district' AND slug = 'tehri-garhwal'), 'declined_over_half', 71),
  ((SELECT id FROM migration_surveys WHERE survey_key = 'round-2018'), (SELECT id FROM areas WHERE type = 'district' AND slug = 'tehri-garhwal'), 'depopulated_after_2011', 58),
  ((SELECT id FROM migration_surveys WHERE survey_key = 'round-2018'), (SELECT id FROM areas WHERE type = 'district' AND slug = 'tehri-garhwal'), 'depopulated_no_phc', 58),
  ((SELECT id FROM migration_surveys WHERE survey_key = 'round-2018'), (SELECT id FROM areas WHERE type = 'district' AND slug = 'tehri-garhwal'), 'depopulated_no_power', 33),
  ((SELECT id FROM migration_surveys WHERE survey_key = 'round-2018'), (SELECT id FROM areas WHERE type = 'district' AND slug = 'tehri-garhwal'), 'depopulated_no_road', 44),
  ((SELECT id FROM migration_surveys WHERE survey_key = 'round-2018'), (SELECT id FROM areas WHERE type = 'district' AND slug = 'tehri-garhwal'), 'depopulated_no_water', 33),
  ((SELECT id FROM migration_surveys WHERE survey_key = 'round-2018'), (SELECT id FROM areas WHERE type = 'district' AND slug = 'tehri-garhwal'), 'inward_migration', 76),
  ((SELECT id FROM migration_surveys WHERE survey_key = 'round-2018'), (SELECT id FROM areas WHERE type = 'district' AND slug = 'udham-singh-nagar'), 'declined_no_phc', 9),
  ((SELECT id FROM migration_surveys WHERE survey_key = 'round-2018'), (SELECT id FROM areas WHERE type = 'district' AND slug = 'udham-singh-nagar'), 'declined_no_power', 1),
  ((SELECT id FROM migration_surveys WHERE survey_key = 'round-2018'), (SELECT id FROM areas WHERE type = 'district' AND slug = 'udham-singh-nagar'), 'declined_no_road', 4),
  ((SELECT id FROM migration_surveys WHERE survey_key = 'round-2018'), (SELECT id FROM areas WHERE type = 'district' AND slug = 'udham-singh-nagar'), 'declined_no_water', 5),
  ((SELECT id FROM migration_surveys WHERE survey_key = 'round-2018'), (SELECT id FROM areas WHERE type = 'district' AND slug = 'udham-singh-nagar'), 'declined_over_half', 9),
  ((SELECT id FROM migration_surveys WHERE survey_key = 'round-2018'), (SELECT id FROM areas WHERE type = 'district' AND slug = 'udham-singh-nagar'), 'depopulated_after_2011', 19),
  ((SELECT id FROM migration_surveys WHERE survey_key = 'round-2018'), (SELECT id FROM areas WHERE type = 'district' AND slug = 'udham-singh-nagar'), 'depopulated_no_phc', 19),
  ((SELECT id FROM migration_surveys WHERE survey_key = 'round-2018'), (SELECT id FROM areas WHERE type = 'district' AND slug = 'udham-singh-nagar'), 'depopulated_no_power', 5),
  ((SELECT id FROM migration_surveys WHERE survey_key = 'round-2018'), (SELECT id FROM areas WHERE type = 'district' AND slug = 'udham-singh-nagar'), 'depopulated_no_road', 13),
  ((SELECT id FROM migration_surveys WHERE survey_key = 'round-2018'), (SELECT id FROM areas WHERE type = 'district' AND slug = 'udham-singh-nagar'), 'depopulated_no_water', 15),
  ((SELECT id FROM migration_surveys WHERE survey_key = 'round-2018'), (SELECT id FROM areas WHERE type = 'district' AND slug = 'udham-singh-nagar'), 'inward_migration', 92),
  ((SELECT id FROM migration_surveys WHERE survey_key = 'round-2018'), (SELECT id FROM areas WHERE type = 'district' AND slug = 'uttarkashi'), 'declined_no_phc', 49),
  ((SELECT id FROM migration_surveys WHERE survey_key = 'round-2018'), (SELECT id FROM areas WHERE type = 'district' AND slug = 'uttarkashi'), 'declined_no_power', 17),
  ((SELECT id FROM migration_surveys WHERE survey_key = 'round-2018'), (SELECT id FROM areas WHERE type = 'district' AND slug = 'uttarkashi'), 'declined_no_road', 32),
  ((SELECT id FROM migration_surveys WHERE survey_key = 'round-2018'), (SELECT id FROM areas WHERE type = 'district' AND slug = 'uttarkashi'), 'declined_no_water', 33),
  ((SELECT id FROM migration_surveys WHERE survey_key = 'round-2018'), (SELECT id FROM areas WHERE type = 'district' AND slug = 'uttarkashi'), 'declined_over_half', 63),
  ((SELECT id FROM migration_surveys WHERE survey_key = 'round-2018'), (SELECT id FROM areas WHERE type = 'district' AND slug = 'uttarkashi'), 'depopulated_after_2011', 70),
  ((SELECT id FROM migration_surveys WHERE survey_key = 'round-2018'), (SELECT id FROM areas WHERE type = 'district' AND slug = 'uttarkashi'), 'depopulated_no_phc', 56),
  ((SELECT id FROM migration_surveys WHERE survey_key = 'round-2018'), (SELECT id FROM areas WHERE type = 'district' AND slug = 'uttarkashi'), 'depopulated_no_power', 17),
  ((SELECT id FROM migration_surveys WHERE survey_key = 'round-2018'), (SELECT id FROM areas WHERE type = 'district' AND slug = 'uttarkashi'), 'depopulated_no_road', 38),
  ((SELECT id FROM migration_surveys WHERE survey_key = 'round-2018'), (SELECT id FROM areas WHERE type = 'district' AND slug = 'uttarkashi'), 'depopulated_no_water', 30),
  ((SELECT id FROM migration_surveys WHERE survey_key = 'round-2018'), (SELECT id FROM areas WHERE type = 'district' AND slug = 'uttarkashi'), 'inward_migration', 16)
ON CONFLICT (survey_id, area_id, category_key) DO UPDATE SET value = EXCLUDED.value;

-- ROLLBACK
-- DELETE FROM migration_observations;
-- DELETE FROM migration_district_figures;
-- DELETE FROM migration_categories;
-- DELETE FROM migration_surveys;
-- DELETE FROM sources WHERE source_key = 'uk-migration-commission';
