-- 041 — the catalogue entries and values for 040's sources.
--
-- Separate from 040 because Postgres will not let a transaction use an enum label that the
-- same transaction added, and the migration runner sends each file as one transaction. The
-- `development` and `tourism` categories are therefore declared there and used here.
--
-- Every figure below was checked against a total the report states for itself. The tourism
-- capacity columns sum to 7,622 units and 188,999 beds; the pilgrim arrivals to 3,477,957
-- for 2019. The composite index has no published column total to check against, so all
-- thirteen districts were transcribed for all six years and the ranks verified to run 1-10
-- within each year -- a mistyped rank would break that and a mistyped score would not, which
-- is why the rank column is the one worth checking.

INSERT INTO indicators (indicator_key, category, scope, label_en, label_hi, unit, decimals, higher_is_better)
VALUES
  ('sdg_composite_score', 'development', 'district', 'SDG Composite Score', 'एस.डी.जी. कम्पोजिट स्कोर', 'index', 0, TRUE),
  ('sdg_composite_rank', 'development', 'district', 'SDG Composite Rank', 'एस.डी.जी. कम्पोजिट रैंक', 'rank', 0, FALSE),
  ('tourist_accommodation_units', 'tourism', 'district', 'Hotels, Lodges and Homestays', 'होटल, लॉज व होम-स्टे', 'count', 0, TRUE),
  ('tourist_accommodation_beds', 'tourism', 'district', 'Beds in Hotels and Homestays', 'होटल व होम-स्टे में शय्या', 'count', 0, TRUE),
  ('pilgrim_shelter_capacity', 'tourism', 'district', 'Dharamshala and Ashram Capacity', 'धर्मशाला व आश्रम क्षमता', 'count', 0, TRUE),
  ('govt_accommodation_beds', 'tourism', 'district', 'Beds in Government Rest Houses', 'सरकारी विश्राम गृहों में शय्या', 'count', 0, TRUE),
  ('hospital_beds', 'health', 'district', 'Hospital Beds', 'अस्पताल में शय्या', 'count', 0, TRUE),
  ('char_dham_pilgrims', 'tourism', 'state', 'Char Dham and Hemkund Pilgrims', 'चार धाम व हेमकुण्ड यात्री', 'count', 0, NULL)
ON CONFLICT (indicator_key) DO UPDATE SET
  category         = EXCLUDED.category,
  scope            = EXCLUDED.scope,
  label_en         = EXCLUDED.label_en,
  label_hi         = EXCLUDED.label_hi,
  unit             = EXCLUDED.unit,
  decimals         = EXCLUDED.decimals,
  higher_is_better = EXCLUDED.higher_is_better;

INSERT INTO indicator_values (indicator_key, area_id, vintage, value, source_id, fetched_at)
VALUES
  ('sdg_composite_score', (SELECT id FROM areas WHERE type = 'district' AND slug = 'almora'), DATE '2016-03-31', 64, (SELECT id FROM sources WHERE source_key = 'uk-district-composite-index'), (now() AT TIME ZONE 'utc')),
  ('sdg_composite_rank', (SELECT id FROM areas WHERE type = 'district' AND slug = 'almora'), DATE '2016-03-31', 4, (SELECT id FROM sources WHERE source_key = 'uk-district-composite-index'), (now() AT TIME ZONE 'utc')),
  ('sdg_composite_score', (SELECT id FROM areas WHERE type = 'district' AND slug = 'almora'), DATE '2017-03-31', 68, (SELECT id FROM sources WHERE source_key = 'uk-district-composite-index'), (now() AT TIME ZONE 'utc')),
  ('sdg_composite_rank', (SELECT id FROM areas WHERE type = 'district' AND slug = 'almora'), DATE '2017-03-31', 4, (SELECT id FROM sources WHERE source_key = 'uk-district-composite-index'), (now() AT TIME ZONE 'utc')),
  ('sdg_composite_score', (SELECT id FROM areas WHERE type = 'district' AND slug = 'almora'), DATE '2018-03-31', 64, (SELECT id FROM sources WHERE source_key = 'uk-district-composite-index'), (now() AT TIME ZONE 'utc')),
  ('sdg_composite_rank', (SELECT id FROM areas WHERE type = 'district' AND slug = 'almora'), DATE '2018-03-31', 4, (SELECT id FROM sources WHERE source_key = 'uk-district-composite-index'), (now() AT TIME ZONE 'utc')),
  ('sdg_composite_score', (SELECT id FROM areas WHERE type = 'district' AND slug = 'almora'), DATE '2019-03-31', 62, (SELECT id FROM sources WHERE source_key = 'uk-district-composite-index'), (now() AT TIME ZONE 'utc')),
  ('sdg_composite_rank', (SELECT id FROM areas WHERE type = 'district' AND slug = 'almora'), DATE '2019-03-31', 3, (SELECT id FROM sources WHERE source_key = 'uk-district-composite-index'), (now() AT TIME ZONE 'utc')),
  ('sdg_composite_score', (SELECT id FROM areas WHERE type = 'district' AND slug = 'almora'), DATE '2020-03-31', 64, (SELECT id FROM sources WHERE source_key = 'uk-district-composite-index'), (now() AT TIME ZONE 'utc')),
  ('sdg_composite_rank', (SELECT id FROM areas WHERE type = 'district' AND slug = 'almora'), DATE '2020-03-31', 5, (SELECT id FROM sources WHERE source_key = 'uk-district-composite-index'), (now() AT TIME ZONE 'utc')),
  ('sdg_composite_score', (SELECT id FROM areas WHERE type = 'district' AND slug = 'almora'), DATE '2021-03-31', 66, (SELECT id FROM sources WHERE source_key = 'uk-district-composite-index'), (now() AT TIME ZONE 'utc')),
  ('sdg_composite_rank', (SELECT id FROM areas WHERE type = 'district' AND slug = 'almora'), DATE '2021-03-31', 3, (SELECT id FROM sources WHERE source_key = 'uk-district-composite-index'), (now() AT TIME ZONE 'utc')),
  ('sdg_composite_score', (SELECT id FROM areas WHERE type = 'district' AND slug = 'bageshwar'), DATE '2016-03-31', 64, (SELECT id FROM sources WHERE source_key = 'uk-district-composite-index'), (now() AT TIME ZONE 'utc')),
  ('sdg_composite_rank', (SELECT id FROM areas WHERE type = 'district' AND slug = 'bageshwar'), DATE '2016-03-31', 4, (SELECT id FROM sources WHERE source_key = 'uk-district-composite-index'), (now() AT TIME ZONE 'utc')),
  ('sdg_composite_score', (SELECT id FROM areas WHERE type = 'district' AND slug = 'bageshwar'), DATE '2017-03-31', 67, (SELECT id FROM sources WHERE source_key = 'uk-district-composite-index'), (now() AT TIME ZONE 'utc')),
  ('sdg_composite_rank', (SELECT id FROM areas WHERE type = 'district' AND slug = 'bageshwar'), DATE '2017-03-31', 5, (SELECT id FROM sources WHERE source_key = 'uk-district-composite-index'), (now() AT TIME ZONE 'utc')),
  ('sdg_composite_score', (SELECT id FROM areas WHERE type = 'district' AND slug = 'bageshwar'), DATE '2018-03-31', 62, (SELECT id FROM sources WHERE source_key = 'uk-district-composite-index'), (now() AT TIME ZONE 'utc')),
  ('sdg_composite_rank', (SELECT id FROM areas WHERE type = 'district' AND slug = 'bageshwar'), DATE '2018-03-31', 6, (SELECT id FROM sources WHERE source_key = 'uk-district-composite-index'), (now() AT TIME ZONE 'utc')),
  ('sdg_composite_score', (SELECT id FROM areas WHERE type = 'district' AND slug = 'bageshwar'), DATE '2019-03-31', 61, (SELECT id FROM sources WHERE source_key = 'uk-district-composite-index'), (now() AT TIME ZONE 'utc')),
  ('sdg_composite_rank', (SELECT id FROM areas WHERE type = 'district' AND slug = 'bageshwar'), DATE '2019-03-31', 4, (SELECT id FROM sources WHERE source_key = 'uk-district-composite-index'), (now() AT TIME ZONE 'utc')),
  ('sdg_composite_score', (SELECT id FROM areas WHERE type = 'district' AND slug = 'bageshwar'), DATE '2020-03-31', 67, (SELECT id FROM sources WHERE source_key = 'uk-district-composite-index'), (now() AT TIME ZONE 'utc')),
  ('sdg_composite_rank', (SELECT id FROM areas WHERE type = 'district' AND slug = 'bageshwar'), DATE '2020-03-31', 3, (SELECT id FROM sources WHERE source_key = 'uk-district-composite-index'), (now() AT TIME ZONE 'utc')),
  ('sdg_composite_score', (SELECT id FROM areas WHERE type = 'district' AND slug = 'bageshwar'), DATE '2021-03-31', 69, (SELECT id FROM sources WHERE source_key = 'uk-district-composite-index'), (now() AT TIME ZONE 'utc')),
  ('sdg_composite_rank', (SELECT id FROM areas WHERE type = 'district' AND slug = 'bageshwar'), DATE '2021-03-31', 1, (SELECT id FROM sources WHERE source_key = 'uk-district-composite-index'), (now() AT TIME ZONE 'utc')),
  ('sdg_composite_score', (SELECT id FROM areas WHERE type = 'district' AND slug = 'chamoli'), DATE '2016-03-31', 62, (SELECT id FROM sources WHERE source_key = 'uk-district-composite-index'), (now() AT TIME ZONE 'utc')),
  ('sdg_composite_rank', (SELECT id FROM areas WHERE type = 'district' AND slug = 'chamoli'), DATE '2016-03-31', 5, (SELECT id FROM sources WHERE source_key = 'uk-district-composite-index'), (now() AT TIME ZONE 'utc')),
  ('sdg_composite_score', (SELECT id FROM areas WHERE type = 'district' AND slug = 'chamoli'), DATE '2017-03-31', 69, (SELECT id FROM sources WHERE source_key = 'uk-district-composite-index'), (now() AT TIME ZONE 'utc')),
  ('sdg_composite_rank', (SELECT id FROM areas WHERE type = 'district' AND slug = 'chamoli'), DATE '2017-03-31', 3, (SELECT id FROM sources WHERE source_key = 'uk-district-composite-index'), (now() AT TIME ZONE 'utc')),
  ('sdg_composite_score', (SELECT id FROM areas WHERE type = 'district' AND slug = 'chamoli'), DATE '2018-03-31', 65, (SELECT id FROM sources WHERE source_key = 'uk-district-composite-index'), (now() AT TIME ZONE 'utc')),
  ('sdg_composite_rank', (SELECT id FROM areas WHERE type = 'district' AND slug = 'chamoli'), DATE '2018-03-31', 3, (SELECT id FROM sources WHERE source_key = 'uk-district-composite-index'), (now() AT TIME ZONE 'utc')),
  ('sdg_composite_score', (SELECT id FROM areas WHERE type = 'district' AND slug = 'chamoli'), DATE '2019-03-31', 60, (SELECT id FROM sources WHERE source_key = 'uk-district-composite-index'), (now() AT TIME ZONE 'utc')),
  ('sdg_composite_rank', (SELECT id FROM areas WHERE type = 'district' AND slug = 'chamoli'), DATE '2019-03-31', 5, (SELECT id FROM sources WHERE source_key = 'uk-district-composite-index'), (now() AT TIME ZONE 'utc')),
  ('sdg_composite_score', (SELECT id FROM areas WHERE type = 'district' AND slug = 'chamoli'), DATE '2020-03-31', 66, (SELECT id FROM sources WHERE source_key = 'uk-district-composite-index'), (now() AT TIME ZONE 'utc')),
  ('sdg_composite_rank', (SELECT id FROM areas WHERE type = 'district' AND slug = 'chamoli'), DATE '2020-03-31', 4, (SELECT id FROM sources WHERE source_key = 'uk-district-composite-index'), (now() AT TIME ZONE 'utc')),
  ('sdg_composite_score', (SELECT id FROM areas WHERE type = 'district' AND slug = 'chamoli'), DATE '2021-03-31', 66, (SELECT id FROM sources WHERE source_key = 'uk-district-composite-index'), (now() AT TIME ZONE 'utc')),
  ('sdg_composite_rank', (SELECT id FROM areas WHERE type = 'district' AND slug = 'chamoli'), DATE '2021-03-31', 3, (SELECT id FROM sources WHERE source_key = 'uk-district-composite-index'), (now() AT TIME ZONE 'utc')),
  ('sdg_composite_score', (SELECT id FROM areas WHERE type = 'district' AND slug = 'champawat'), DATE '2016-03-31', 64, (SELECT id FROM sources WHERE source_key = 'uk-district-composite-index'), (now() AT TIME ZONE 'utc')),
  ('sdg_composite_rank', (SELECT id FROM areas WHERE type = 'district' AND slug = 'champawat'), DATE '2016-03-31', 4, (SELECT id FROM sources WHERE source_key = 'uk-district-composite-index'), (now() AT TIME ZONE 'utc')),
  ('sdg_composite_score', (SELECT id FROM areas WHERE type = 'district' AND slug = 'champawat'), DATE '2017-03-31', 60, (SELECT id FROM sources WHERE source_key = 'uk-district-composite-index'), (now() AT TIME ZONE 'utc')),
  ('sdg_composite_rank', (SELECT id FROM areas WHERE type = 'district' AND slug = 'champawat'), DATE '2017-03-31', 8, (SELECT id FROM sources WHERE source_key = 'uk-district-composite-index'), (now() AT TIME ZONE 'utc')),
  ('sdg_composite_score', (SELECT id FROM areas WHERE type = 'district' AND slug = 'champawat'), DATE '2018-03-31', 59, (SELECT id FROM sources WHERE source_key = 'uk-district-composite-index'), (now() AT TIME ZONE 'utc')),
  ('sdg_composite_rank', (SELECT id FROM areas WHERE type = 'district' AND slug = 'champawat'), DATE '2018-03-31', 8, (SELECT id FROM sources WHERE source_key = 'uk-district-composite-index'), (now() AT TIME ZONE 'utc')),
  ('sdg_composite_score', (SELECT id FROM areas WHERE type = 'district' AND slug = 'champawat'), DATE '2019-03-31', 56, (SELECT id FROM sources WHERE source_key = 'uk-district-composite-index'), (now() AT TIME ZONE 'utc')),
  ('sdg_composite_rank', (SELECT id FROM areas WHERE type = 'district' AND slug = 'champawat'), DATE '2019-03-31', 7, (SELECT id FROM sources WHERE source_key = 'uk-district-composite-index'), (now() AT TIME ZONE 'utc')),
  ('sdg_composite_score', (SELECT id FROM areas WHERE type = 'district' AND slug = 'champawat'), DATE '2020-03-31', 63, (SELECT id FROM sources WHERE source_key = 'uk-district-composite-index'), (now() AT TIME ZONE 'utc')),
  ('sdg_composite_rank', (SELECT id FROM areas WHERE type = 'district' AND slug = 'champawat'), DATE '2020-03-31', 6, (SELECT id FROM sources WHERE source_key = 'uk-district-composite-index'), (now() AT TIME ZONE 'utc')),
  ('sdg_composite_score', (SELECT id FROM areas WHERE type = 'district' AND slug = 'champawat'), DATE '2021-03-31', 67, (SELECT id FROM sources WHERE source_key = 'uk-district-composite-index'), (now() AT TIME ZONE 'utc')),
  ('sdg_composite_rank', (SELECT id FROM areas WHERE type = 'district' AND slug = 'champawat'), DATE '2021-03-31', 2, (SELECT id FROM sources WHERE source_key = 'uk-district-composite-index'), (now() AT TIME ZONE 'utc')),
  ('sdg_composite_score', (SELECT id FROM areas WHERE type = 'district' AND slug = 'dehradun'), DATE '2016-03-31', 71, (SELECT id FROM sources WHERE source_key = 'uk-district-composite-index'), (now() AT TIME ZONE 'utc')),
  ('sdg_composite_rank', (SELECT id FROM areas WHERE type = 'district' AND slug = 'dehradun'), DATE '2016-03-31', 1, (SELECT id FROM sources WHERE source_key = 'uk-district-composite-index'), (now() AT TIME ZONE 'utc')),
  ('sdg_composite_score', (SELECT id FROM areas WHERE type = 'district' AND slug = 'dehradun'), DATE '2017-03-31', 70, (SELECT id FROM sources WHERE source_key = 'uk-district-composite-index'), (now() AT TIME ZONE 'utc')),
  ('sdg_composite_rank', (SELECT id FROM areas WHERE type = 'district' AND slug = 'dehradun'), DATE '2017-03-31', 2, (SELECT id FROM sources WHERE source_key = 'uk-district-composite-index'), (now() AT TIME ZONE 'utc')),
  ('sdg_composite_score', (SELECT id FROM areas WHERE type = 'district' AND slug = 'dehradun'), DATE '2018-03-31', 69, (SELECT id FROM sources WHERE source_key = 'uk-district-composite-index'), (now() AT TIME ZONE 'utc')),
  ('sdg_composite_rank', (SELECT id FROM areas WHERE type = 'district' AND slug = 'dehradun'), DATE '2018-03-31', 1, (SELECT id FROM sources WHERE source_key = 'uk-district-composite-index'), (now() AT TIME ZONE 'utc')),
  ('sdg_composite_score', (SELECT id FROM areas WHERE type = 'district' AND slug = 'dehradun'), DATE '2019-03-31', 71, (SELECT id FROM sources WHERE source_key = 'uk-district-composite-index'), (now() AT TIME ZONE 'utc')),
  ('sdg_composite_rank', (SELECT id FROM areas WHERE type = 'district' AND slug = 'dehradun'), DATE '2019-03-31', 1, (SELECT id FROM sources WHERE source_key = 'uk-district-composite-index'), (now() AT TIME ZONE 'utc')),
  ('sdg_composite_score', (SELECT id FROM areas WHERE type = 'district' AND slug = 'dehradun'), DATE '2020-03-31', 70, (SELECT id FROM sources WHERE source_key = 'uk-district-composite-index'), (now() AT TIME ZONE 'utc')),
  ('sdg_composite_rank', (SELECT id FROM areas WHERE type = 'district' AND slug = 'dehradun'), DATE '2020-03-31', 1, (SELECT id FROM sources WHERE source_key = 'uk-district-composite-index'), (now() AT TIME ZONE 'utc')),
  ('sdg_composite_score', (SELECT id FROM areas WHERE type = 'district' AND slug = 'dehradun'), DATE '2021-03-31', 67, (SELECT id FROM sources WHERE source_key = 'uk-district-composite-index'), (now() AT TIME ZONE 'utc')),
  ('sdg_composite_rank', (SELECT id FROM areas WHERE type = 'district' AND slug = 'dehradun'), DATE '2021-03-31', 2, (SELECT id FROM sources WHERE source_key = 'uk-district-composite-index'), (now() AT TIME ZONE 'utc')),
  ('sdg_composite_score', (SELECT id FROM areas WHERE type = 'district' AND slug = 'haridwar'), DATE '2016-03-31', 55, (SELECT id FROM sources WHERE source_key = 'uk-district-composite-index'), (now() AT TIME ZONE 'utc')),
  ('sdg_composite_rank', (SELECT id FROM areas WHERE type = 'district' AND slug = 'haridwar'), DATE '2016-03-31', 9, (SELECT id FROM sources WHERE source_key = 'uk-district-composite-index'), (now() AT TIME ZONE 'utc')),
  ('sdg_composite_score', (SELECT id FROM areas WHERE type = 'district' AND slug = 'haridwar'), DATE '2017-03-31', 54, (SELECT id FROM sources WHERE source_key = 'uk-district-composite-index'), (now() AT TIME ZONE 'utc')),
  ('sdg_composite_rank', (SELECT id FROM areas WHERE type = 'district' AND slug = 'haridwar'), DATE '2017-03-31', 10, (SELECT id FROM sources WHERE source_key = 'uk-district-composite-index'), (now() AT TIME ZONE 'utc')),
  ('sdg_composite_score', (SELECT id FROM areas WHERE type = 'district' AND slug = 'haridwar'), DATE '2018-03-31', 59, (SELECT id FROM sources WHERE source_key = 'uk-district-composite-index'), (now() AT TIME ZONE 'utc')),
  ('sdg_composite_rank', (SELECT id FROM areas WHERE type = 'district' AND slug = 'haridwar'), DATE '2018-03-31', 8, (SELECT id FROM sources WHERE source_key = 'uk-district-composite-index'), (now() AT TIME ZONE 'utc')),
  ('sdg_composite_score', (SELECT id FROM areas WHERE type = 'district' AND slug = 'haridwar'), DATE '2019-03-31', 59, (SELECT id FROM sources WHERE source_key = 'uk-district-composite-index'), (now() AT TIME ZONE 'utc')),
  ('sdg_composite_rank', (SELECT id FROM areas WHERE type = 'district' AND slug = 'haridwar'), DATE '2019-03-31', 6, (SELECT id FROM sources WHERE source_key = 'uk-district-composite-index'), (now() AT TIME ZONE 'utc')),
  ('sdg_composite_score', (SELECT id FROM areas WHERE type = 'district' AND slug = 'haridwar'), DATE '2020-03-31', 62, (SELECT id FROM sources WHERE source_key = 'uk-district-composite-index'), (now() AT TIME ZONE 'utc')),
  ('sdg_composite_rank', (SELECT id FROM areas WHERE type = 'district' AND slug = 'haridwar'), DATE '2020-03-31', 7, (SELECT id FROM sources WHERE source_key = 'uk-district-composite-index'), (now() AT TIME ZONE 'utc')),
  ('sdg_composite_score', (SELECT id FROM areas WHERE type = 'district' AND slug = 'haridwar'), DATE '2021-03-31', 53, (SELECT id FROM sources WHERE source_key = 'uk-district-composite-index'), (now() AT TIME ZONE 'utc')),
  ('sdg_composite_rank', (SELECT id FROM areas WHERE type = 'district' AND slug = 'haridwar'), DATE '2021-03-31', 9, (SELECT id FROM sources WHERE source_key = 'uk-district-composite-index'), (now() AT TIME ZONE 'utc')),
  ('sdg_composite_score', (SELECT id FROM areas WHERE type = 'district' AND slug = 'nainital'), DATE '2016-03-31', 67, (SELECT id FROM sources WHERE source_key = 'uk-district-composite-index'), (now() AT TIME ZONE 'utc')),
  ('sdg_composite_rank', (SELECT id FROM areas WHERE type = 'district' AND slug = 'nainital'), DATE '2016-03-31', 2, (SELECT id FROM sources WHERE source_key = 'uk-district-composite-index'), (now() AT TIME ZONE 'utc')),
  ('sdg_composite_score', (SELECT id FROM areas WHERE type = 'district' AND slug = 'nainital'), DATE '2017-03-31', 67, (SELECT id FROM sources WHERE source_key = 'uk-district-composite-index'), (now() AT TIME ZONE 'utc')),
  ('sdg_composite_rank', (SELECT id FROM areas WHERE type = 'district' AND slug = 'nainital'), DATE '2017-03-31', 5, (SELECT id FROM sources WHERE source_key = 'uk-district-composite-index'), (now() AT TIME ZONE 'utc')),
  ('sdg_composite_score', (SELECT id FROM areas WHERE type = 'district' AND slug = 'nainital'), DATE '2018-03-31', 63, (SELECT id FROM sources WHERE source_key = 'uk-district-composite-index'), (now() AT TIME ZONE 'utc')),
  ('sdg_composite_rank', (SELECT id FROM areas WHERE type = 'district' AND slug = 'nainital'), DATE '2018-03-31', 5, (SELECT id FROM sources WHERE source_key = 'uk-district-composite-index'), (now() AT TIME ZONE 'utc')),
  ('sdg_composite_score', (SELECT id FROM areas WHERE type = 'district' AND slug = 'nainital'), DATE '2019-03-31', 62, (SELECT id FROM sources WHERE source_key = 'uk-district-composite-index'), (now() AT TIME ZONE 'utc')),
  ('sdg_composite_rank', (SELECT id FROM areas WHERE type = 'district' AND slug = 'nainital'), DATE '2019-03-31', 3, (SELECT id FROM sources WHERE source_key = 'uk-district-composite-index'), (now() AT TIME ZONE 'utc')),
  ('sdg_composite_score', (SELECT id FROM areas WHERE type = 'district' AND slug = 'nainital'), DATE '2020-03-31', 68, (SELECT id FROM sources WHERE source_key = 'uk-district-composite-index'), (now() AT TIME ZONE 'utc')),
  ('sdg_composite_rank', (SELECT id FROM areas WHERE type = 'district' AND slug = 'nainital'), DATE '2020-03-31', 2, (SELECT id FROM sources WHERE source_key = 'uk-district-composite-index'), (now() AT TIME ZONE 'utc')),
  ('sdg_composite_score', (SELECT id FROM areas WHERE type = 'district' AND slug = 'nainital'), DATE '2021-03-31', 65, (SELECT id FROM sources WHERE source_key = 'uk-district-composite-index'), (now() AT TIME ZONE 'utc')),
  ('sdg_composite_rank', (SELECT id FROM areas WHERE type = 'district' AND slug = 'nainital'), DATE '2021-03-31', 4, (SELECT id FROM sources WHERE source_key = 'uk-district-composite-index'), (now() AT TIME ZONE 'utc')),
  ('sdg_composite_score', (SELECT id FROM areas WHERE type = 'district' AND slug = 'pauri-garhwal'), DATE '2016-03-31', 67, (SELECT id FROM sources WHERE source_key = 'uk-district-composite-index'), (now() AT TIME ZONE 'utc')),
  ('sdg_composite_rank', (SELECT id FROM areas WHERE type = 'district' AND slug = 'pauri-garhwal'), DATE '2016-03-31', 2, (SELECT id FROM sources WHERE source_key = 'uk-district-composite-index'), (now() AT TIME ZONE 'utc')),
  ('sdg_composite_score', (SELECT id FROM areas WHERE type = 'district' AND slug = 'pauri-garhwal'), DATE '2017-03-31', 60, (SELECT id FROM sources WHERE source_key = 'uk-district-composite-index'), (now() AT TIME ZONE 'utc')),
  ('sdg_composite_rank', (SELECT id FROM areas WHERE type = 'district' AND slug = 'pauri-garhwal'), DATE '2017-03-31', 8, (SELECT id FROM sources WHERE source_key = 'uk-district-composite-index'), (now() AT TIME ZONE 'utc')),
  ('sdg_composite_score', (SELECT id FROM areas WHERE type = 'district' AND slug = 'pauri-garhwal'), DATE '2018-03-31', 64, (SELECT id FROM sources WHERE source_key = 'uk-district-composite-index'), (now() AT TIME ZONE 'utc')),
  ('sdg_composite_rank', (SELECT id FROM areas WHERE type = 'district' AND slug = 'pauri-garhwal'), DATE '2018-03-31', 4, (SELECT id FROM sources WHERE source_key = 'uk-district-composite-index'), (now() AT TIME ZONE 'utc')),
  ('sdg_composite_score', (SELECT id FROM areas WHERE type = 'district' AND slug = 'pauri-garhwal'), DATE '2019-03-31', 59, (SELECT id FROM sources WHERE source_key = 'uk-district-composite-index'), (now() AT TIME ZONE 'utc')),
  ('sdg_composite_rank', (SELECT id FROM areas WHERE type = 'district' AND slug = 'pauri-garhwal'), DATE '2019-03-31', 6, (SELECT id FROM sources WHERE source_key = 'uk-district-composite-index'), (now() AT TIME ZONE 'utc')),
  ('sdg_composite_score', (SELECT id FROM areas WHERE type = 'district' AND slug = 'pauri-garhwal'), DATE '2020-03-31', 61, (SELECT id FROM sources WHERE source_key = 'uk-district-composite-index'), (now() AT TIME ZONE 'utc')),
  ('sdg_composite_rank', (SELECT id FROM areas WHERE type = 'district' AND slug = 'pauri-garhwal'), DATE '2020-03-31', 8, (SELECT id FROM sources WHERE source_key = 'uk-district-composite-index'), (now() AT TIME ZONE 'utc')),
  ('sdg_composite_score', (SELECT id FROM areas WHERE type = 'district' AND slug = 'pauri-garhwal'), DATE '2021-03-31', 67, (SELECT id FROM sources WHERE source_key = 'uk-district-composite-index'), (now() AT TIME ZONE 'utc')),
  ('sdg_composite_rank', (SELECT id FROM areas WHERE type = 'district' AND slug = 'pauri-garhwal'), DATE '2021-03-31', 2, (SELECT id FROM sources WHERE source_key = 'uk-district-composite-index'), (now() AT TIME ZONE 'utc')),
  ('sdg_composite_score', (SELECT id FROM areas WHERE type = 'district' AND slug = 'pithoragarh'), DATE '2016-03-31', 57, (SELECT id FROM sources WHERE source_key = 'uk-district-composite-index'), (now() AT TIME ZONE 'utc')),
  ('sdg_composite_rank', (SELECT id FROM areas WHERE type = 'district' AND slug = 'pithoragarh'), DATE '2016-03-31', 8, (SELECT id FROM sources WHERE source_key = 'uk-district-composite-index'), (now() AT TIME ZONE 'utc')),
  ('sdg_composite_score', (SELECT id FROM areas WHERE type = 'district' AND slug = 'pithoragarh'), DATE '2017-03-31', 61, (SELECT id FROM sources WHERE source_key = 'uk-district-composite-index'), (now() AT TIME ZONE 'utc')),
  ('sdg_composite_rank', (SELECT id FROM areas WHERE type = 'district' AND slug = 'pithoragarh'), DATE '2017-03-31', 7, (SELECT id FROM sources WHERE source_key = 'uk-district-composite-index'), (now() AT TIME ZONE 'utc')),
  ('sdg_composite_score', (SELECT id FROM areas WHERE type = 'district' AND slug = 'pithoragarh'), DATE '2018-03-31', 56, (SELECT id FROM sources WHERE source_key = 'uk-district-composite-index'), (now() AT TIME ZONE 'utc')),
  ('sdg_composite_rank', (SELECT id FROM areas WHERE type = 'district' AND slug = 'pithoragarh'), DATE '2018-03-31', 9, (SELECT id FROM sources WHERE source_key = 'uk-district-composite-index'), (now() AT TIME ZONE 'utc')),
  ('sdg_composite_score', (SELECT id FROM areas WHERE type = 'district' AND slug = 'pithoragarh'), DATE '2019-03-31', 63, (SELECT id FROM sources WHERE source_key = 'uk-district-composite-index'), (now() AT TIME ZONE 'utc')),
  ('sdg_composite_rank', (SELECT id FROM areas WHERE type = 'district' AND slug = 'pithoragarh'), DATE '2019-03-31', 2, (SELECT id FROM sources WHERE source_key = 'uk-district-composite-index'), (now() AT TIME ZONE 'utc')),
  ('sdg_composite_score', (SELECT id FROM areas WHERE type = 'district' AND slug = 'pithoragarh'), DATE '2020-03-31', 58, (SELECT id FROM sources WHERE source_key = 'uk-district-composite-index'), (now() AT TIME ZONE 'utc')),
  ('sdg_composite_rank', (SELECT id FROM areas WHERE type = 'district' AND slug = 'pithoragarh'), DATE '2020-03-31', 9, (SELECT id FROM sources WHERE source_key = 'uk-district-composite-index'), (now() AT TIME ZONE 'utc')),
  ('sdg_composite_score', (SELECT id FROM areas WHERE type = 'district' AND slug = 'pithoragarh'), DATE '2021-03-31', 63, (SELECT id FROM sources WHERE source_key = 'uk-district-composite-index'), (now() AT TIME ZONE 'utc')),
  ('sdg_composite_rank', (SELECT id FROM areas WHERE type = 'district' AND slug = 'pithoragarh'), DATE '2021-03-31', 6, (SELECT id FROM sources WHERE source_key = 'uk-district-composite-index'), (now() AT TIME ZONE 'utc')),
  ('sdg_composite_score', (SELECT id FROM areas WHERE type = 'district' AND slug = 'rudraprayag'), DATE '2016-03-31', 60, (SELECT id FROM sources WHERE source_key = 'uk-district-composite-index'), (now() AT TIME ZONE 'utc')),
  ('sdg_composite_rank', (SELECT id FROM areas WHERE type = 'district' AND slug = 'rudraprayag'), DATE '2016-03-31', 7, (SELECT id FROM sources WHERE source_key = 'uk-district-composite-index'), (now() AT TIME ZONE 'utc')),
  ('sdg_composite_score', (SELECT id FROM areas WHERE type = 'district' AND slug = 'rudraprayag'), DATE '2017-03-31', 71, (SELECT id FROM sources WHERE source_key = 'uk-district-composite-index'), (now() AT TIME ZONE 'utc')),
  ('sdg_composite_rank', (SELECT id FROM areas WHERE type = 'district' AND slug = 'rudraprayag'), DATE '2017-03-31', 1, (SELECT id FROM sources WHERE source_key = 'uk-district-composite-index'), (now() AT TIME ZONE 'utc')),
  ('sdg_composite_score', (SELECT id FROM areas WHERE type = 'district' AND slug = 'rudraprayag'), DATE '2018-03-31', 66, (SELECT id FROM sources WHERE source_key = 'uk-district-composite-index'), (now() AT TIME ZONE 'utc')),
  ('sdg_composite_rank', (SELECT id FROM areas WHERE type = 'district' AND slug = 'rudraprayag'), DATE '2018-03-31', 2, (SELECT id FROM sources WHERE source_key = 'uk-district-composite-index'), (now() AT TIME ZONE 'utc')),
  ('sdg_composite_score', (SELECT id FROM areas WHERE type = 'district' AND slug = 'rudraprayag'), DATE '2019-03-31', 61, (SELECT id FROM sources WHERE source_key = 'uk-district-composite-index'), (now() AT TIME ZONE 'utc')),
  ('sdg_composite_rank', (SELECT id FROM areas WHERE type = 'district' AND slug = 'rudraprayag'), DATE '2019-03-31', 4, (SELECT id FROM sources WHERE source_key = 'uk-district-composite-index'), (now() AT TIME ZONE 'utc')),
  ('sdg_composite_score', (SELECT id FROM areas WHERE type = 'district' AND slug = 'rudraprayag'), DATE '2020-03-31', 63, (SELECT id FROM sources WHERE source_key = 'uk-district-composite-index'), (now() AT TIME ZONE 'utc')),
  ('sdg_composite_rank', (SELECT id FROM areas WHERE type = 'district' AND slug = 'rudraprayag'), DATE '2020-03-31', 6, (SELECT id FROM sources WHERE source_key = 'uk-district-composite-index'), (now() AT TIME ZONE 'utc')),
  ('sdg_composite_score', (SELECT id FROM areas WHERE type = 'district' AND slug = 'rudraprayag'), DATE '2021-03-31', 65, (SELECT id FROM sources WHERE source_key = 'uk-district-composite-index'), (now() AT TIME ZONE 'utc')),
  ('sdg_composite_rank', (SELECT id FROM areas WHERE type = 'district' AND slug = 'rudraprayag'), DATE '2021-03-31', 4, (SELECT id FROM sources WHERE source_key = 'uk-district-composite-index'), (now() AT TIME ZONE 'utc')),
  ('sdg_composite_score', (SELECT id FROM areas WHERE type = 'district' AND slug = 'tehri-garhwal'), DATE '2016-03-31', 62, (SELECT id FROM sources WHERE source_key = 'uk-district-composite-index'), (now() AT TIME ZONE 'utc')),
  ('sdg_composite_rank', (SELECT id FROM areas WHERE type = 'district' AND slug = 'tehri-garhwal'), DATE '2016-03-31', 5, (SELECT id FROM sources WHERE source_key = 'uk-district-composite-index'), (now() AT TIME ZONE 'utc')),
  ('sdg_composite_score', (SELECT id FROM areas WHERE type = 'district' AND slug = 'tehri-garhwal'), DATE '2017-03-31', 65, (SELECT id FROM sources WHERE source_key = 'uk-district-composite-index'), (now() AT TIME ZONE 'utc')),
  ('sdg_composite_rank', (SELECT id FROM areas WHERE type = 'district' AND slug = 'tehri-garhwal'), DATE '2017-03-31', 6, (SELECT id FROM sources WHERE source_key = 'uk-district-composite-index'), (now() AT TIME ZONE 'utc')),
  ('sdg_composite_score', (SELECT id FROM areas WHERE type = 'district' AND slug = 'tehri-garhwal'), DATE '2018-03-31', 62, (SELECT id FROM sources WHERE source_key = 'uk-district-composite-index'), (now() AT TIME ZONE 'utc')),
  ('sdg_composite_rank', (SELECT id FROM areas WHERE type = 'district' AND slug = 'tehri-garhwal'), DATE '2018-03-31', 6, (SELECT id FROM sources WHERE source_key = 'uk-district-composite-index'), (now() AT TIME ZONE 'utc')),
  ('sdg_composite_score', (SELECT id FROM areas WHERE type = 'district' AND slug = 'tehri-garhwal'), DATE '2019-03-31', 63, (SELECT id FROM sources WHERE source_key = 'uk-district-composite-index'), (now() AT TIME ZONE 'utc')),
  ('sdg_composite_rank', (SELECT id FROM areas WHERE type = 'district' AND slug = 'tehri-garhwal'), DATE '2019-03-31', 2, (SELECT id FROM sources WHERE source_key = 'uk-district-composite-index'), (now() AT TIME ZONE 'utc')),
  ('sdg_composite_score', (SELECT id FROM areas WHERE type = 'district' AND slug = 'tehri-garhwal'), DATE '2020-03-31', 58, (SELECT id FROM sources WHERE source_key = 'uk-district-composite-index'), (now() AT TIME ZONE 'utc')),
  ('sdg_composite_rank', (SELECT id FROM areas WHERE type = 'district' AND slug = 'tehri-garhwal'), DATE '2020-03-31', 9, (SELECT id FROM sources WHERE source_key = 'uk-district-composite-index'), (now() AT TIME ZONE 'utc')),
  ('sdg_composite_score', (SELECT id FROM areas WHERE type = 'district' AND slug = 'tehri-garhwal'), DATE '2021-03-31', 59, (SELECT id FROM sources WHERE source_key = 'uk-district-composite-index'), (now() AT TIME ZONE 'utc')),
  ('sdg_composite_rank', (SELECT id FROM areas WHERE type = 'district' AND slug = 'tehri-garhwal'), DATE '2021-03-31', 7, (SELECT id FROM sources WHERE source_key = 'uk-district-composite-index'), (now() AT TIME ZONE 'utc')),
  ('sdg_composite_score', (SELECT id FROM areas WHERE type = 'district' AND slug = 'udham-singh-nagar'), DATE '2016-03-31', 61, (SELECT id FROM sources WHERE source_key = 'uk-district-composite-index'), (now() AT TIME ZONE 'utc')),
  ('sdg_composite_rank', (SELECT id FROM areas WHERE type = 'district' AND slug = 'udham-singh-nagar'), DATE '2016-03-31', 6, (SELECT id FROM sources WHERE source_key = 'uk-district-composite-index'), (now() AT TIME ZONE 'utc')),
  ('sdg_composite_score', (SELECT id FROM areas WHERE type = 'district' AND slug = 'udham-singh-nagar'), DATE '2017-03-31', 59, (SELECT id FROM sources WHERE source_key = 'uk-district-composite-index'), (now() AT TIME ZONE 'utc')),
  ('sdg_composite_rank', (SELECT id FROM areas WHERE type = 'district' AND slug = 'udham-singh-nagar'), DATE '2017-03-31', 9, (SELECT id FROM sources WHERE source_key = 'uk-district-composite-index'), (now() AT TIME ZONE 'utc')),
  ('sdg_composite_score', (SELECT id FROM areas WHERE type = 'district' AND slug = 'udham-singh-nagar'), DATE '2018-03-31', 60, (SELECT id FROM sources WHERE source_key = 'uk-district-composite-index'), (now() AT TIME ZONE 'utc')),
  ('sdg_composite_rank', (SELECT id FROM areas WHERE type = 'district' AND slug = 'udham-singh-nagar'), DATE '2018-03-31', 7, (SELECT id FROM sources WHERE source_key = 'uk-district-composite-index'), (now() AT TIME ZONE 'utc')),
  ('sdg_composite_score', (SELECT id FROM areas WHERE type = 'district' AND slug = 'udham-singh-nagar'), DATE '2019-03-31', 53, (SELECT id FROM sources WHERE source_key = 'uk-district-composite-index'), (now() AT TIME ZONE 'utc')),
  ('sdg_composite_rank', (SELECT id FROM areas WHERE type = 'district' AND slug = 'udham-singh-nagar'), DATE '2019-03-31', 8, (SELECT id FROM sources WHERE source_key = 'uk-district-composite-index'), (now() AT TIME ZONE 'utc')),
  ('sdg_composite_score', (SELECT id FROM areas WHERE type = 'district' AND slug = 'udham-singh-nagar'), DATE '2020-03-31', 54, (SELECT id FROM sources WHERE source_key = 'uk-district-composite-index'), (now() AT TIME ZONE 'utc')),
  ('sdg_composite_rank', (SELECT id FROM areas WHERE type = 'district' AND slug = 'udham-singh-nagar'), DATE '2020-03-31', 10, (SELECT id FROM sources WHERE source_key = 'uk-district-composite-index'), (now() AT TIME ZONE 'utc')),
  ('sdg_composite_score', (SELECT id FROM areas WHERE type = 'district' AND slug = 'udham-singh-nagar'), DATE '2021-03-31', 58, (SELECT id FROM sources WHERE source_key = 'uk-district-composite-index'), (now() AT TIME ZONE 'utc')),
  ('sdg_composite_rank', (SELECT id FROM areas WHERE type = 'district' AND slug = 'udham-singh-nagar'), DATE '2021-03-31', 8, (SELECT id FROM sources WHERE source_key = 'uk-district-composite-index'), (now() AT TIME ZONE 'utc')),
  ('sdg_composite_score', (SELECT id FROM areas WHERE type = 'district' AND slug = 'uttarkashi'), DATE '2016-03-31', 65, (SELECT id FROM sources WHERE source_key = 'uk-district-composite-index'), (now() AT TIME ZONE 'utc')),
  ('sdg_composite_rank', (SELECT id FROM areas WHERE type = 'district' AND slug = 'uttarkashi'), DATE '2016-03-31', 3, (SELECT id FROM sources WHERE source_key = 'uk-district-composite-index'), (now() AT TIME ZONE 'utc')),
  ('sdg_composite_score', (SELECT id FROM areas WHERE type = 'district' AND slug = 'uttarkashi'), DATE '2017-03-31', 69, (SELECT id FROM sources WHERE source_key = 'uk-district-composite-index'), (now() AT TIME ZONE 'utc')),
  ('sdg_composite_rank', (SELECT id FROM areas WHERE type = 'district' AND slug = 'uttarkashi'), DATE '2017-03-31', 3, (SELECT id FROM sources WHERE source_key = 'uk-district-composite-index'), (now() AT TIME ZONE 'utc')),
  ('sdg_composite_score', (SELECT id FROM areas WHERE type = 'district' AND slug = 'uttarkashi'), DATE '2018-03-31', 65, (SELECT id FROM sources WHERE source_key = 'uk-district-composite-index'), (now() AT TIME ZONE 'utc')),
  ('sdg_composite_rank', (SELECT id FROM areas WHERE type = 'district' AND slug = 'uttarkashi'), DATE '2018-03-31', 3, (SELECT id FROM sources WHERE source_key = 'uk-district-composite-index'), (now() AT TIME ZONE 'utc')),
  ('sdg_composite_score', (SELECT id FROM areas WHERE type = 'district' AND slug = 'uttarkashi'), DATE '2019-03-31', 61, (SELECT id FROM sources WHERE source_key = 'uk-district-composite-index'), (now() AT TIME ZONE 'utc')),
  ('sdg_composite_rank', (SELECT id FROM areas WHERE type = 'district' AND slug = 'uttarkashi'), DATE '2019-03-31', 4, (SELECT id FROM sources WHERE source_key = 'uk-district-composite-index'), (now() AT TIME ZONE 'utc')),
  ('sdg_composite_score', (SELECT id FROM areas WHERE type = 'district' AND slug = 'uttarkashi'), DATE '2020-03-31', 63, (SELECT id FROM sources WHERE source_key = 'uk-district-composite-index'), (now() AT TIME ZONE 'utc')),
  ('sdg_composite_rank', (SELECT id FROM areas WHERE type = 'district' AND slug = 'uttarkashi'), DATE '2020-03-31', 6, (SELECT id FROM sources WHERE source_key = 'uk-district-composite-index'), (now() AT TIME ZONE 'utc')),
  ('sdg_composite_score', (SELECT id FROM areas WHERE type = 'district' AND slug = 'uttarkashi'), DATE '2021-03-31', 64, (SELECT id FROM sources WHERE source_key = 'uk-district-composite-index'), (now() AT TIME ZONE 'utc')),
  ('sdg_composite_rank', (SELECT id FROM areas WHERE type = 'district' AND slug = 'uttarkashi'), DATE '2021-03-31', 5, (SELECT id FROM sources WHERE source_key = 'uk-district-composite-index'), (now() AT TIME ZONE 'utc')),
  ('tourist_accommodation_units', (SELECT id FROM areas WHERE type = 'district' AND slug = 'almora'), DATE '2022-03-31', 410, (SELECT id FROM sources WHERE source_key = 'uk-tourism-capacity'), (now() AT TIME ZONE 'utc')),
  ('tourist_accommodation_beds', (SELECT id FROM areas WHERE type = 'district' AND slug = 'almora'), DATE '2022-03-31', 6110, (SELECT id FROM sources WHERE source_key = 'uk-tourism-capacity'), (now() AT TIME ZONE 'utc')),
  ('pilgrim_shelter_capacity', (SELECT id FROM areas WHERE type = 'district' AND slug = 'almora'), DATE '2022-03-31', 138, (SELECT id FROM sources WHERE source_key = 'uk-tourism-capacity'), (now() AT TIME ZONE 'utc')),
  ('govt_accommodation_beds', (SELECT id FROM areas WHERE type = 'district' AND slug = 'almora'), DATE '2022-03-31', 674, (SELECT id FROM sources WHERE source_key = 'uk-tourism-capacity'), (now() AT TIME ZONE 'utc')),
  ('tourist_accommodation_units', (SELECT id FROM areas WHERE type = 'district' AND slug = 'bageshwar'), DATE '2022-03-31', 137, (SELECT id FROM sources WHERE source_key = 'uk-tourism-capacity'), (now() AT TIME ZONE 'utc')),
  ('tourist_accommodation_beds', (SELECT id FROM areas WHERE type = 'district' AND slug = 'bageshwar'), DATE '2022-03-31', 1999, (SELECT id FROM sources WHERE source_key = 'uk-tourism-capacity'), (now() AT TIME ZONE 'utc')),
  ('pilgrim_shelter_capacity', (SELECT id FROM areas WHERE type = 'district' AND slug = 'bageshwar'), DATE '2022-03-31', 15, (SELECT id FROM sources WHERE source_key = 'uk-tourism-capacity'), (now() AT TIME ZONE 'utc')),
  ('govt_accommodation_beds', (SELECT id FROM areas WHERE type = 'district' AND slug = 'bageshwar'), DATE '2022-03-31', 385, (SELECT id FROM sources WHERE source_key = 'uk-tourism-capacity'), (now() AT TIME ZONE 'utc')),
  ('tourist_accommodation_units', (SELECT id FROM areas WHERE type = 'district' AND slug = 'chamoli'), DATE '2022-03-31', 852, (SELECT id FROM sources WHERE source_key = 'uk-tourism-capacity'), (now() AT TIME ZONE 'utc')),
  ('tourist_accommodation_beds', (SELECT id FROM areas WHERE type = 'district' AND slug = 'chamoli'), DATE '2022-03-31', 24696, (SELECT id FROM sources WHERE source_key = 'uk-tourism-capacity'), (now() AT TIME ZONE 'utc')),
  ('pilgrim_shelter_capacity', (SELECT id FROM areas WHERE type = 'district' AND slug = 'chamoli'), DATE '2022-03-31', 3962, (SELECT id FROM sources WHERE source_key = 'uk-tourism-capacity'), (now() AT TIME ZONE 'utc')),
  ('govt_accommodation_beds', (SELECT id FROM areas WHERE type = 'district' AND slug = 'chamoli'), DATE '2022-03-31', 1852, (SELECT id FROM sources WHERE source_key = 'uk-tourism-capacity'), (now() AT TIME ZONE 'utc')),
  ('tourist_accommodation_units', (SELECT id FROM areas WHERE type = 'district' AND slug = 'champawat'), DATE '2022-03-31', 131, (SELECT id FROM sources WHERE source_key = 'uk-tourism-capacity'), (now() AT TIME ZONE 'utc')),
  ('tourist_accommodation_beds', (SELECT id FROM areas WHERE type = 'district' AND slug = 'champawat'), DATE '2022-03-31', 1678, (SELECT id FROM sources WHERE source_key = 'uk-tourism-capacity'), (now() AT TIME ZONE 'utc')),
  ('pilgrim_shelter_capacity', (SELECT id FROM areas WHERE type = 'district' AND slug = 'champawat'), DATE '2022-03-31', 4220, (SELECT id FROM sources WHERE source_key = 'uk-tourism-capacity'), (now() AT TIME ZONE 'utc')),
  ('govt_accommodation_beds', (SELECT id FROM areas WHERE type = 'district' AND slug = 'champawat'), DATE '2022-03-31', 248, (SELECT id FROM sources WHERE source_key = 'uk-tourism-capacity'), (now() AT TIME ZONE 'utc')),
  ('tourist_accommodation_units', (SELECT id FROM areas WHERE type = 'district' AND slug = 'dehradun'), DATE '2022-03-31', 1376, (SELECT id FROM sources WHERE source_key = 'uk-tourism-capacity'), (now() AT TIME ZONE 'utc')),
  ('tourist_accommodation_beds', (SELECT id FROM areas WHERE type = 'district' AND slug = 'dehradun'), DATE '2022-03-31', 31701, (SELECT id FROM sources WHERE source_key = 'uk-tourism-capacity'), (now() AT TIME ZONE 'utc')),
  ('pilgrim_shelter_capacity', (SELECT id FROM areas WHERE type = 'district' AND slug = 'dehradun'), DATE '2022-03-31', 3456, (SELECT id FROM sources WHERE source_key = 'uk-tourism-capacity'), (now() AT TIME ZONE 'utc')),
  ('govt_accommodation_beds', (SELECT id FROM areas WHERE type = 'district' AND slug = 'dehradun'), DATE '2022-03-31', 1010, (SELECT id FROM sources WHERE source_key = 'uk-tourism-capacity'), (now() AT TIME ZONE 'utc')),
  ('tourist_accommodation_units', (SELECT id FROM areas WHERE type = 'district' AND slug = 'haridwar'), DATE '2022-03-31', 535, (SELECT id FROM sources WHERE source_key = 'uk-tourism-capacity'), (now() AT TIME ZONE 'utc')),
  ('tourist_accommodation_beds', (SELECT id FROM areas WHERE type = 'district' AND slug = 'haridwar'), DATE '2022-03-31', 18225, (SELECT id FROM sources WHERE source_key = 'uk-tourism-capacity'), (now() AT TIME ZONE 'utc')),
  ('pilgrim_shelter_capacity', (SELECT id FROM areas WHERE type = 'district' AND slug = 'haridwar'), DATE '2022-03-31', 96750, (SELECT id FROM sources WHERE source_key = 'uk-tourism-capacity'), (now() AT TIME ZONE 'utc')),
  ('govt_accommodation_beds', (SELECT id FROM areas WHERE type = 'district' AND slug = 'haridwar'), DATE '2022-03-31', 306, (SELECT id FROM sources WHERE source_key = 'uk-tourism-capacity'), (now() AT TIME ZONE 'utc')),
  ('tourist_accommodation_units', (SELECT id FROM areas WHERE type = 'district' AND slug = 'nainital'), DATE '2022-03-31', 1036, (SELECT id FROM sources WHERE source_key = 'uk-tourism-capacity'), (now() AT TIME ZONE 'utc')),
  ('tourist_accommodation_beds', (SELECT id FROM areas WHERE type = 'district' AND slug = 'nainital'), DATE '2022-03-31', 47656, (SELECT id FROM sources WHERE source_key = 'uk-tourism-capacity'), (now() AT TIME ZONE 'utc')),
  ('pilgrim_shelter_capacity', (SELECT id FROM areas WHERE type = 'district' AND slug = 'nainital'), DATE '2022-03-31', 1756, (SELECT id FROM sources WHERE source_key = 'uk-tourism-capacity'), (now() AT TIME ZONE 'utc')),
  ('govt_accommodation_beds', (SELECT id FROM areas WHERE type = 'district' AND slug = 'nainital'), DATE '2022-03-31', 799, (SELECT id FROM sources WHERE source_key = 'uk-tourism-capacity'), (now() AT TIME ZONE 'utc')),
  ('tourist_accommodation_units', (SELECT id FROM areas WHERE type = 'district' AND slug = 'pauri-garhwal'), DATE '2022-03-31', 421, (SELECT id FROM sources WHERE source_key = 'uk-tourism-capacity'), (now() AT TIME ZONE 'utc')),
  ('tourist_accommodation_beds', (SELECT id FROM areas WHERE type = 'district' AND slug = 'pauri-garhwal'), DATE '2022-03-31', 8055, (SELECT id FROM sources WHERE source_key = 'uk-tourism-capacity'), (now() AT TIME ZONE 'utc')),
  ('pilgrim_shelter_capacity', (SELECT id FROM areas WHERE type = 'district' AND slug = 'pauri-garhwal'), DATE '2022-03-31', 12042, (SELECT id FROM sources WHERE source_key = 'uk-tourism-capacity'), (now() AT TIME ZONE 'utc')),
  ('govt_accommodation_beds', (SELECT id FROM areas WHERE type = 'district' AND slug = 'pauri-garhwal'), DATE '2022-03-31', 1050, (SELECT id FROM sources WHERE source_key = 'uk-tourism-capacity'), (now() AT TIME ZONE 'utc')),
  ('tourist_accommodation_units', (SELECT id FROM areas WHERE type = 'district' AND slug = 'pithoragarh'), DATE '2022-03-31', 651, (SELECT id FROM sources WHERE source_key = 'uk-tourism-capacity'), (now() AT TIME ZONE 'utc')),
  ('tourist_accommodation_beds', (SELECT id FROM areas WHERE type = 'district' AND slug = 'pithoragarh'), DATE '2022-03-31', 4903, (SELECT id FROM sources WHERE source_key = 'uk-tourism-capacity'), (now() AT TIME ZONE 'utc')),
  ('pilgrim_shelter_capacity', (SELECT id FROM areas WHERE type = 'district' AND slug = 'pithoragarh'), DATE '2022-03-31', 70, (SELECT id FROM sources WHERE source_key = 'uk-tourism-capacity'), (now() AT TIME ZONE 'utc')),
  ('govt_accommodation_beds', (SELECT id FROM areas WHERE type = 'district' AND slug = 'pithoragarh'), DATE '2022-03-31', 524, (SELECT id FROM sources WHERE source_key = 'uk-tourism-capacity'), (now() AT TIME ZONE 'utc')),
  ('tourist_accommodation_units', (SELECT id FROM areas WHERE type = 'district' AND slug = 'rudraprayag'), DATE '2022-03-31', 476, (SELECT id FROM sources WHERE source_key = 'uk-tourism-capacity'), (now() AT TIME ZONE 'utc')),
  ('tourist_accommodation_beds', (SELECT id FROM areas WHERE type = 'district' AND slug = 'rudraprayag'), DATE '2022-03-31', 10084, (SELECT id FROM sources WHERE source_key = 'uk-tourism-capacity'), (now() AT TIME ZONE 'utc')),
  ('pilgrim_shelter_capacity', (SELECT id FROM areas WHERE type = 'district' AND slug = 'rudraprayag'), DATE '2022-03-31', 204, (SELECT id FROM sources WHERE source_key = 'uk-tourism-capacity'), (now() AT TIME ZONE 'utc')),
  ('govt_accommodation_beds', (SELECT id FROM areas WHERE type = 'district' AND slug = 'rudraprayag'), DATE '2022-03-31', 1549, (SELECT id FROM sources WHERE source_key = 'uk-tourism-capacity'), (now() AT TIME ZONE 'utc')),
  ('tourist_accommodation_units', (SELECT id FROM areas WHERE type = 'district' AND slug = 'tehri-garhwal'), DATE '2022-03-31', 797, (SELECT id FROM sources WHERE source_key = 'uk-tourism-capacity'), (now() AT TIME ZONE 'utc')),
  ('tourist_accommodation_beds', (SELECT id FROM areas WHERE type = 'district' AND slug = 'tehri-garhwal'), DATE '2022-03-31', 16930, (SELECT id FROM sources WHERE source_key = 'uk-tourism-capacity'), (now() AT TIME ZONE 'utc')),
  ('pilgrim_shelter_capacity', (SELECT id FROM areas WHERE type = 'district' AND slug = 'tehri-garhwal'), DATE '2022-03-31', 9660, (SELECT id FROM sources WHERE source_key = 'uk-tourism-capacity'), (now() AT TIME ZONE 'utc')),
  ('govt_accommodation_beds', (SELECT id FROM areas WHERE type = 'district' AND slug = 'tehri-garhwal'), DATE '2022-03-31', 778, (SELECT id FROM sources WHERE source_key = 'uk-tourism-capacity'), (now() AT TIME ZONE 'utc')),
  ('tourist_accommodation_units', (SELECT id FROM areas WHERE type = 'district' AND slug = 'udham-singh-nagar'), DATE '2022-03-31', 131, (SELECT id FROM sources WHERE source_key = 'uk-tourism-capacity'), (now() AT TIME ZONE 'utc')),
  ('tourist_accommodation_beds', (SELECT id FROM areas WHERE type = 'district' AND slug = 'udham-singh-nagar'), DATE '2022-03-31', 3725, (SELECT id FROM sources WHERE source_key = 'uk-tourism-capacity'), (now() AT TIME ZONE 'utc')),
  ('pilgrim_shelter_capacity', (SELECT id FROM areas WHERE type = 'district' AND slug = 'udham-singh-nagar'), DATE '2022-03-31', 2470, (SELECT id FROM sources WHERE source_key = 'uk-tourism-capacity'), (now() AT TIME ZONE 'utc')),
  ('govt_accommodation_beds', (SELECT id FROM areas WHERE type = 'district' AND slug = 'udham-singh-nagar'), DATE '2022-03-31', 156, (SELECT id FROM sources WHERE source_key = 'uk-tourism-capacity'), (now() AT TIME ZONE 'utc')),
  ('tourist_accommodation_units', (SELECT id FROM areas WHERE type = 'district' AND slug = 'uttarkashi'), DATE '2022-03-31', 669, (SELECT id FROM sources WHERE source_key = 'uk-tourism-capacity'), (now() AT TIME ZONE 'utc')),
  ('tourist_accommodation_beds', (SELECT id FROM areas WHERE type = 'district' AND slug = 'uttarkashi'), DATE '2022-03-31', 13237, (SELECT id FROM sources WHERE source_key = 'uk-tourism-capacity'), (now() AT TIME ZONE 'utc')),
  ('pilgrim_shelter_capacity', (SELECT id FROM areas WHERE type = 'district' AND slug = 'uttarkashi'), DATE '2022-03-31', 419, (SELECT id FROM sources WHERE source_key = 'uk-tourism-capacity'), (now() AT TIME ZONE 'utc')),
  ('govt_accommodation_beds', (SELECT id FROM areas WHERE type = 'district' AND slug = 'uttarkashi'), DATE '2022-03-31', 641, (SELECT id FROM sources WHERE source_key = 'uk-tourism-capacity'), (now() AT TIME ZONE 'utc')),
  ('char_dham_pilgrims', (SELECT id FROM areas WHERE type = 'state' AND code = 'UK'), DATE '2019-12-31', 3477957, (SELECT id FROM sources WHERE source_key = 'uk-tourism-capacity'), (now() AT TIME ZONE 'utc')),
  ('char_dham_pilgrims', (SELECT id FROM areas WHERE type = 'state' AND code = 'UK'), DATE '2020-12-31', 330039, (SELECT id FROM sources WHERE source_key = 'uk-tourism-capacity'), (now() AT TIME ZONE 'utc')),
  ('char_dham_pilgrims', (SELECT id FROM areas WHERE type = 'state' AND code = 'UK'), DATE '2021-12-31', 529382, (SELECT id FROM sources WHERE source_key = 'uk-tourism-capacity'), (now() AT TIME ZONE 'utc')),
  ('schools_count', (SELECT id FROM areas WHERE type = 'district' AND slug = 'almora'), DATE '2017-03-31', 1980, (SELECT id FROM sources WHERE source_key = 'uk-des-district-reports'), (now() AT TIME ZONE 'utc')),
  ('hospital_beds', (SELECT id FROM areas WHERE type = 'district' AND slug = 'almora'), DATE '2017-03-31', 712, (SELECT id FROM sources WHERE source_key = 'uk-des-district-reports'), (now() AT TIME ZONE 'utc')),
  ('schools_count', (SELECT id FROM areas WHERE type = 'district' AND slug = 'pithoragarh'), DATE '2018-03-31', 1997, (SELECT id FROM sources WHERE source_key = 'uk-des-district-reports'), (now() AT TIME ZONE 'utc')),
  ('hospital_beds', (SELECT id FROM areas WHERE type = 'district' AND slug = 'pithoragarh'), DATE '2018-03-31', 612, (SELECT id FROM sources WHERE source_key = 'uk-des-district-reports'), (now() AT TIME ZONE 'utc')),
  ('schools_count', (SELECT id FROM areas WHERE type = 'district' AND slug = 'pauri-garhwal'), DATE '2017-03-31', 2699, (SELECT id FROM sources WHERE source_key = 'uk-des-district-reports'), (now() AT TIME ZONE 'utc')),
  ('hospital_beds', (SELECT id FROM areas WHERE type = 'district' AND slug = 'pauri-garhwal'), DATE '2017-03-31', 1634, (SELECT id FROM sources WHERE source_key = 'uk-des-district-reports'), (now() AT TIME ZONE 'utc'))
ON CONFLICT (indicator_key, area_id, vintage) DO UPDATE SET
  value      = EXCLUDED.value,
  source_id  = EXCLUDED.source_id,
  fetched_at = EXCLUDED.fetched_at;

-- ROLLBACK
-- DELETE FROM indicator_values WHERE indicator_key IN
--   ('sdg_composite_score','sdg_composite_rank','tourist_accommodation_units',
--    'tourist_accommodation_beds','pilgrim_shelter_capacity','govt_accommodation_beds',
--    'char_dham_pilgrims','hospital_beds','schools_count');
-- DELETE FROM indicators WHERE indicator_key IN
--   ('sdg_composite_score','sdg_composite_rank','tourist_accommodation_units',
--    'tourist_accommodation_beds','pilgrim_shelter_capacity','govt_accommodation_beds',
--    'char_dham_pilgrims','hospital_beds');
